# frozen_string_literal: true

# The base world's first book entries (docs/HANDOFF.md §2: "The base world
# is seed data: the first World and its children").
#
# Worlds are live: a GM develops theirs as they play, editing entries in the
# books. So an ordinary run only adds what's missing (a new monster, a new
# table) and never touches an entry that's already there, edited or not.
# `bin/rails base_world:update` (overwrite: true) puts every entry back to
# what's written here, for when the seed data itself has been retuned.
# Numbers are first-pass tuning (§9.2).
module Seeds
  module BaseWorld
    module_function

    def run(overwrite: false)
      @overwrite = overwrite
      world = World.find_or_initialize_by(slug: "base")
      if world.new_record? || overwrite
        world.update!(name: "Base World",
                      description: "The opinionated default setting: crystals, jobs, and a world map of towns, " \
                                   "dungeons and the roads between them.")
      end

      ABILITIES.each { |slug, attrs| upsert(world.abilities, slug, attrs) }
      ITEMS.each { |slug, attrs| upsert(world.items, slug, attrs) }
      MONSTERS.each { |slug, attrs| upsert(world.monsters, slug, attrs) }
      ENCOUNTER_TABLES.each { |slug, attrs| upsert(world.encounter_tables, slug, attrs) }
      GENERATOR_TABLES.each { |slug, attrs| upsert(world.generator_tables, slug, attrs) }
      LOCATION_TEMPLATES.each do |slug, attrs|
        table = attrs[:encounter_table] && world.encounter_tables.find_by!(slug: attrs[:encounter_table])
        upsert(world.location_templates, slug, attrs.except(:encounter_table).merge(encounter_table: table))
      end
      JOBS.each do |slug, attrs|
        levels = attrs.fetch(:levels)
        fresh = !world.jobs.exists?(slug: slug.to_s)
        job = upsert(world.jobs, slug, attrs.except(:levels))
        next unless fresh || overwrite

        job.job_levels.destroy_all
        levels.each do |ability, level|
          job.job_levels.create!(level: level, ability: world.abilities.find_by!(slug: ability))
        end
      end
      world
    end

    # Create the entry if it's missing; only rewrite an existing one when
    # overwriting.
    def upsert(scope, slug, attrs)
      record = scope.find_or_initialize_by(slug: slug.to_s)
      record.update!(attrs) if record.new_record? || @overwrite
      record
    end

    def stats(max_hp:, max_mp: 0, str: 10, mag: 10, vit: 10, spr: 10, agi: 10, atk: 0, def: 0, mdef: 0)
      { max_hp:, max_mp:, str:, mag:, vit:, spr:, agi:, atk:, def:, mdef: }
    end

    ABILITIES = {
      fire: { name: "Fire", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "flash",
              effects: [ { primitive: "elemental", type: "fire", power: 12 } ],
              description: "A burst of flame. The first spell every black mage learns and the last one they forget." },
      blizzard: { name: "Blizzard", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "flash",
                  effects: [ { primitive: "elemental", type: "ice", power: 12 } ],
                  description: "Shards of ice that sting worse than they look." },
      thunder: { name: "Thunder", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "flash",
                 effects: [ { primitive: "elemental", type: "electric", power: 12 } ],
                 description: "A single crack of lightning." },
      fira: { name: "Fira", kind: "magic", target: "all_enemies", mp_cost: 10, gesture: "flash",
              effects: [ { primitive: "elemental", type: "fire", power: 10 } ],
              description: "Fire spread across the whole enemy line." },
      sleep: { name: "Sleep", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "float",
               effects: [ { primitive: "status", kind: "sleep", chance: 70, duration: 3 } ],
               description: "Lulls a foe to sleep. A hard blow wakes them." },
      bio: { name: "Bio", kind: "magic", target: "single_enemy", mp_cost: 6, gesture: "tint",
             effects: [ { primitive: "elemental", type: "poison", power: 12 },
                       { primitive: "status", kind: "poison", chance: 100, duration: 4 } ],
             description: "Corrosive shadow that lingers as poison." },
      drain: { name: "Drain", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "tint",
               effects: [ { primitive: "drain", power: 14 } ],
               description: "Steals life from a foe and gives it to the caster." },
      cure: { name: "Cure", kind: "magic", target: "single_ally", mp_cost: 4, gesture: "float",
              effects: [ { primitive: "heal", power: 25 } ],
              description: "Closes wounds on a single ally." },
      cura: { name: "Cura", kind: "magic", target: "all_allies", mp_cost: 9, gesture: "float",
              effects: [ { primitive: "heal", power: 18 } ],
              description: "Gentler healing that reaches the whole party." },
      raise: { name: "Raise", kind: "magic", target: "single_ally", mp_cost: 10, gesture: "pop",
               effects: [ { primitive: "revive", fraction: 25 } ],
               description: "Calls a fallen ally back to their feet." },
      silence: { name: "Silence", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "fade",
                 effects: [ { primitive: "status", kind: "silence", chance: 80, duration: 3 } ],
                 description: "Steals a caster's voice." },
      haste: { name: "Haste", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "spin",
               effects: [ { primitive: "status", kind: "haste", chance: 100, duration: 4 } ],
               description: "Quickens an ally's turns." },
      double_cut: { name: "Double Cut", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 60, hits: 2 } ],
                    description: "Two quick strikes in the time of one." },
      war_cry: { name: "War Cry", kind: "skill", target: "self", mp_cost: 2, gesture: "shake",
                 effects: [ { primitive: "buff", stat: "str", amount: 50, duration: 3 } ],
                 description: "A roar that steadies the arm." },
      armor_break: { name: "Armor Break", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 80 },
                               { primitive: "debuff", stat: "def", amount: 50, duration: 3 } ],
                     description: "A blow aimed at the seams of a foe's armor." },
      kick: { name: "Kick", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
              effects: [ { primitive: "physical", type: "fighting", power: 70 } ],
              description: "A sweeping kick that catches every foe." },
      smoke_bomb: { name: "Smoke Bomb", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
                    effects: [ { primitive: "escape" } ],
                    description: "Guarantees an escape, if escape is possible at all." },
      goblin_punch: { name: "Goblin Punch", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                      effects: [ { primitive: "physical", type: "fighting", power: 150 } ],
                      description: "An unreasonably strong punch from an unreasonably small creature." },
      venom_bite: { name: "Venom Bite", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", type: "poison", power: 80 },
                              { primitive: "status", kind: "poison", chance: 60, duration: 3 } ],
                    description: "A bite that keeps hurting." },
      howl: { name: "Howl", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "shake",
              effects: [ { primitive: "buff", stat: "agi", amount: 30, duration: 3 } ],
              description: "The pack moves faster together." },
      steal: { name: "Steal", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
               effects: [ { primitive: "steal", chance: 50 } ],
               description: "Lifts something from a foe's pockets: one of the things it would drop. Faster hands, better odds." },
      libra: { name: "Libra", kind: "magic", target: "single_enemy", mp_cost: 1, gesture: "float",
               effects: [ { primitive: "scan" } ],
               description: "Reads a foe: its HP, what it's weak to, and what it shrugs off. The party remembers." },
      crush: { name: "Crush", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
               effects: [ { primitive: "physical", type: "normal", power: 180 } ],
               description: "The ogre's whole weight behind one blow. It does this every third round: be ready." },
      crystal_breath: { name: "Crystal Breath", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                        effects: [ { primitive: "elemental", type: "fire", power: 22 } ],
                        description: "Fire, focused through the crystal. Everyone burns." },
      esuna: { name: "Esuna", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
               effects: [ { primitive: "cleanse" } ],
               description: "Lifts every affliction from one ally." },
      water_jet: { name: "Water Jet", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "water", power: 14 } ],
                   description: "A hard spray of river water." },
      shadow_strike: { name: "Shadow Strike", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                       effects: [ { primitive: "physical", type: "dark", power: 120 } ],
                       description: "A blow from where the light isn't." },
      # Signature commands: each job's own, always on its menu.
      rally: { name: "Rally", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "buff", stat: "str", amount: 25, duration: 3 } ],
               description: "A shout that lifts everyone's arm a little. The Freelancer's own command." },
      cover: { name: "Cover", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "status", kind: "cover", chance: 100, duration: 2 } ],
               description: "Stand in front of the party until your next turn: the enemy's single blows hit you instead. The Knight's own command." },
      mug: { name: "Mug", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
             effects: [ { primitive: "physical", power: 100 }, { primitive: "steal", chance: 40 } ],
             description: "Hit them and help yourself on the way past. The Thief's own command." },
      focus: { name: "Focus", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "buff", stat: "str", amount: 100, duration: 2 } ],
               description: "One breath: the next blow lands twice as hard. The Monk's own command." },
      channel: { name: "Channel", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
                 effects: [ { primitive: "buff", stat: "mag", amount: 60, duration: 2 } ],
                 description: "Gather the power for the next spell. The Black Mage's own command." },
      pray: { name: "Pray", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "float",
              effects: [ { primitive: "heal", power: 6 } ],
              description: "A little healing for everyone, for free. The White Mage's own command." },
      flame_blade: { name: "Flame Blade", kind: "skill", target: "single_enemy", mp_cost: 3, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "fire", power: 120 } ],
                     description: "A spell run down the length of a sword. The Red Mage's own command." },
      carbuncle: { name: "Carbuncle", kind: "magic", target: "all_allies", mp_cost: 8, gesture: "pop",
                   effects: [ { primitive: "status", kind: "haste", chance: 100, duration: 3 } ],
                   description: "A small green friend who makes everyone quick. The Summoner's own command." },
      gaia: { name: "Gaia", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
              effects: [ { primitive: "elemental", type: "terrain", power: 12 } ],
              description: "The ground itself answers: its type is the land you're fighting on. The Geomancer's own command." },
      jump: { name: "Jump", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
              effects: [ { primitive: "jump", power: 220 } ],
              description: "Leap out of reach for a round, then come down hard. The Dragoon's own command." },
      # Summons: big, typed, and dear.
      ifrit: { name: "Ifrit", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
               effects: [ { primitive: "elemental", type: "fire", power: 20 } ], description: "Hellfire, all of them." },
      shiva: { name: "Shiva", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
               effects: [ { primitive: "elemental", type: "ice", power: 20 } ], description: "Diamond dust, all of them." },
      ramuh: { name: "Ramuh", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
               effects: [ { primitive: "elemental", type: "electric", power: 20 } ], description: "Judgment bolt, all of them." },
      titan: { name: "Titan", kind: "magic", target: "all_enemies", mp_cost: 16, gesture: "shake",
               effects: [ { primitive: "elemental", type: "ground", power: 24 } ], description: "The earth heaves." },
      leviathan: { name: "Leviathan", kind: "magic", target: "all_enemies", mp_cost: 20, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "water", power: 28 } ], description: "A tidal wave where there was no sea." },
      # Geomancy: the land's arts.
      sinkhole: { name: "Sinkhole", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "shake",
                  effects: [ { primitive: "elemental", type: "ground", power: 16 } ], description: "The floor opens under one foe." },
      whirlwind: { name: "Whirlwind", kind: "magic", target: "all_enemies", mp_cost: 6, gesture: "spin",
                   effects: [ { primitive: "elemental", type: "flying", power: 12 } ], description: "The wind takes them all off their feet." },
      riptide: { name: "Riptide", kind: "magic", target: "all_enemies", mp_cost: 8, gesture: "flash",
                 effects: [ { primitive: "elemental", type: "water", power: 14 },
                            { primitive: "status", kind: "slow", chance: 40, duration: 3 } ],
                 description: "Cold water, and the pull of it." },
      # The Dragoon's lance.
      lance: { name: "Lance", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "lunge",
               effects: [ { primitive: "physical", power: 140 } ], description: "A long reach and a hard point." },
      high_jump: { name: "High Jump", kind: "skill", target: "single_enemy", mp_cost: 6, gesture: "lunge",
                   effects: [ { primitive: "jump", power: 320 } ], description: "Higher, longer, harder." },
      dragon_crest: { name: "Dragon Crest", kind: "skill", target: "self", mp_cost: 3, gesture: "shake",
                      effects: [ { primitive: "buff", stat: "def", amount: 50, duration: 3 } ], description: "Scale-hard, for a while." },
      # New jobs' desperation moves.
      crimson_flurry: { name: "Crimson Flurry", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "spin",
                        effects: [ { primitive: "physical", type: "fire", power: 60, hits: 3 } ],
                        description: "Blade and flame, three times over. A Red Mage's desperation move." },
      megaflare: { name: "Megaflare", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "normal", power: 45 } ],
                   description: "Something enormous answers the call. A Summoner's desperation move." },
      cataclysm: { name: "Cataclysm", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "shake",
                   effects: [ { primitive: "elemental", type: "terrain", power: 30 } ],
                   description: "The whole land turns on them. A Geomancer's desperation move." },
      dragon_dive: { name: "Dragon Dive", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "flying", power: 240 } ],
                     description: "Straight down, from very high. A Dragoon's desperation move." },
      # Desperation moves: never learned, found. At a quarter HP or less an
      # attack sometimes becomes the job's move, once a battle.
      last_stand: { name: "Last Stand", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 220 } ],
                    description: "Everything, in one swing. A Freelancer's desperation move." },
      unbroken_line: { name: "Unbroken Line", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                       effects: [ { primitive: "physical", type: "steel", power: 130 } ],
                       description: "The Knight plants their feet and cuts through the whole line. A desperation move." },
      vanishing_cut: { name: "Vanishing Cut", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "fade",
                       effects: [ { primitive: "physical", type: "dark", power: 75, hits: 4 } ],
                       description: "Four cuts from nowhere. A Thief's desperation move." },
      hundred_fists: { name: "Hundred Fists", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "shake",
                       effects: [ { primitive: "physical", type: "fighting", power: 50, hits: 6 } ],
                       description: "Not quite a hundred. A Monk's desperation move." },
      starfall: { name: "Starfall", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                  effects: [ { primitive: "elemental", type: "rock", power: 34 } ],
                  description: "The sky answers, once. A Black Mage's desperation move." },
      judgement: { name: "Judgement", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "fire", power: 26 },
                             { primitive: "status", kind: "blind", chance: 50, duration: 3 } ],
                   description: "Holy fire, too bright to look at. A White Mage's desperation move." }
    }.freeze

    ITEMS = {
      potion: { name: "Potion", category: "consumable", price: 40, target: "single_ally",
                effects: [ { primitive: "heal", power: 30 } ], description: "Restores a little HP." },
      phoenix_down: { name: "Phoenix Down", category: "consumable", price: 300, target: "single_ally",
                      effects: [ { primitive: "revive", fraction: 20 } ], description: "A feather that remembers being alive." },
      hi_potion: { name: "Hi-Potion", category: "consumable", price: 150, target: "single_ally",
                   effects: [ { primitive: "heal", power: 80 } ], description: "Restores a good deal of HP." },
      smoke_pellet: { name: "Smoke Pellet", category: "consumable", price: 80, target: "self",
                      effects: [ { primitive: "escape" } ], description: "For when the plan was bad." },
      antidote: { name: "Antidote", category: "consumable", price: 50, target: "single_ally",
                  effects: [ { primitive: "cleanse", kind: "poison" } ], description: "Bitter, and it works." },
      eye_drops: { name: "Eye Drops", category: "consumable", price: 50, target: "single_ally",
                   effects: [ { primitive: "cleanse", kind: "blind" } ], description: "Clears the eyes of darkness." },
      echo_screen: { name: "Echo Screen", category: "consumable", price: 50, target: "single_ally",
                     effects: [ { primitive: "cleanse", kind: "silence" } ], description: "Gives a silenced throat back its voice." },
      remedy: { name: "Remedy", category: "consumable", price: 250, target: "single_ally",
                effects: [ { primitive: "cleanse" } ], description: "Cures everything that ails you, except being down." },
      broadsword: { name: "Broadsword", category: "sword", price: 200, stats: { atk: 14 },
                    description: "A plain, honest blade." },
      dagger: { name: "Dagger", category: "knife", price: 120, stats: { atk: 9, agi: 2 },
                description: "Light enough to strike first." },
      rod: { name: "Rod", category: "rod", price: 150, stats: { atk: 4, mag: 4 },
             description: "Wood, wire and a borrowed spark." },
      staff: { name: "Staff", category: "staff", price: 150, stats: { atk: 5, spr: 4 },
               description: "A walking stick that listens." },
      buckler: { name: "Buckler", category: "shield", price: 100, stats: { def: 3, mdef: 1 },
                 description: "Small, round, often dented." },
      iron_spear: { name: "Iron Spear", category: "spear", price: 220, stats: { atk: 15 },
                    description: "Reach is its own kind of armour." },
      hand_axe: { name: "Hand Axe", category: "axe", price: 180, stats: { atk: 13 },
                  description: "For wood, mostly." },
      iron_helm: { name: "Iron Helm", category: "helmet", price: 150, stats: { def: 3 },
                   description: "Rings when hit. Better than the alternative." },
      leather_cap: { name: "Leather Cap", category: "hat", price: 60, stats: { def: 1, mdef: 1 },
                     description: "Keeps the rain off." },
      bronze_armor: { name: "Bronze Armor", category: "heavy_armor", price: 400, stats: { def: 8, agi: -2 },
                      description: "Heavy, loud and reassuring." },
      cotton_robe: { name: "Cotton Robe", category: "robe", price: 120, stats: { def: 2, mdef: 4 },
                     description: "Embroidered with small protective sigils." },
      power_ring: { name: "Power Ring", category: "accessory", price: 1000, stats: { str: 5 },
                    description: "A ring cut from a single garnet." }
    }.freeze

    JOBS = {
      freelancer: { name: "Freelancer", base_type: "normal", signature: "rally", desperation: "last_stand", description: "No talents, no limits. Every hero starts here.",
                    stat_multipliers: {}, ability_slots: 2, equip_categories: Item::EQUIPMENT_CATEGORIES,
                    innates: [], levels: [ [ "libra", 5 ] ] },
      knight: { name: "Knight", base_type: "steel", signature: "cover", passive: "second_wind", desperation: "unbroken_line", description: "Heavy armor, a long sword and the resolve to stand in front.",
                stat_multipliers: { max_hp: 130, str: 120, vit: 120, agi: 90, mag: 60 },
                equip_categories: %w[sword axe spear shield helmet heavy_armor accessory],
                innates: [ { stat: "def", percent: 10 } ],
                levels: [ [ "war_cry", 1 ], [ "armor_break", 12 ], [ "double_cut", 30 ] ] },
      thief: { name: "Thief", base_type: "dark", signature: "mug", passive: "first_strike", desperation: "vanishing_cut", description: "Fast hands, faster feet.",
               stat_multipliers: { agi: 140, str: 90, max_hp: 90 },
               equip_categories: %w[knife hat light_armor accessory],
               innates: [ { stat: "agi", add: 5 } ],
               levels: [ [ "steal", 1 ], [ "smoke_bomb", 12 ], [ "double_cut", 25 ] ] },
      monk: { name: "Monk", base_type: "fighting", signature: "focus", passive: "counter", desperation: "hundred_fists", description: "Fists instead of steel.",
              stat_multipliers: { max_hp: 140, str: 130, vit: 110, mag: 50 },
              equip_categories: %w[light_armor accessory],
              innates: [ { stat: "atk", add: 12 } ],
              levels: [ [ "kick", 1 ], [ "war_cry", 15 ] ] },
      black_mage: { name: "Black Mage", base_type: "fire", signature: "channel", passive: "mp_regen", desperation: "starfall", description: "Destruction, studied carefully.",
                    stat_multipliers: { max_hp: 70, max_mp: 150, mag: 140, str: 60 },
                    equip_categories: %w[knife rod robe hat accessory],
                    innates: [],
                    levels: [ [ "fire", 1 ], [ "blizzard", 5 ], [ "thunder", 8 ], [ "sleep", 15 ], [ "fira", 30 ], [ "bio", 45 ], [ "drain", 60 ] ] },
      white_mage: { name: "White Mage", base_type: "psychic", signature: "pray", passive: "regen", desperation: "judgement", description: "Keeps everyone else alive.",
                    stat_multipliers: { max_hp: 80, max_mp: 140, mag: 120, spr: 130, str: 60 },
                    equip_categories: %w[staff robe hat accessory],
                    innates: [ { stat: "mdef", percent: 20 } ],
                    levels: [ [ "cure", 1 ], [ "silence", 10 ], [ "esuna", 20 ], [ "cura", 30 ], [ "haste", 40 ], [ "raise", 60 ] ] },
      red_mage: { name: "Red Mage", base_type: "normal", signature: "flame_blade", passive: "regen", desperation: "crimson_flurry",
                  description: "A little of everything, and a sword to put it through.",
                  stat_multipliers: { max_hp: 95, max_mp: 115, str: 105, mag: 110 },
                  equip_categories: %w[sword knife rod light_armor robe hat accessory],
                  innates: [],
                  levels: [ [ "fire", 1 ], [ "cure", 1 ], [ "blizzard", 8 ], [ "thunder", 8 ], [ "sleep", 20 ], [ "haste", 40 ] ] },
      summoner: { name: "Summoner", base_type: "ghost", signature: "carbuncle", passive: "mp_regen", desperation: "megaflare",
                  description: "Calls things that should not come when called.",
                  stat_multipliers: { max_hp: 75, max_mp: 160, mag: 135, str: 55 },
                  equip_categories: %w[staff rod robe hat accessory],
                  innates: [],
                  levels: [ [ "ifrit", 1 ], [ "shiva", 5 ], [ "ramuh", 8 ], [ "titan", 30 ], [ "leviathan", 60 ] ] },
      geomancer: { name: "Geomancer", base_type: "ground", signature: "gaia", passive: "regen", desperation: "cataclysm",
                   description: "Reads the land and borrows its temper.",
                   stat_multipliers: { max_hp: 100, mag: 115, spr: 115, str: 90 },
                   equip_categories: %w[staff axe light_armor hat accessory],
                   innates: [ { stat: "mdef", percent: 10 } ],
                   levels: [ [ "sinkhole", 1 ], [ "whirlwind", 15 ], [ "riptide", 30 ] ] },
      dragoon: { name: "Dragoon", base_type: "flying", signature: "jump", passive: "first_strike", desperation: "dragon_dive",
                 description: "Fights from above. Mostly from above.",
                 stat_multipliers: { max_hp: 120, str: 125, agi: 105, mag: 50 },
                 equip_categories: %w[spear shield helmet heavy_armor accessory],
                 innates: [ { stat: "atk", add: 4 } ],
                 levels: [ [ "lance", 1 ], [ "dragon_crest", 15 ], [ "high_jump", 35 ] ] }
    }.freeze

    MONSTERS = {
      goblin: { name: "Goblin", level: 1, stats: stats(max_hp: 45, str: 9, atk: 8, agi: 8, def: 3, mdef: 2),
                base_type: "normal", affinities: { fire: "weak" }, exp: 20, gil: 30, abp: 2,
                ai_script: [ { if: { chance: 25 }, use: "goblin_punch" }, { use: "attack" } ],
                drops: [ { item: "potion", chance: 30 } ],
                description: "Small, green and far braver in groups." },
      wolf: { name: "Wolf", level: 2, stats: stats(max_hp: 60, str: 11, atk: 10, agi: 16, def: 3, mdef: 3),
              exp: 30, gil: 20, abp: 2,
              ai_script: [ { if: { round_multiple: 3 }, use: "howl" }, { if: { chance: 30 }, use: "venom_bite" }, { use: "attack" } ],
              drops: [ { item: "potion", chance: 25 } ],
              description: "Hunts in packs along the old roads." },
      killer_bee: { name: "Killer Bee", level: 2, stats: stats(max_hp: 35, str: 8, atk: 9, agi: 22, def: 1, mdef: 2),
                    base_type: "bug", exp: 24, gil: 15, abp: 2,
                    ai_script: [ { if: { chance: 40 }, use: "venom_bite", target: "lowest_hp" }, { use: "attack" } ],
                    description: "The buzzing arrives before the bee does." },
      zombie: { name: "Zombie", level: 3, stats: stats(max_hp: 110, str: 12, atk: 12, agi: 4, def: 4, mdef: 1),
                base_type: "dark", affinities: { fire: "weak" }, status_immune: %w[poison sleep],
                exp: 48, gil: 50, abp: 3,
                ai_script: [ { use: "attack", target: "lowest_hp" } ],
                description: "Slow, relentless and already dead." },
      skeleton: { name: "Skeleton", level: 3, stats: stats(max_hp: 85, str: 13, atk: 12, agi: 9, def: 5, mdef: 3),
                  base_type: "dark", status_immune: %w[poison sleep], exp: 40, gil: 35, abp: 3,
                  ai_script: [ { if: { chance: 35 }, use: "shadow_strike" }, { use: "attack" } ],
                  drops: [ { item: "phoenix_down", chance: 10 } ],
                  description: "Bones that remember how to hold a sword." },
      nymph: { name: "Nymph", level: 3, stats: stats(max_hp: 75, max_mp: 30, mag: 15, str: 7, atk: 5, agi: 14, def: 3, mdef: 8),
               base_type: "water", exp: 38, gil: 45, abp: 3,
               ai_script: [ { if: { self_hp_below: 40 }, use: "cure", target: "self" }, { if: { chance: 60 }, use: "water_jet" }, { use: "attack" } ],
               drops: [ { item: "hi_potion", chance: 15 } ],
               description: "Lives in the forest pools. Doesn't like to be looked at." },
      flan: { name: "Flan", level: 3,
              stats: stats(max_hp: 70, max_mp: 20, mag: 14, atk: 6, agi: 6, def: 60, mdef: 0),
              base_type: "water", exp: 42, gil: 40, abp: 3,
              ai_script: [ { if: { chance: 50 }, use: "blizzard" }, { use: "attack" } ],
              description: "Blades bounce off. Bring a mage." },
      sand_worm: { name: "Sand Worm", level: 4, stats: stats(max_hp: 180, str: 15, atk: 14, agi: 6, def: 6, mdef: 4),
                   base_type: "ground", affinities: { ground: "absorb" }, exp: 70, gil: 75, abp: 4,
                   ai_script: [ { if: { chance: 35 }, use: "venom_bite" }, { use: "attack", target: "highest_hp" } ],
                   drops: [ { item: "phoenix_down", chance: 10 } ],
                   description: "Rises from the dunes when something walks over it." },
      goblin_chief: { boss: true, boss_line: "Mine. The cave, the shinies, the hat. All mine.", name: "Goblin Chief", level: 4,
                      stats: stats(max_hp: 140, max_mp: 12, str: 14, atk: 13, agi: 10, def: 5, mdef: 3, mag: 10),
                      base_type: "fighting", affinities: { fire: "weak" }, exp: 85, gil: 150, abp: 4,
                      ai_script: [ { if: { self_hp_below: 30 }, use: "cure", target: "self" },
                                  { if: { chance: 40 }, use: "goblin_punch" }, { use: "attack" } ],
                      drops: [ { item: "broadsword", chance: 15 } ],
                      variant: { hue: 40, scale: 125 },
                      description: "A goblin in a slightly bigger hat. Palette-swapped from the Goblin." },
      dark_mage: { boss: true, boss_line: "The crystals were never meant for your kind. Kneel, and I'll make it quick.", name: "Dark Mage", level: 5,
                   stats: stats(max_hp: 120, max_mp: 60, str: 6, mag: 20, spr: 16, atk: 4, agi: 12, def: 3, mdef: 12),
                   base_type: "dark", affinities: { dark: "absorb" }, exp: 100, gil: 200, abp: 4,
                   ai_script: [ { if: { ally_hp_below: 40 }, use: "drain" }, { if: { chance: 30 }, use: "sleep" },
                               { if: { chance: 60 }, use: "fire" }, { use: "bio" } ],
                   drops: [ { item: "rod", chance: 20 } ],
                   description: "Studied at the same academy as the party's black mage. Graduated differently." },
      ogre: { boss: true, boss_line: "You came for the crystal. So did the last ones. They're under the pass.", name: "Ogre", level: 6,
              stats: stats(max_hp: 340, max_mp: 30, str: 24, mag: 8, atk: 22, agi: 7, def: 12, mdef: 6),
              base_type: "normal", affinities: { ice: "absorb", fire: "resist" }, status_immune: %w[sleep], exp: 280, gil: 400, abp: 8,
              ai_script: [ { if: { self_hp_below: 30 }, use: "cure", target: "self" },
                          { if: { round_multiple: 3 }, use: "crush", target: "lowest_hp" },
                          { if: { round_multiple: 4 }, use: "war_cry" }, { use: "attack", target: "lowest_hp" } ],
              drops: [ { item: "bronze_armor", chance: 50 }, { item: "power_ring", chance: 5 } ],
              description: "Guards the pass. A boss for a party of four at job level 2 or so." },
      crystal_wyrm: { boss: true, boss_line: "I have slept on this fire for a thousand years. You will not take it from me.", name: "Crystal Wyrm", level: 10,
                      stats: stats(max_hp: 1200, max_mp: 200, str: 26, mag: 24, spr: 20, atk: 24, agi: 14, def: 16, mdef: 16),
                      base_type: "rock", affinities: { electric: "weak" },
                      status_immune: %w[sleep paralyze silence poison], exp: 1400, gil: 2500, abp: 16,
                      ai_script: [ { if: { self_hp_below: 25, chance: 50 }, use: "cura" },
                                  { if: { round_multiple: 4 }, use: "crystal_breath" }, { if: { chance: 30 }, use: "thunder" },
                                  { use: "attack" } ],
                      drops: [ { item: "power_ring", chance: 100 } ],
                      description: "Grew around a shard of the fire crystal. The first real boss." }
    }.freeze

    ENCOUNTER_TABLES = {
      grasslands: { name: "Grasslands", terrain: "plains", tier: 1,
                    description: "Open country between the first towns.",
                    entries: [ { weight: 4, monsters: { goblin: 3 } }, { weight: 2, monsters: { wolf: 2 } },
                               { weight: 1, monsters: { goblin: 2, wolf: 1 } } ] },
      old_forest: { name: "Old Forest", terrain: "forest", tier: 1,
                    entries: [ { weight: 3, monsters: { killer_bee: 3 } }, { weight: 2, monsters: { wolf: 3 } },
                               { weight: 2, monsters: { nymph: 2 } }, { weight: 1, monsters: { goblin_chief: 1, goblin: 2 } } ] },
      dunes: { name: "Dunes", terrain: "desert", tier: 2,
               entries: [ { weight: 3, monsters: { sand_worm: 1 } }, { weight: 2, monsters: { killer_bee: 4 } } ] },
      barrow: { name: "Barrow", terrain: "crypt", tier: 2,
                description: "Old graves that don't stay shut.",
                entries: [ { weight: 3, monsters: { zombie: 2 } }, { weight: 3, monsters: { skeleton: 3 } },
                           { weight: 2, monsters: { zombie: 1, dark_mage: 1 } },
                           { weight: 1, monsters: { flan: 2 } } ] },
      goblin_cave: { name: "Goblin Cave", terrain: "cave", tier: 1,
                     description: "Goblins, their pets, and whatever they've let in.",
                     entries: [ { weight: 4, monsters: { goblin: 3 } }, { weight: 2, monsters: { goblin: 2 } },
                                { weight: 2, monsters: { goblin: 2, killer_bee: 1 } }, { weight: 1, monsters: { goblin: 4 } },
                                { weight: 1, monsters: { goblin_chief: 1, goblin: 1 } } ] },
      mountain_pass: { name: "Mountain Pass", terrain: "mountain", tier: 3,
                       entries: [ { weight: 1, monsters: { ogre: 1 } }, { weight: 3, monsters: { wolf: 3 } } ] }
    }.freeze

    def texts(*strings, **fields)
      strings.map { |text| { text: text }.merge(fields) }
    end

    GENERATOR_TABLES = {
      town_names: { name: "Town names", kind: "town_names",
                    entries: texts("Tule", "Carwen", "Walse", "Karnak", "Istory", "Jachol", "Lix", "Mirage",
                                   "Surgate", "Kelb", "Regole", "Quelb", "Mua", "Moore", "Crescent", "Bal",
                                   "Ferrow", "Amberlee", "Hollin", "Saltmarsh", "Greyford", "Cinderwick", "Oakhollow", "Thistlebrook") },
      dungeon_names: { name: "Dungeon names", kind: "dungeon_names",
                       entries: texts("The Sunken Crypt", "Hollow Barrow", "The Old Graves", "Kingsrest", "The Weeping Vault",
                                      "Ashen Catacombs", "The Silent Mound", "Pale Hill", "The Lantern Tombs", "Mourners' Deep") },
      cave_names: { name: "Cave names", kind: "dungeon_names",
                    entries: texts("Goblin Hole", "The Dripping Caves", "Rattail Warren", "Mossback Cave", "The Crooked Den",
                                   "Snaggletooth Grotto", "Mudwater Tunnels", "The Chittering Dark", "Bramble Cave", "Old Quarry") },
      given_names: { name: "Given names", kind: "names",
                     entries: texts("Mira", "Oskar", "Lenne", "Dorn", "Pell", "Hask", "Ivy", "Brand", "Sella", "Tobin", "Wren", "Garrick",
                                    "Nessa", "Rook", "Alma", "Bex", "Corin", "Dalia", "Edda", "Fenn", "Gile", "Hollis", "Ines", "Jory",
                                    "Kessa", "Lorn", "Maddock", "Nim", "Orla", "Piet", "Quill", "Rhosyn", "Saul", "Tamsin", "Ulric", "Vesna",
                                    "Wim", "Yara", "Zeb", "Anselm", "Brin", "Calla", "Doro", "Emrys", "Faye", "Gideon", "Hanne", "Ilse",
                                    "Jonah", "Kit", "Liesl", "Marek", "Noor", "Otto", "Pim", "Runa", "Sten", "Tilde", "Varro", "Wenna") },
      town_hooks: { name: "Townsfolk hooks", kind: "hooks",
                    entries: texts("Owes the guild more than they'll say.", "Saw green lights on the hill three nights running.",
                                   "Lost a brother to the mountain pass.", "Sells maps that are mostly right.",
                                   "Wants an escort north and can't pay yet.", "Is hiding a runaway in the cellar.",
                                   "Swears the wind stopped last week, then started again.", "Collects crystal shards. Asks about them.",
                                   "Knows the old way into the shrine.", "Wants their stolen ring back, no questions asked.",
                                   "Was a soldier once. Won't say for which side.", "Keeps a chocobo that bites everyone but them.",
                                   "Has a letter for someone who never came back.", "Is certain the mayor is a monster in disguise.",
                                   "Pays well for goblin ears, and doesn't say why.", "Dreams of the sea, though they've never seen it.",
                                   "Heard singing from the old well.", "Is saving for a sword they'll never be able to lift.",
                                   "Their crops died overnight in a perfect circle.", "Needs medicine from the next town before the week is out.",
                                   "Was robbed on the road by someone polite.", "Knows a song about the heroes that isn't flattering.",
                                   "Runs a card game with a marked deck.", "Is looking for a missing apprentice.",
                                   "Found a key they can't find a lock for.", "Remembers when the crystal still sang.",
                                   "Carves charms against the dark. Some of them work.", "Wants the party to take a message to their mother.",
                                   "Is writing a book about monsters. Needs a closer look.", "Heard the temple bells ring with no one pulling.",
                                   "Sold something to the wrong person and regrets it.", "Hasn't slept since the lights went out on the hill.",
                                   "Will trade anything for news from the capital.", "Keeps staring at one of the party as if they know them.",
                                   "Buried something by the old mill and forgot which tree.", "Thinks the river is running backwards. It is.") },
      service_names: { name: "Service names", kind: "service_names",
                       entries: texts("The Sleepy Chocobo", "The Crossed Keys", "Last Light Inn", "The Wandering Moogle", "The Hearth & Kettle",
                                      "The Tipsy Wyvern", service: "inn") +
                                texts("Odds & Ends", "The Tinker's Cart", "Crystal Supply", "Hammer & Tongs", "The Traveller's Pack",
                                      service: "shop") +
                                texts("Adventurers' Hall", "The Compass Guild", "The Lantern Society", service: "guild") +
                                texts("Chapel of Light", "Shrine of the Four Winds", "Temple of the Quiet Flame", service: "temple") },
      buildings: { name: "Building archetypes", kind: "buildings",
                   entries: [ { text: "Inn", service: "inn", width: 90, height: 90, roof: "peak" },
                              { text: "Shop", service: "shop", width: 70, height: 70, roof: "peak" },
                              { text: "Guild", service: "guild", width: 80, height: 105, roof: "flat" },
                              { text: "Temple", service: "temple", width: 70, height: 135, roof: "dome" },
                              { text: "House", width: 50, height: 60, weight: 4 },
                              { text: "Cottage", width: 45, height: 50, roof: "peak", weight: 2 },
                              { text: "Tower", width: 36, height: 125 },
                              { text: "Warehouse", width: 95, height: 55, roof: "flat" },
                              { text: "Windmill", width: 40, height: 100, roof: "peak" } ] },
      shop_stock: { name: "General store stock", kind: "stock",
                    entries: %w[potion hi_potion phoenix_down smoke_pellet antidote eye_drops echo_screen remedy
                                broadsword dagger iron_spear hand_axe rod staff buckler leather_cap iron_helm cotton_robe]
                               .map { |item| { item: item } } },
      village_stock: { name: "Village store stock", kind: "stock",
                       entries: [ { item: "potion", weight: 3 }, { item: "antidote", weight: 2 }, { item: "eye_drops" }, { item: "echo_screen" },
                                  { item: "smoke_pellet" }, { item: "dagger" }, { item: "rod" }, { item: "leather_cap" },
                                  { item: "cotton_robe" }, { item: "buckler" } ] },
      rooms: { name: "Room names", kind: "rooms",
               entries: texts("Flooded Hall", "Ossuary", "Collapsed Stair", "Crystal Chamber", "Guardroom", "Cistern",
                              "Vault", "Crossing", "Chapel", "Kennels", "Forge", "Gallery", "Well Room", "Barracks",
                              "Fungus Grotto", "Root Cellar", "Bone Pit", "Echoing Hall", "Mushroom Garden", "Larder",
                              "Shrine Room", "Broken Bridge", "Sunken Library", "Throne Room") },
      room_events: { name: "Room events", kind: "room_events",
                     entries: texts("A voice asks each of you for your name, and repeats it back wrong.",
                                    "The floor tilts. Something rolls toward the dark end of the room.",
                                    "Old bones, arranged in a careful circle. One is missing.",
                                    "A mural shows four heroes. Their faces have been scratched out.",
                                    "Wind howls through a crack in the wall, though you're far underground.",
                                    "A goblin, too scared to fight, offers to trade a secret for its life.",
                                    "A lantern still burns here. Someone lit it today.",
                                    "Fresh footprints lead in and don't lead out.",
                                    "A chest sits open and empty. The dust inside it is disturbed.",
                                    "The walls are covered in tally marks. Hundreds of them.",
                                    "A statue's eyes follow whoever holds a light.",
                                    "Water drips upward from a puddle into the ceiling.",
                                    "A skeleton in old armor clutches a note: \"Don't trust the map.\"",
                                    "Somewhere ahead, someone is humming the song from the inn.",
                                    "A sleeping monster, enormous, blocks half the room. It doesn't wake. Yet.",
                                    "The room is warm, and smells of bread.",
                                    "Carved above the door: a warning, in a language one of you almost reads.",
                                    "A mirror shows the room with one more person in it.",
                                    "The crystal dust on the floor glows where you step.",
                                    "An old campsite. The bedrolls are still warm.") },
      forks: { name: "Fork costs", kind: "forks",
               entries: texts("A rope bridge: someone must stay behind to hold it.",
                              "Poison gas: everyone who goes this way loses a tenth of their HP.",
                              "A sealed door that opens only for 100 gil in the slot.",
                              "A narrow crawlway: no heavy armor fits through.",
                              "Rising water: the way back will be flooded behind you.",
                              "A toll-troll: it wants an item, any item, and it wants the best one.",
                              "Loose rock: the noise will wake whatever sleeps below.",
                              "A dark stair: no light will burn on it.",
                              "A warded arch: anyone who casts a spell here loses their MP.",
                              "Thorns: whoever leads takes a wound that won't heal until you rest.",
                              "A long climb: the party arrives too tired to run from the next fight.",
                              "A silent hall: speak, and it answers with something worse.") },
      locks: { name: "Locks and keys", kind: "locks",
               entries: [ { text: "Crystal portal", key: "Blue crystal" }, { text: "Bone altar", key: "Goat's skull" },
                          { text: "Iron door", key: "Rusty key" }, { text: "Sealed coffin", key: "Grave-warden's ring" },
                          { text: "Rune wall", key: "Moon rune" }, { text: "Drawbridge winch", key: "Crank handle" },
                          { text: "Goblin gate", key: "Chief's tooth" }, { text: "Weeping statue", key: "Silver tear" },
                          { text: "Bell-rope portcullis", key: "Brass bell" }, { text: "Flooded sluice", key: "Valve wheel" } ] },
      treasure: { name: "Dungeon treasure", kind: "treasure",
                  entries: [ { item: "potion", weight: 4 }, { item: "hi_potion", weight: 2 }, { item: "phoenix_down", weight: 2 },
                             { item: "antidote", weight: 2 }, { item: "remedy" }, { item: "power_ring" }, { item: "bronze_armor" },
                             { gil: 50, weight: 3 }, { gil: 120, weight: 2 }, { gil: 300 } ] }
    }.freeze

    LOCATION_TEMPLATES = {
      village: { name: "Village", kind: "town", description: "A small town on the road: an inn, a shop, a handful of worried people.",
                 config: { services: { inn: 100, shop: 90, guild: 20, temple: 40 }, npcs: [ 3, 5 ], stock: [ 4, 6 ], buildings: [ 8, 11 ],
                           tables: %w[town_names given_names town_hooks service_names buildings village_stock] } },
      port_town: { name: "Port town", kind: "town", description: "Busy, crowded, full of rumours from the sea.",
                   config: { services: { inn: 100, shop: 100, guild: 80, temple: 60 }, npcs: [ 5, 8 ], stock: [ 6, 9 ], buildings: [ 12, 16 ],
                             tables: %w[town_names given_names town_hooks service_names buildings shop_stock] } },
      goblin_cave: { name: "Goblin cave", kind: "dungeon", encounter_table: "goblin_cave",
                     description: "A short, twisting cave. A good first dungeon.",
                     config: { rooms: [ 5, 7 ], loops: 1, locks: 1, decisions: { encounter: 4, event: 2, treasure: 2, fork: 1 }, boss: { goblin_chief: 1 },
                               tables: %w[cave_names rooms room_events forks treasure locks] } },
      barrow: { name: "Barrow", kind: "dungeon", encounter_table: "barrow",
                description: "Old graves dug deep into the hill, and something that won't stay buried.",
                config: { rooms: [ 8, 11 ], loops: 2, locks: 2, decisions: { encounter: 5, event: 3, treasure: 2, fork: 2 }, boss: { dark_mage: 1, zombie: 2 },
                          tables: %w[dungeon_names rooms room_events forks treasure locks] } }
    }.freeze
  end
end
