# frozen_string_literal: true

# The Grimoire: abilities, the creatures' moves and each job's lessons. (Seeds::BaseWorld)
module Seeds
  module BaseWorld
    ABILITIES = {
      fire: { name: "Fire", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
              effects: [ { primitive: "elemental", type: "fire", power: 12 } ],
              description: "A burst of flame. The first spell every black mage learns and the last one they forget." },
      blizzard: { name: "Blizzard", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
                  effects: [ { primitive: "elemental", type: "ice", power: 12 } ],
                  description: "Shards of ice that sting worse than they look." },
      thunder: { name: "Thunder", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
                 effects: [ { primitive: "elemental", type: "electric", power: 12 } ],
                 description: "A single crack of lightning." },
      fira: { name: "Fira", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
              effects: [ { primitive: "elemental", type: "fire", power: 10 } ],
              description: "Fire spread across the whole enemy line." },
      sleep: { name: "Sleep", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "float",
               effects: [ { primitive: "status", kind: "sleep", chance: 70, duration: 3 } ],
               description: "Lulls a foe to sleep. A hard blow wakes them." },
      bio: { name: "Bio", kind: "magic", target: "single_enemy", mp_cost: 6, gesture: "tint",
             effects: [ { primitive: "elemental", type: "poison", power: 12 },
                       { primitive: "status", kind: "poison", chance: 100, duration: 4 } ],
             description: "Corrosive shadow that lingers as poison." },
      drain: { name: "Drain", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "tint",
               effects: [ { primitive: "drain", power: 14 } ],
               description: "Steals life from a foe and gives it to the caster." },
      cure: { name: "Cure", kind: "magic", target: "single_ally", mp_cost: 4, gesture: "float",
              effects: [ { primitive: "heal", power: 25 } ],
              description: "Closes wounds on a single ally." },
      cura: { name: "Cura", kind: "magic", target: "all_allies", mp_cost: 9, gesture: "float",
              effects: [ { primitive: "heal", power: 18 } ],
              description: "Gentler healing that reaches the whole party." },
      raise: { name: "Raise", kind: "magic", target: "single_ally", mp_cost: 10, gesture: "pop",
               effects: [ { primitive: "revive", fraction: 25 } ],
               description: "Calls a fallen ally back to their feet." },
      silence: { name: "Silence", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "fade",
                 effects: [ { primitive: "status", kind: "silence", chance: 80, duration: 3 } ],
                 description: "Steals a caster's voice." },
      haste: { name: "Haste", kind: "magic", target: "single_ally", mp_cost: 8, gesture: "spin",
               effects: [ { primitive: "status", kind: "haste", chance: 100, duration: 3 } ],
               description: "Quickens an ally: a second go at the end of each round, the same move again, for a few rounds." },
      double_cut: { name: "Double Cut", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 60, hits: 2 } ],
                    description: "Two quick strikes in the time of one." },
      war_cry: { name: "War Cry", kind: "skill", target: "self", mp_cost: 2, gesture: "shake",
                 effects: [ { primitive: "buff", stat: "str", amount: 50, duration: 3 }, { primitive: "buff", stat: "atk", amount: 50, duration: 3 } ],
                 description: "A roar that steadies the arm." },
      armor_break: { name: "Armor Break", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 80 },
                               { primitive: "debuff", stat: "def", amount: 50, duration: 3 } ],
                     description: "A blow aimed at the seams of a foe's armor." },
      kick: { name: "Kick", kind: "skill", target: "all_enemies", mp_cost: 3, gesture: "spin",
              effects: [ { primitive: "physical", power: 45 } ],
              description: "A sweeping kick that catches every foe, if none of them hard." },
      smoke_bomb: { name: "Smoke Bomb", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
                    effects: [ { primitive: "escape" } ],
                    description: "Guarantees an escape, if escape is possible at all." },
      goblin_punch: { name: "Goblin Punch", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                      effects: [ { primitive: "physical", power: 150 } ],
                      description: "An unreasonably strong punch from an unreasonably small creature." },
      venom_bite: { name: "Venom Bite", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", type: "poison", power: 80 },
                              { primitive: "status", kind: "poison", chance: 60, duration: 3 } ],
                    description: "A bite that keeps hurting." },
      howl: { name: "Howl", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "shake",
              effects: [ { primitive: "buff", stat: "agi", amount: 30, duration: 3 } ],
              description: "The pack moves faster together." },
      steal: { name: "Steal", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
               effects: [ { primitive: "steal", chance: 50 } ],
               description: "Lifts something from a foe's pockets: one of the things it would drop. Faster hands, better odds." },
      libra: { name: "Libra", kind: "magic", target: "single_enemy", mp_cost: 1, gesture: "float",
               effects: [ { primitive: "scan" } ],
               description: "Reads a foe: its HP, what it's weak to, and what it shrugs off. The party remembers." },
      crush: { name: "Crush", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
               effects: [ { primitive: "physical", type: "normal", power: 180 } ],
               description: "The ogre's whole weight behind one blow. It does this every third round: be ready." },
      crystal_breath: { name: "Crystal Breath", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash", charge: 1,
                        effects: [ { primitive: "elemental", type: "rock", power: 22 } ],
                        description: "A storm of crystal shards across the whole party, a turn in the gathering: the wyrm says so first. Armour helps; flame and feathers don't." },
      shard_storm: { name: "Shard Storm", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash", charge: 1,
                     effects: [ { primitive: "elemental", type: "rock", power: 34, hits: 1 }, { primitive: "status", kind: "slow", chance: 40 } ],
                     description: "The Unbound wyrm's breath: harder, and it slows what it doesn't cut. A turn in the gathering." },
      esuna: { name: "Esuna", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
               effects: [ { primitive: "cleanse" } ],
               description: "Lifts every affliction from one ally." },
      water_jet: { name: "Water Jet", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "water", power: 14 } ],
                   description: "A hard spray of river water." },
      shadow_strike: { name: "Shadow Strike", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                       effects: [ { primitive: "physical", type: "dark", power: 120 } ],
                       description: "A blow from where the light isn't." },
      # Signature commands: each job's own, always on its menu.
      rally: { name: "Rally", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "buff", stat: "str", amount: 25, duration: 3 }, { primitive: "buff", stat: "atk", amount: 25, duration: 3 } ],
               description: "A shout that lifts everyone's arm a little. The Freelancer's own command." },
      cover: { name: "Cover", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "status", kind: "aggro", chance: 100, duration: 2 } ],
               description: "Stand in front of the party until your next turn: the enemy's single blows hit you instead. The Knight's own command." },
      mug: { name: "Mug", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
             effects: [ { primitive: "physical", power: 60 }, { primitive: "steal", chance: 40 } ],
             description: "Hit them and help yourself on the way past. The Thief's own command." },
      focus: { name: "Focus", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "status", kind: "charged", chance: 100, duration: 3 } ],
               description: "One breath: the next blow lands twice as hard. The Monk's own command." },
      hide: { name: "Hide", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
              effects: [ { primitive: "away", who: "self", duration: 1 } ],
              description: "Gone from sight until your next turn: nothing can reach you, then you're back to act." },
      barrier: { name: "Barrier", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
                 effects: [ { primitive: "shield", power: 8, duration: 4 } ],
                 description: "A skin of light that takes the next blows before they reach you." },
      stop: { name: "Stop", kind: "magic", target: "single_enemy", mp_cost: 7, gesture: "tint",
              effects: [ { primitive: "status", kind: "stop", chance: 60, duration: 2 } ],
              description: "Holds a foe still in time. Hitting it doesn't break the spell." },
      enfire: { name: "Enfire", kind: "magic", target: "self", mp_cost: 4, gesture: "flash",
                effects: [ { primitive: "imbue", type: "fire", duration: 3 } ],
                description: "Sets your blade alight: your Attack strikes as fire for a while." },
      osmose: { name: "Osmose", kind: "magic", target: "single_enemy", mp_cost: 0, gesture: "tint",
                effects: [ { primitive: "sap", power: 16, keep: 100 } ],
                description: "Draws a foe's magic into your own." },
      gravity: { name: "Gravity", kind: "magic", target: "single_enemy", mp_cost: 9, gesture: "shake",
                 effects: [ { primitive: "percent", power: 25, chance: 80 } ],
                 description: "A quarter of whatever it has left, whatever its armour. It never finishes anyone, and bosses barely notice." },
      inner_fury: { name: "Inner Fury", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
                    effects: [ { primitive: "status", kind: "berserk", chance: 100, duration: 3 } ],
                    description: "Stop thinking and hit things, harder. You attack on your own until it passes." },
      shield_bash: { name: "Shield Bash", kind: "skill", target: "single_enemy", mp_cost: 3, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 60 }, { primitive: "away", who: "target", duration: 1, chance: 60 } ],
                     description: "A shove that sends a foe reeling off the field for a turn." },
      # Field abilities: a job's move outside battle (FieldUse), once per rest.
      forage: { name: "Forage", kind: "field", field_skill: "survival", field_outcome: "find", field_difficulty: "easy", field_power: 100,
                effects: [], description: "Roots, herbs, a traveller's lost pack: something useful turns up." },
      intimidate: { name: "Intimidate", kind: "field", field_skill: "athletics", field_outcome: "sneak", field_difficulty: "hard",
                    effects: [], description: "Stand tall and loud enough that whatever waits on the road thinks better of it." },
      pick_lock: { name: "Pick Lock", kind: "field", field_skill: "thievery", field_outcome: "story", field_difficulty: "normal",
                   effects: [], description: "A door, a chest, a cell. What's behind it is the GM's to tell." },
      meditate: { name: "Meditate", kind: "field", field_skill: "insight", field_outcome: "restore", field_difficulty: "normal", field_power: 25,
                  effects: [], description: "A moment's stillness, shared: a quarter of everyone's HP and MP back." },
      appraise: { name: "Appraise", kind: "field", field_skill: "lore", field_outcome: "learn", field_difficulty: "normal",
                  effects: [], description: "Read what's waiting on the road before it moves: its weaknesses, known before the fight." },
      field_dressing: { name: "Field Dressing", kind: "field", field_skill: "insight", field_outcome: "restore", field_difficulty: "easy", field_power: 40,
                        effects: [], description: "Bandages and a quiet word: everyone standing gets some of their strength back." },
      parley: { name: "Parley", kind: "field", field_skill: "persuasion", field_outcome: "sneak", field_difficulty: "normal",
                effects: [], description: "Talk your way past what's waiting on the road." },
      familiar: { name: "Familiar", kind: "field", field_skill: "survival", field_outcome: "reveal", field_difficulty: "normal",
                  effects: [], description: "A small summoned thing runs ahead and shows you what's near." },
      read_the_land: { name: "Read the Land", kind: "field", field_skill: "survival", field_outcome: "safe_road", field_difficulty: "normal",
                       effects: [], description: "Find the way the land wants you to go: the next dangerous path is safe." },
      scout: { name: "Scout from Above", kind: "field", field_skill: "athletics", field_outcome: "reveal", field_difficulty: "easy",
               effects: [], description: "Up a tree, a tower, a cliff: every place near the party comes into view." },
      revenge: { name: "Revenge", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                 effects: [ { primitive: "physical", power: 90, grudge: 200 } ],
                 description: "Every bruise paid back: the nearer you are to falling, the harder it lands." },
      bewilder: { name: "Bewilder", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "tint",
                  effects: [ { primitive: "status", kind: "confuse", chance: 60, duration: 3 } ],
                  description: "Friend and foe look alike for a while." },
      channel: { name: "Channel", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
                 effects: [ { primitive: "status", kind: "charged", chance: 100, duration: 3 } ],
                 description: "Gather the power: the next spell lands twice as hard, for the same MP. The Black Mage's own command." },
      pray: { name: "Pray", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "float",
              effects: [ { primitive: "heal", power: 6 } ],
              description: "A little healing for everyone, for free. The White Mage's own command." },
      flame_blade: { name: "Flame Blade", kind: "skill", target: "single_enemy", mp_cost: 3, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "fire", power: 120 } ],
                     description: "A spell run down the length of a sword. The Red Mage's own command." },
      call_sprite: { name: "Call Sprite", kind: "magic", target: "self", mp_cost: 12, gesture: "pop",
                     effects: [ { primitive: "summon", creature: "sprite" } ],
                     description: "A small bright friend who makes everyone quick, a second go each for a round or two, then flits off. The Summoner's own command." },
      gaia: { name: "Gaia", kind: "skill", target: "all_enemies", mp_cost: 4, gesture: "flash",
              effects: [ { primitive: "elemental", type: "terrain", power: 12 } ],
              description: "The ground itself answers: its type is the land you're fighting on. The Geomancer's own command." },
      jump: { name: "Jump", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
              effects: [ { primitive: "jump", power: 180 } ],
              description: "Leap out of reach for a round, then come down hard. The Dragoon's own command." },
      # Summons: big, typed, and dear.
      # Small summons: a creature comes, does one thing well, and goes (the
      # summon primitive). The creatures are in the Bestiary.
      call_eagle: { name: "Call Eagle", kind: "magic", target: "self", mp_cost: 5, gesture: "pop",
                    effects: [ { primitive: "summon", creature: "eagle" } ], description: "A hunting eagle stoops on one foe and is gone." },
      call_wisp: { name: "Call Wisp", kind: "magic", target: "self", mp_cost: 7, gesture: "pop",
                   effects: [ { primitive: "summon", creature: "wisp" } ], description: "A cold light drifts through the enemy line." },
      call_salamander: { name: "Call Salamander", kind: "magic", target: "self", mp_cost: 9, gesture: "pop",
                         effects: [ { primitive: "summon", creature: "salamander" } ], description: "A lizard the size of a dog, breathing fire at whatever you point at." },
      call_turtle: { name: "Call Turtle", kind: "magic", target: "self", mp_cost: 14, gesture: "pop",
                     effects: [ { primitive: "summon", creature: "stone_turtle", duration: 3 } ],
                     description: "An old stone turtle stays a while and wards the party each turn." },
      call_serpent: { name: "Call Serpent", kind: "magic", target: "self", mp_cost: 20, gesture: "pop",
                      effects: [ { primitive: "summon", creature: "river_serpent", duration: 2 } ],
                      description: "A river serpent coils round the fight for two turns, crushing everything in reach." },
      # Later in each job's learn table, and each job's last lesson (its
      # capstone, at job level 50; the climb to 100 is mastery).
      stalwart: { name: "Stalwart", kind: "skill", target: "all_allies", mp_cost: 6, gesture: "shake",
                  effects: [ { primitive: "buff", stat: "def", amount: 50, duration: 3 } ], description: "Everyone stands a little behind the Knight, and it helps." },
      oathblade: { name: "Oathblade", kind: "skill", target: "single_enemy", mp_cost: 10, gesture: "lunge",
                   effects: [ { primitive: "physical", power: 260 } ], description: "The Knight's last lesson: one blow with everything sworn behind it." },
      pilfer: { name: "Pilfer", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                effects: [ { primitive: "steal", chance: 90 } ], description: "Hands so quick the pocket is empty before it's missed." },
      shadowdance: { name: "Shadowdance", kind: "skill", target: "single_enemy", mp_cost: 8, gesture: "spin",
                     effects: [ { primitive: "physical", type: "dark", power: 70, hits: 4 } ], description: "Four cuts from four places at once. The Thief's last lesson." },
      chakra: { name: "Chakra", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
                effects: [ { primitive: "heal", power: 40 }, { primitive: "cleanse" } ], description: "Breathe in, and the body mends itself." },
      final_fist: { name: "Final Fist", kind: "skill", target: "single_enemy", mp_cost: 10, gesture: "lunge",
                    effects: [ { primitive: "physical", type: "fighting", power: 320 } ], description: "Everything the Monk has learned, in one punch." },
      thundara: { name: "Thundara", kind: "magic", target: "all_enemies", mp_cost: 10, gesture: "flash",
                  effects: [ { primitive: "elemental", type: "electric", power: 10 } ], description: "Lightning that forks through the whole line." },
      flare: { name: "Flare", kind: "magic", target: "single_enemy", mp_cost: 24, gesture: "flash",
               effects: [ { primitive: "elemental", type: "fire", power: 40 } ], description: "The heart of a star, for a moment. The Black Mage's last lesson." },
      curaga: { name: "Curaga", kind: "magic", target: "all_allies", mp_cost: 16, gesture: "float",
                effects: [ { primitive: "heal", power: 32 } ], description: "Deep healing for everyone at once." },
      holy: { name: "Holy", kind: "magic", target: "single_enemy", mp_cost: 24, gesture: "flash",
              effects: [ { primitive: "elemental", type: "psychic", power: 38 } ], description: "A white light that judges. The White Mage's last lesson." },
      enblizzard: { name: "Enblizzard", kind: "magic", target: "self", mp_cost: 4, gesture: "flash",
                    effects: [ { primitive: "imbue", type: "ice", duration: 3 } ], description: "Frost on the blade: your Attack strikes as ice for a while." },
      crimson_rain: { name: "Crimson Rain", kind: "magic", target: "all_enemies", mp_cost: 18, gesture: "flash",
                      effects: [ { primitive: "elemental", type: "fire", power: 18 } ], description: "Red sparks falling everywhere at once. The Red Mage's last lesson." },
      quake: { name: "Quake", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "shake",
               effects: [ { primitive: "elemental", type: "ground", power: 16 } ], description: "The ground itself shrugs them off." },
      lifeblood: { name: "Lifeblood", kind: "magic", target: "all_allies", mp_cost: 8, gesture: "float",
                   effects: [ { primitive: "heal", power: 20 } ], description: "Green things grow round the party's feet, and the wounds close." },
      gaias_wrath: { name: "Gaia's Wrath", kind: "magic", target: "all_enemies", mp_cost: 26, gesture: "shake",
                     effects: [ { primitive: "elemental", type: "ground", power: 30 } ], description: "The land remembers every insult. The Geomancer's last lesson." },
      wyrm_breath: { name: "Wyrm Breath", kind: "skill", target: "all_enemies", mp_cost: 10, gesture: "flash",
                     effects: [ { primitive: "elemental", type: "fire", power: 14 } ], description: "Something of the dragon in the Dragoon, breathed out." },
      skyfall: { name: "Skyfall", kind: "skill", target: "single_enemy", mp_cost: 12, gesture: "lunge",
                 effects: [ { primitive: "jump", power: 480 } ], description: "Up past the clouds, and down like judgement. The Dragoon's last lesson." },
      call_wyvern: { name: "Call Wyvern", kind: "magic", target: "self", mp_cost: 30, gesture: "pop",
                     effects: [ { primitive: "summon", creature: "wyvern", duration: 2 } ],
                     description: "A wyvern wheels over the fight for two turns, raking everything below. The Summoner's last lesson." },
      sky_rend: { name: "Sky Rend", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                  effects: [ { primitive: "elemental", type: "flying", power: 26 } ], description: "Wings like knives." },
      # What the creatures do.
      talon_dive: { name: "Talon Dive", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", type: "flying", power: 180 } ], description: "Out of the sun, talons first." },
      chill_touch: { name: "Chill Touch", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "tint",
                     effects: [ { primitive: "elemental", type: "ice", power: 12 }, { primitive: "status", kind: "slow", chance: 30, duration: 2 } ],
                     description: "The cold of somewhere else." },
      fire_breath: { name: "Fire Breath", kind: "magic", target: "single_enemy", mp_cost: 0, gesture: "flash",
                     effects: [ { primitive: "elemental", type: "fire", power: 30 } ], description: "A long, hot breath." },
      shell_ward: { name: "Shell Ward", kind: "magic", target: "all_allies", mp_cost: 0, gesture: "float",
                    effects: [ { primitive: "shield", power: 5, duration: 2 } ], description: "The turtle's patience, spread thin over everyone." },
      tidal_coil: { name: "Tidal Coil", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "shake",
                    effects: [ { primitive: "elemental", type: "water", power: 18 } ], description: "River water, and the weight of the serpent in it." },
      quicken: { name: "Quicken", kind: "magic", target: "all_allies", mp_cost: 0, gesture: "pop",
                 effects: [ { primitive: "status", kind: "haste", chance: 100, duration: 2 } ], description: "Everyone a little quicker." },
      # Geomancy: the land's arts.
      sinkhole: { name: "Sinkhole", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "shake",
                  effects: [ { primitive: "elemental", type: "ground", power: 16 } ], description: "The floor opens under one foe." },
      whirlwind: { name: "Whirlwind", kind: "magic", target: "all_enemies", mp_cost: 6, gesture: "spin",
                   effects: [ { primitive: "elemental", type: "flying", power: 12 } ], description: "The wind takes them all off their feet." },
      riptide: { name: "Riptide", kind: "magic", target: "all_enemies", mp_cost: 8, gesture: "flash",
                 effects: [ { primitive: "elemental", type: "water", power: 14 },
                            { primitive: "status", kind: "slow", chance: 40, duration: 3 } ],
                 description: "Cold water, and the pull of it." },
      # The Dragoon's lance.
      lance: { name: "Lance", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "lunge",
               effects: [ { primitive: "physical", power: 140 } ], description: "A long reach and a hard point." },
      high_jump: { name: "High Jump", kind: "skill", target: "single_enemy", mp_cost: 6, gesture: "lunge",
                   effects: [ { primitive: "jump", power: 320 } ], description: "Higher, longer, harder." },
      dragon_crest: { name: "Dragon Crest", kind: "skill", target: "self", mp_cost: 3, gesture: "shake",
                      effects: [ { primitive: "buff", stat: "def", amount: 50, duration: 3 } ], description: "Scale-hard, for a while." },
      # New jobs' desperation moves.
      crimson_flurry: { name: "Crimson Flurry", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "spin",
                        effects: [ { primitive: "physical", type: "fire", power: 60, hits: 3 } ],
                        description: "Blade and flame, three times over. A Red Mage's desperation move." },
      megaflare: { name: "Megaflare", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "normal", power: 45 } ],
                   description: "Something enormous answers the call. A Summoner's desperation move." },
      cataclysm: { name: "Cataclysm", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "shake",
                   effects: [ { primitive: "elemental", type: "terrain", power: 30 } ],
                   description: "The whole land turns on them. A Geomancer's desperation move." },
      dragon_dive: { name: "Dragon Dive", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "flying", power: 240 } ],
                     description: "Straight down, from very high. A Dragoon's desperation move." },
      # Desperation moves: never learned, found. At a quarter HP or less an
      # attack sometimes becomes the job's move, once a battle.
      last_stand: { name: "Last Stand", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 220 } ],
                    description: "Everything, in one swing. A Freelancer's desperation move." },
      unbroken_line: { name: "Unbroken Line", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                       effects: [ { primitive: "physical", type: "steel", power: 130 } ],
                       description: "The Knight plants their feet and cuts through the whole line. A desperation move." },
      vanishing_cut: { name: "Vanishing Cut", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "fade",
                       effects: [ { primitive: "physical", type: "dark", power: 75, hits: 4 } ],
                       description: "Four cuts from nowhere. A Thief's desperation move." },
      hundred_fists: { name: "Hundred Fists", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "shake",
                       effects: [ { primitive: "physical", type: "fighting", power: 50, hits: 6 } ],
                       description: "Not quite a hundred. A Monk's desperation move." },
      starfall: { name: "Starfall", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                  effects: [ { primitive: "elemental", type: "rock", power: 34 } ],
                  description: "The sky answers, once. A Black Mage's desperation move." },
      judgement: { name: "Judgement", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "fire", power: 26 },
                             { primitive: "status", kind: "blind", chance: 50, duration: 3 } ],
                   description: "Holy fire, too bright to look at. A White Mage's desperation move." }
    }.freeze
  end
end
