# frozen_string_literal: true

# The Armory: consumables, and each kind of gear in four steps. (Seeds::BaseWorld)
module Seeds
  module BaseWorld
    ITEMS = {
      potion: { name: "Potion", category: "consumable", price: 40, target: "single_ally",
                effects: [ { primitive: "heal", power: 30 } ], description: "Restores a little HP." },
      phoenix_down: { name: "Phoenix Down", category: "consumable", price: 300, target: "single_ally",
                      effects: [ { primitive: "revive", fraction: 20 } ], description: "A feather that remembers being alive." },
      hi_potion: { name: "Hi-Potion", category: "consumable", price: 150, target: "single_ally",
                   effects: [ { primitive: "heal", power: 80 } ], description: "Restores a good deal of HP." },
      smoke_pellet: { name: "Smoke Pellet", category: "consumable", price: 80, target: "self",
                      effects: [ { primitive: "escape" } ], description: "For when the plan was bad." },
      antidote: { name: "Antidote", category: "consumable", price: 50, target: "single_ally",
                  effects: [ { primitive: "cleanse", kind: "poison" } ], description: "Bitter, and it works." },
      eye_drops: { name: "Eye Drops", category: "consumable", price: 50, target: "single_ally",
                   effects: [ { primitive: "cleanse", kind: "blind" } ], description: "Clears the eyes of darkness." },
      echo_screen: { name: "Echo Screen", category: "consumable", price: 50, target: "single_ally",
                     effects: [ { primitive: "cleanse", kind: "silence" } ], description: "Gives a silenced throat back its voice." },
      remedy: { name: "Remedy", category: "consumable", price: 250, target: "single_ally",
                effects: [ { primitive: "cleanse" } ], description: "Cures everything that ails you, except being down." },
      broadsword: { name: "Broadsword", category: "sword", price: 200, stats: { atk: 14 },
                    description: "A plain, honest blade." },
      dagger: { name: "Dagger", category: "knife", price: 120, stats: { atk: 9, agi: 2 },
                description: "Light enough to strike first." },
      rod: { name: "Rod", category: "rod", price: 150, stats: { atk: 4, mag: 4 },
             description: "Wood, wire and a borrowed spark." },
      staff: { name: "Staff", category: "staff", price: 150, stats: { atk: 5, spr: 4 },
               description: "A walking stick that listens." },
      buckler: { name: "Buckler", category: "shield", price: 100, stats: { def: 3, mdef: 1 },
                 description: "Small, round, often dented." },
      iron_spear: { name: "Iron Spear", category: "spear", price: 220, stats: { atk: 15 },
                    description: "Reach is its own kind of armour." },
      hand_axe: { name: "Hand Axe", category: "axe", price: 180, stats: { atk: 13 },
                  description: "For wood, mostly." },
      iron_helm: { name: "Iron Helm", category: "helmet", price: 150, stats: { def: 3 },
                   description: "Rings when hit. Better than the alternative." },
      leather_cap: { name: "Leather Cap", category: "hat", price: 60, stats: { def: 1, mdef: 1 },
                     description: "Keeps the rain off." },
      bronze_armor: { name: "Bronze Armor", category: "heavy_armor", price: 400, stats: { def: 8, agi: -2 },
                      description: "Heavy, loud and reassuring." },
      cotton_robe: { name: "Cotton Robe", category: "robe", price: 120, stats: { def: 2, mdef: 4 },
                     description: "Embroidered with small protective sigils." },
      power_ring: { name: "Power Ring", category: "accessory", price: 1000, stats: { str: 5 },
                    description: "A ring cut from a single garnet." },

      # The ladders: each kind of gear in four steps (Dragon Quest's copper,
      # iron, steel). The first is what a new character starts in; the
      # second a village sells; the third a port; the fourth is found.
      mythril_knife: { name: "Mythril Knife", category: "knife", price: 500, stats: { atk: 16, agi: 3 }, description: "Lighter than it looks, sharper than it should be." },
      main_gauche: { name: "Main Gauche", category: "knife", price: 1400, stats: { atk: 24, agi: 4, def: 2 }, description: "For the off hand, and the parry." },
      assassins_dagger: { name: "Assassin's Dagger", category: "knife", price: 3800, stats: { atk: 32, agi: 6 }, description: "Nobody admits to having made it." },
      longsword: { name: "Longsword", category: "sword", price: 550, stats: { atk: 21 }, description: "A knight's first real sword." },
      mythril_sword: { name: "Mythril Sword", category: "sword", price: 1500, stats: { atk: 29 }, description: "Pale, cold and very light." },
      rune_blade: { name: "Rune Blade", category: "sword", price: 4200, stats: { atk: 36, mag: 4 }, description: "The letters on it move when nobody's looking." },
      battle_axe: { name: "Battle Axe", category: "axe", price: 520, stats: { atk: 22, agi: -1 }, description: "Not for wood." },
      mythril_axe: { name: "Mythril Axe", category: "axe", price: 1450, stats: { atk: 30 }, description: "Swings like a lighter axe and lands like a heavier one." },
      ogre_killer: { name: "Ogre Killer", category: "axe", price: 4000, stats: { atk: 40, agi: -2 }, description: "Named for the job, and good at it." },
      partisan: { name: "Partisan", category: "spear", price: 600, stats: { atk: 22 }, description: "A spear with ideas: a blade, a hook, a spike." },
      mythril_spear: { name: "Mythril Spear", category: "spear", price: 1600, stats: { atk: 30 }, description: "Long, light, and it hums in the wind." },
      wind_spear: { name: "Wind Spear", category: "spear", price: 4300, stats: { atk: 38, agi: 3 }, description: "Thrown once, it came back." },
      oak_staff: { name: "Oak Staff", category: "staff", price: 480, stats: { atk: 7, spr: 7 }, description: "Cut from a tree that was old when the village was new." },
      healing_staff: { name: "Healing Staff", category: "staff", price: 1300, stats: { atk: 9, spr: 11 }, description: "Warm to hold, even in winter." },
      sages_staff: { name: "Sage's Staff", category: "staff", price: 3900, stats: { atk: 11, spr: 15, mag: 5 }, description: "Its last owner wrote in the margins of the world." },
      flame_rod: { name: "Flame Rod", category: "rod", price: 500, stats: { atk: 6, mag: 7 }, description: "The tip is always a little too warm." },
      mythril_rod: { name: "Mythril Rod", category: "rod", price: 1400, stats: { atk: 8, mag: 11 }, description: "Spells leave it faster." },
      wizards_rod: { name: "Wizard's Rod", category: "rod", price: 4000, stats: { atk: 10, mag: 16 }, description: "It chose its wizard, not the other way round." },
      iron_shield: { name: "Iron Shield", category: "shield", price: 380, stats: { def: 6, mdef: 2 }, description: "A proper shield. Heavy, and worth it." },
      mythril_shield: { name: "Mythril Shield", category: "shield", price: 1100, stats: { def: 9, mdef: 4 }, description: "Spells skid off it." },
      aegis_shield: { name: "Aegis Shield", category: "shield", price: 3600, stats: { def: 13, mdef: 9 }, description: "The face on it frowns at magic." },
      horned_helm: { name: "Horned Helm", category: "helmet", price: 420, stats: { def: 5 }, description: "The horns are mostly for show." },
      mythril_helm: { name: "Mythril Helm", category: "helmet", price: 1150, stats: { def: 8, mdef: 2 }, description: "You forget you're wearing it." },
      crystal_helm: { name: "Crystal Helm", category: "helmet", price: 3500, stats: { def: 11, mdef: 4 }, description: "Clear as ice and harder." },
      feathered_hat: { name: "Feathered Hat", category: "hat", price: 300, stats: { def: 2, mdef: 3, agi: 1 }, description: "Jaunty, and it knows it." },
      wizards_hat: { name: "Wizard's Hat", category: "hat", price: 900, stats: { def: 3, mdef: 5, mag: 2 }, description: "Pointed, of course." },
      circlet: { name: "Circlet", category: "hat", price: 3000, stats: { def: 4, mdef: 8, mag: 3, spr: 3 }, description: "A thin silver band that makes thinking easier." },
      iron_armor: { name: "Iron Armor", category: "heavy_armor", price: 900, stats: { def: 12, agi: -2 }, description: "Everything the bronze was, and more of it." },
      mythril_armor: { name: "Mythril Armor", category: "heavy_armor", price: 2200, stats: { def: 17, agi: -1 }, description: "Plate that moves like cloth." },
      crystal_armor: { name: "Crystal Armor", category: "heavy_armor", price: 5500, stats: { def: 23, mdef: 5, agi: -1 }, description: "Light passes through it. Blades don't." },
      leather_armor: { name: "Leather Armor", category: "light_armor", price: 150, stats: { def: 4, agi: 1 }, description: "Boiled, stitched and comfortable." },
      chain_vest: { name: "Chain Vest", category: "light_armor", price: 450, stats: { def: 7 }, description: "Rings on rings. Quieter than it sounds." },
      mythril_vest: { name: "Mythril Vest", category: "light_armor", price: 1200, stats: { def: 10, agi: 2 }, description: "Worn under a coat, nobody knows." },
      ninja_gear: { name: "Ninja Gear", category: "light_armor", price: 3600, stats: { def: 14, agi: 5 }, description: "Dark, close and silent." },
      silk_robe: { name: "Silk Robe", category: "robe", price: 400, stats: { def: 3, mdef: 7 }, description: "Spun by worms that were paid in songs." },
      sages_robe: { name: "Sage's Robe", category: "robe", price: 1100, stats: { def: 5, mdef: 10, spr: 2 }, description: "Heavy with pockets, all of them full." },
      white_robe: { name: "White Robe", category: "robe", price: 3400, stats: { def: 7, mdef: 14, mag: 3, spr: 3 }, description: "It never needs washing." },
      hermes_sandals: { name: "Hermes Sandals", category: "accessory", price: 800, stats: { agi: 4 }, description: "Little wings at the heel. They flutter when you're late." },
      silver_bracer: { name: "Silver Bracer", category: "accessory", price: 700, stats: { def: 3, mdef: 3 }, description: "Turns a blade once, then twice." },
      faerie_earring: { name: "Faerie Earring", category: "accessory", price: 900, stats: { mag: 4 }, description: "Someone tiny whispers spells in your ear." },
      protect_ring: { name: "Protect Ring", category: "accessory", price: 2400, stats: { def: 4, mdef: 6 }, description: "Warm when danger is near." }
    }.freeze
  end
end
