# frozen_string_literal: true

# The Job Compendium: each job and its learn table. (Seeds::BaseWorld)
module Seeds
  module BaseWorld
    JOBS = {
      freelancer: { name: "Freelancer", base_type: "normal", skills: %w[persuasion survival], field_ability: "forage", signature: "rally", desperation: "last_stand", description: "No talents, no limits. Every hero starts here.",
                    stat_multipliers: {}, ability_slots: 2, equip_categories: Item::EQUIPMENT_CATEGORIES,
                    innates: [], levels: [ [ "libra", 1 ], [ "cure", 12 ], [ "double_cut", 20 ], [ "war_cry", 28 ], [ "barrier", 36 ], [ "haste", 50 ] ] },
      knight: { name: "Knight", base_type: "steel", skills: %w[athletics endurance], field_ability: "intimidate", signature: "cover", passive: "second_wind", desperation: "unbroken_line", description: "Heavy armor, a long sword and the resolve to stand in front.",
                stat_multipliers: { max_hp: 130, str: 120, vit: 120, agi: 90, mag: 60 },
                equip_categories: %w[sword axe spear shield helmet heavy_armor accessory],
                innates: [ { stat: "def", percent: 10 } ],
                levels: [ [ "war_cry", 1 ], [ "armor_break", 6 ], [ "double_cut", 14 ], [ "shield_bash", 22 ], [ "stalwart", 34 ], [ "oathblade", 50 ] ] },
      thief: { name: "Thief", base_type: "dark", skills: %w[stealth thievery], field_ability: "pick_lock", signature: "mug", passive: "first_strike", desperation: "vanishing_cut", description: "Fast hands, faster feet.",
               stat_multipliers: { agi: 140, str: 90, max_hp: 90 },
               equip_categories: %w[knife hat light_armor accessory],
               innates: [ { stat: "agi", add: 5 } ],
               levels: [ [ "steal", 1 ], [ "smoke_bomb", 6 ], [ "hide", 12 ], [ "double_cut", 18 ], [ "pilfer", 34 ], [ "shadowdance", 50 ] ] },
      monk: { name: "Monk", base_type: "fighting", skills: %w[athletics insight], field_ability: "meditate", signature: "focus", passive: "counter", desperation: "hundred_fists", description: "Fists instead of steel.",
              stat_multipliers: { max_hp: 140, str: 130, vit: 110, mag: 50 },
              equip_categories: %w[light_armor accessory],
              innates: [ { stat: "atk", add: 12 } ],
              levels: [ [ "kick", 1 ], [ "war_cry", 8 ], [ "inner_fury", 16 ], [ "revenge", 24 ], [ "chakra", 34 ], [ "final_fist", 50 ] ] },
      black_mage: { name: "Black Mage", base_type: "fire", skills: %w[lore insight], field_ability: "appraise", signature: "channel", passive: "mp_regen", desperation: "starfall", description: "Destruction, studied carefully.",
                    stat_multipliers: { max_hp: 70, max_mp: 150, mag: 140, str: 60 },
                    equip_categories: %w[knife rod robe hat accessory],
                    innates: [],
                    levels: [ [ "fire", 1 ], [ "blizzard", 3 ], [ "thunder", 5 ], [ "sleep", 9 ], [ "osmose", 14 ], [ "fira", 18 ], [ "bio", 23 ], [ "gravity", 28 ], [ "drain", 33 ], [ "thundara", 40 ], [ "flare", 50 ] ] },
      white_mage: { name: "White Mage", base_type: "psychic", skills: %w[insight persuasion], field_ability: "field_dressing", signature: "pray", passive: "regen", desperation: "judgement", description: "Keeps everyone else alive.",
                    stat_multipliers: { max_hp: 80, max_mp: 140, mag: 120, spr: 130, str: 60 },
                    equip_categories: %w[staff robe hat accessory],
                    innates: [ { stat: "mdef", percent: 20 } ],
                    levels: [ [ "cure", 1 ], [ "silence", 5 ], [ "barrier", 9 ], [ "esuna", 12 ], [ "cura", 16 ], [ "raise", 22 ], [ "haste", 28 ], [ "curaga", 38 ], [ "holy", 50 ] ] },
      red_mage: { name: "Red Mage", base_type: "normal", skills: %w[lore persuasion], field_ability: "parley", signature: "flame_blade", passive: "regen", desperation: "crimson_flurry",
                  description: "A little of everything, and a sword to put it through.",
                  stat_multipliers: { max_hp: 95, max_mp: 115, str: 105, mag: 110 },
                  equip_categories: %w[sword knife rod light_armor robe hat accessory],
                  innates: [],
                  levels: [ [ "fire", 1 ], [ "cure", 1 ], [ "blizzard", 5 ], [ "thunder", 8 ], [ "enfire", 12 ], [ "sleep", 16 ], [ "stop", 22 ], [ "haste", 28 ], [ "enblizzard", 36 ], [ "crimson_rain", 50 ] ] },
      summoner: { name: "Summoner", base_type: "ghost", skills: %w[lore survival], field_ability: "familiar", signature: "call_sprite", passive: "mp_regen", desperation: "megaflare",
                  description: "Calls things that should not come when called.",
                  stat_multipliers: { max_hp: 75, max_mp: 160, mag: 135, str: 55 },
                  equip_categories: %w[staff rod robe hat accessory],
                  innates: [],
                  levels: [ [ "call_eagle", 1 ], [ "call_wisp", 4 ], [ "call_salamander", 8 ], [ "call_turtle", 20 ], [ "call_serpent", 34 ], [ "call_wyvern", 50 ] ] },
      geomancer: { name: "Geomancer", base_type: "ground", skills: %w[survival endurance], field_ability: "read_the_land", signature: "gaia", passive: "regen", desperation: "cataclysm",
                   description: "Reads the land and borrows its temper.",
                   stat_multipliers: { max_hp: 100, mag: 115, spr: 115, str: 90 },
                   equip_categories: %w[staff axe light_armor hat accessory],
                   innates: [ { stat: "mdef", percent: 10 } ],
                   levels: [ [ "sinkhole", 1 ], [ "whirlwind", 8 ], [ "riptide", 16 ], [ "quake", 26 ], [ "lifeblood", 36 ], [ "gaias_wrath", 50 ] ] },
      dragoon: { name: "Dragoon", base_type: "flying", skills: %w[athletics survival], field_ability: "scout", signature: "jump", passive: "first_strike", desperation: "dragon_dive",
                 description: "Fights from above. Mostly from above.",
                 stat_multipliers: { max_hp: 120, str: 125, agi: 105, mag: 50 },
                 equip_categories: %w[spear shield helmet heavy_armor accessory],
                 innates: [ { stat: "atk", add: 4 } ],
                 levels: [ [ "lance", 1 ], [ "dragon_crest", 8 ], [ "high_jump", 18 ], [ "wyrm_breath", 34 ], [ "skyfall", 50 ] ] }
    }.freeze
  end
end
