# frozen_string_literal: true

# The Bestiary: what's met in the wild, the bosses, and what's summoned. (Seeds::BaseWorld)
module Seeds
  module BaseWorld
    MONSTERS = {
      # Summoned, not met in the wild (the summon primitive).
      eagle: { name: "Eagle", level: 3, stats: stats(max_hp: 40, str: 14, atk: 10, agi: 30, def: 2, mdef: 2), base_type: "flying",
               exp: 0, gil: 0, abp: 0, ai_script: [ { use: "talon_dive" } ], description: "Comes when called, from a long way up." },
      wisp: { name: "Wisp", level: 3, stats: stats(max_hp: 30, mag: 16, agi: 20, mdef: 8), base_type: "ghost",
              exp: 0, gil: 0, abp: 0, ai_script: [ { use: "chill_touch" } ], description: "A light that shouldn't be there." },
      salamander: { name: "Salamander", level: 5, stats: stats(max_hp: 60, mag: 20, agi: 12, def: 4, mdef: 6), base_type: "fire",
                    exp: 0, gil: 0, abp: 0, ai_script: [ { use: "fire_breath" } ], description: "Warm to hold. Don't." },
      stone_turtle: { name: "Stone Turtle", level: 10, stats: stats(max_hp: 200, mag: 18, agi: 4, def: 30, mdef: 20), base_type: "rock",
                      exp: 0, gil: 0, abp: 0, ai_script: [ { use: "shell_ward" } ], description: "Older than the road. In no hurry." },
      river_serpent: { name: "River Serpent", level: 15, stats: stats(max_hp: 160, mag: 26, agi: 14, def: 8, mdef: 10), base_type: "water",
                       exp: 0, gil: 0, abp: 0, ai_script: [ { use: "tidal_coil" } ], description: "Lives where the river bends. Owes the Summoner a favour." },
      wyvern: { name: "Wyvern", level: 25, stats: stats(max_hp: 260, mag: 34, agi: 22, def: 12, mdef: 12), base_type: "flying",
                exp: 0, gil: 0, abp: 0, ai_script: [ { use: "sky_rend" } ], description: "Answers only a master's call." },
      sprite: { name: "Sprite", level: 1, stats: stats(max_hp: 20, mag: 10, agi: 40), base_type: "psychic",
                exp: 0, gil: 0, abp: 0, ai_script: [ { use: "quicken" } ], description: "Small, bright and quick, and makes you quick too." },
      goblin: { name: "Goblin", level: 1, stats: stats(max_hp: 45, str: 9, atk: 8, agi: 8, def: 3, mdef: 2),
                base_type: "normal", affinities: { fire: "weak" }, exp: 20, gil: 30, abp: 2,
                ai_script: [ { if: { chance: 25 }, use: "goblin_punch" }, { use: "attack" } ],
                drops: [ { item: "potion", chance: 30 } ],
                description: "Small, green and far braver in groups." },
      wolf: { name: "Wolf", level: 2, stats: stats(max_hp: 60, str: 11, atk: 10, agi: 16, def: 3, mdef: 3),
              exp: 30, gil: 20, abp: 2,
              ai_script: [ { if: { round_multiple: 3 }, use: "howl" }, { if: { chance: 30 }, use: "venom_bite" }, { use: "attack" } ],
              drops: [ { item: "potion", chance: 25 } ],
              description: "Hunts in packs along the old roads." },
      killer_bee: { name: "Killer Bee", level: 2, stats: stats(max_hp: 35, str: 8, atk: 9, agi: 22, def: 1, mdef: 2),
                    base_type: "bug", exp: 24, gil: 15, abp: 2,
                    ai_script: [ { if: { chance: 40 }, use: "venom_bite", target: "lowest_hp" }, { use: "attack" } ],
                    description: "The buzzing arrives before the bee does." },
      zombie: { name: "Zombie", level: 3, stats: stats(max_hp: 110, str: 12, atk: 12, agi: 4, def: 4, mdef: 1),
                base_type: "dark", undead: true, affinities: { fire: "weak" }, status_immune: %w[poison sleep],
                exp: 48, gil: 50, abp: 3,
                ai_script: [ { use: "attack", target: "lowest_hp" } ],
                description: "Slow, relentless and already dead." },
      skeleton: { name: "Skeleton", level: 3, stats: stats(max_hp: 85, str: 13, atk: 12, agi: 9, def: 5, mdef: 3),
                  base_type: "dark", undead: true, status_immune: %w[poison sleep], exp: 40, gil: 35, abp: 3,
                  ai_script: [ { if: { chance: 35 }, use: "shadow_strike" }, { use: "attack" } ],
                  drops: [ { item: "phoenix_down", chance: 10 } ],
                  description: "Bones that remember how to hold a sword." },
      nymph: { name: "Nymph", level: 3, stats: stats(max_hp: 75, max_mp: 30, mag: 15, str: 7, atk: 5, agi: 14, def: 3, mdef: 8),
               base_type: "water", exp: 38, gil: 45, abp: 3,
               ai_script: [ { if: { self_hp_below: 40 }, use: "cure", target: "self" }, { if: { chance: 60 }, use: "water_jet" }, { use: "attack" } ],
               drops: [ { item: "hi_potion", chance: 15 } ],
               description: "Lives in the forest pools. Doesn't like to be looked at." },
      flan: { name: "Flan", level: 3,
              stats: stats(max_hp: 70, max_mp: 20, mag: 14, atk: 6, agi: 6, def: 60, mdef: 0),
              base_type: "water", exp: 42, gil: 40, abp: 3,
              ai_script: [ { if: { chance: 50 }, use: "blizzard" }, { use: "attack" } ],
              description: "Blades bounce off. Bring a mage." },
      sand_worm: { name: "Sand Worm", level: 4, stats: stats(max_hp: 180, str: 15, atk: 14, agi: 6, def: 6, mdef: 4),
                   base_type: "ground", affinities: { ground: "absorb" }, exp: 70, gil: 75, abp: 4,
                   ai_script: [ { if: { chance: 35 }, use: "venom_bite" }, { use: "attack", target: "highest_hp" } ],
                   drops: [ { item: "phoenix_down", chance: 10 } ],
                   description: "Rises from the dunes when something walks over it." },
      goblin_chief: { boss: true, boss_line: "Mine. The cave, the shinies, the hat. All mine.", name: "Goblin Chief", level: 4,
                      stats: stats(max_hp: 140, max_mp: 12, str: 14, atk: 13, agi: 10, def: 5, mdef: 3, mag: 10),
                      base_type: "fighting", affinities: { fire: "weak" }, exp: 85, gil: 150, abp: 4,
                      ai_script: [ { if: { self_hp_below: 30 }, use: "cure", target: "self" },
                                  { if: { chance: 40 }, use: "goblin_punch" }, { use: "attack" } ],
                      drops: [ { item: "broadsword", chance: 15 } ],
                      variant: { hue: 40, scale: 125 },
                      description: "A goblin in a slightly bigger hat. Palette-swapped from the Goblin." },
      dark_mage: { boss: true, boss_line: "The crystals were never meant for your kind. Kneel, and I'll make it quick.", name: "Dark Mage", level: 5,
                   stats: stats(max_hp: 120, max_mp: 60, str: 6, mag: 20, spr: 16, atk: 4, agi: 12, def: 3, mdef: 12),
                   base_type: "dark", affinities: { dark: "absorb" }, exp: 100, gil: 200, abp: 4,
                   ai_script: [ { if: { ally_hp_below: 40 }, use: "drain" }, { if: { chance: 30 }, use: "sleep" },
                               { if: { chance: 20 }, use: "bewilder" }, { if: { chance: 60 }, use: "fire" }, { use: "bio" } ],
                   drops: [ { item: "rod", chance: 20 } ],
                   description: "Studied at the same academy as the party's black mage. Graduated differently." },
      ogre: { boss: true, boss_line: "You came for the crystal. So did the last ones. They're under the pass.", name: "Ogre", level: 6,
              stats: stats(max_hp: 340, max_mp: 30, str: 24, mag: 8, atk: 22, agi: 7, def: 12, mdef: 6),
              base_type: "normal", affinities: { ice: "absorb", fire: "resist" }, status_immune: %w[sleep], exp: 280, gil: 400, abp: 8,
              ai_script: [ { if: { self_hp_below: 30 }, use: "cure", target: "self" },
                          { if: { round_multiple: 3 }, use: "crush", target: "lowest_hp" },
                          { if: { round_multiple: 4 }, use: "war_cry" }, { use: "attack", target: "lowest_hp" } ],
              drops: [ { item: "bronze_armor", chance: 50 }, { item: "power_ring", chance: 5 } ],
              description: "Guards the pass. A boss for a party of four at job level 2 or so." },
      crystal_wyrm: { boss: true, boss_line: "I have slept on this fire for a thousand years. You will not take it from me.", name: "Crystal Wyrm", level: 10,
                      stats: stats(max_hp: 1200, max_mp: 200, str: 26, mag: 24, spr: 20, atk: 24, agi: 14, def: 16, mdef: 16),
                      base_type: "rock", affinities: { electric: "weak" },
                      status_immune: %w[sleep paralyze silence poison], exp: 1400, gil: 2500, abp: 16,
                      ai_script: [ { if: { self_hp_below: 25, chance: 50 }, use: "cura" },
                                  { if: { round_multiple: 4 }, use: "crystal_breath" }, { if: { chance: 30 }, use: "thunder" },
                                  { use: "attack" } ],
                      drops: [ { item: "power_ring", chance: 100 } ],
                      description: "Grew around a shard of the fire crystal. The first real boss." }
    }.freeze
  end
end
