# frozen_string_literal: true

# Encounter tables and generator tables: what's met on a road, and what towns and dungeons are rolled from. (Seeds::BaseWorld)
module Seeds
  module BaseWorld
    ENCOUNTER_TABLES = {
      grasslands: { name: "Grasslands", terrain: "plains", tier: 1,
                    description: "Open country between the first towns.",
                    entries: [ { weight: 4, monsters: { goblin: 3 } }, { weight: 2, monsters: { wolf: 2 } },
                               { weight: 1, monsters: { goblin: 2, wolf: 1 } } ] },
      old_forest: { name: "Old Forest", terrain: "forest", tier: 1,
                    entries: [ { weight: 3, monsters: { killer_bee: 3 } }, { weight: 2, monsters: { wolf: 3 } },
                               { weight: 2, monsters: { nymph: 2 } }, { weight: 1, monsters: { goblin_chief: 1, goblin: 2 } } ] },
      dunes: { name: "Dunes", terrain: "desert", tier: 2,
               entries: [ { weight: 3, monsters: { sand_worm: 1 } }, { weight: 2, monsters: { killer_bee: 4 } } ] },
      barrow: { name: "Barrow", terrain: "crypt", tier: 2,
                description: "Old graves that don't stay shut.",
                entries: [ { weight: 3, monsters: { zombie: 2 } }, { weight: 3, monsters: { skeleton: 3 } },
                           { weight: 2, monsters: { zombie: 1, dark_mage: 1 } },
                           { weight: 1, monsters: { flan: 2 } } ] },
      goblin_cave: { name: "Goblin Cave", terrain: "cave", tier: 1,
                     description: "Goblins, their pets, and whatever they've let in.",
                     entries: [ { weight: 4, monsters: { goblin: 3 } }, { weight: 2, monsters: { goblin: 2 } },
                                { weight: 2, monsters: { goblin: 2, killer_bee: 1 } }, { weight: 1, monsters: { goblin: 4 } },
                                { weight: 1, monsters: { goblin_chief: 1, goblin: 1 } } ] },
      mountain_pass: { name: "Mountain Pass", terrain: "mountain", tier: 3,
                       entries: [ { weight: 1, monsters: { ogre: 1 } }, { weight: 3, monsters: { wolf: 3 } } ] }
    }.freeze

    GENERATOR_TABLES = {
      town_names: { name: "Town names", kind: "town_names",
                    entries: texts("Tule", "Carwen", "Walse", "Karnak", "Istory", "Jachol", "Lix", "Mirage",
                                   "Surgate", "Kelb", "Regole", "Quelb", "Mua", "Moore", "Crescent", "Bal",
                                   "Ferrow", "Amberlee", "Hollin", "Saltmarsh", "Greyford", "Cinderwick", "Oakhollow", "Thistlebrook") },
      dungeon_names: { name: "Dungeon names", kind: "dungeon_names",
                       entries: texts("The Sunken Crypt", "Hollow Barrow", "The Old Graves", "Kingsrest", "The Weeping Vault",
                                      "Ashen Catacombs", "The Silent Mound", "Pale Hill", "The Lantern Tombs", "Mourners' Deep") },
      cave_names: { name: "Cave names", kind: "dungeon_names",
                    entries: texts("Goblin Hole", "The Dripping Caves", "Rattail Warren", "Mossback Cave", "The Crooked Den",
                                   "Snaggletooth Grotto", "Mudwater Tunnels", "The Chittering Dark", "Bramble Cave", "Old Quarry") },
      given_names: { name: "Given names", kind: "names",
                     entries: texts("Mira", "Oskar", "Lenne", "Dorn", "Pell", "Hask", "Ivy", "Brand", "Sella", "Tobin", "Wren", "Garrick",
                                    "Nessa", "Rook", "Alma", "Bex", "Corin", "Dalia", "Edda", "Fenn", "Gile", "Hollis", "Ines", "Jory",
                                    "Kessa", "Lorn", "Maddock", "Nim", "Orla", "Piet", "Quill", "Rhosyn", "Saul", "Tamsin", "Ulric", "Vesna",
                                    "Wim", "Yara", "Zeb", "Anselm", "Brin", "Calla", "Doro", "Emrys", "Faye", "Gideon", "Hanne", "Ilse",
                                    "Jonah", "Kit", "Liesl", "Marek", "Noor", "Otto", "Pim", "Runa", "Sten", "Tilde", "Varro", "Wenna") },
      family_names: { name: "Families", kind: "families",
                      entries: texts("Vell", "Marrow", "Asher", "Crane", "Dunmore", "Hale", "Pike", "Rook", "Thorne", "Wick", "Briar", "Coldwell",
                                     "Fenwick", "Hargrave", "Lark", "Moss", "Oakes", "Sallow", "Tennant", "Garrow") },
      town_hooks: { name: "Townsfolk hooks", kind: "hooks",
                    entries: texts("Owes the guild more than they'll say.", "Saw green lights over {place} three nights running.",
                                   "Lost a brother on the road to {place}.", "Sells maps that are mostly right.",
                                   "Wants an escort to {town} and can't pay yet.", "Is hiding a runaway in the cellar.",
                                   "Swears the wind stopped last week, then started again.", "Collects crystal shards. Asks about them.",
                                   "Knows the old way into {dungeon}.", "Wants their stolen ring back, no questions asked.",
                                   "Was a soldier once. Won't say for which side.", "Keeps a chocobo that bites everyone but them.",
                                   "Has a letter for someone who never came back.", "Is certain the mayor is a monster in disguise.",
                                   "Pays well for goblin ears, and doesn't say why.", "Dreams of the sea, though they've never seen it.",
                                   "Heard singing from the old well.", "Is saving for a sword they'll never be able to lift.",
                                   "Their crops died overnight in a perfect circle.", "Needs medicine from {town} before the week is out.",
                                   "Was robbed on the road by someone polite.", "Knows a song about the heroes that isn't flattering.",
                                   "Runs a card game with a marked deck.", "Is looking for a missing apprentice.",
                                   "Found a key they can't find a lock for.", "Remembers when the crystal still sang.",
                                   "Carves charms against the dark. Some of them work.", "Wants the party to take a message to their mother.",
                                   "Is writing a book about monsters. Needs a closer look.", "Heard the temple bells ring with no one pulling.",
                                   "Sold something to the wrong person and regrets it.", "Hasn't slept since the lights went out on the hill.",
                                   "Will trade anything for news from the capital.", "Keeps staring at one of the party as if they know them.",
                                   "Buried something by the old mill and forgot which tree.", "Thinks the river is running backwards. It is.") },
      # Townsfolk couplets (Generators::Town#couplets): a memory and a wish,
      # in their own words. Any two go together. A wish can be for something
      # the party can bring: an item, or the nearest dungeon ({dungeon})
      # cleared (Location::Wishes).
      townsfolk_memories: { name: "Townsfolk memories", kind: "memories",
                         entries: texts("I lost my brother on the road to {place}.", "I was a soldier once. I won't say for which side.",
                                        "I grew up by the sea. I still dream about it.", "I burned the old mill down. It was an accident.",
                                        "I sang at a king's wedding, once.", "I found a key I can't find a lock for.",
                                        "I was the one who sealed {dungeon}. I had my reasons.", "I ran away from {town} with nothing but these boots.",
                                        "I raised six children in that house. None of them write.", "I cheated at cards for twenty years and never lost.",
                                        "I saw the crystal go dark. Everyone says I was dreaming.", "I buried my husband with his sword. I regret it now.",
                                        "I was a thief. The temple took me in.", "I carried letters on that road for thirty years.",
                                        "I lost a bet to a moogle and I'm still paying it off.", "I built half the houses on this street.",
                                        "I was born the night the bells rang by themselves.", "I walked out of {dungeon} alone. The others didn't.",
                                        "I used to guard the pass. Then the pass stopped needing guards.", "I married for money. It went badly.",
                                        "I've never left this town. Not once.", "I was a cook for a band of heroes. They didn't come back.") },
      townsfolk_wishes: { name: "Townsfolk wishes", kind: "wishes",
                        entries: texts("I keep a lantern in the window for him.", "I'm saving for a sword I'll never be able to lift.",
                                       "I want to see the sea before I die.", "I'm writing it all down, in case nobody believes me.",
                                       "I'd leave tomorrow if anyone would buy the house.", "I'm teaching my granddaughter the old songs.",
                                       "I'm looking for my apprentice. She went toward {place}.", "I'd trade anything for news from {town}.",
                                       "I don't go out after dark any more.", "I'm building a boat. Don't ask where I'll sail it.",
                                       "Half this town owes me money, and I mean to collect.", "I'm trying to be a better person. It's slow going.") +
                                 texts("I'd give anything to see {dungeon} quiet again.", "Nobody sleeps here for the noise from {dungeon}.",
                                       "My son went into {dungeon}. I want to know it's safe to look for him.") +
                                 [ { text: "My father's fever won't break. The temple's out of remedies.", item: "remedy" },
                                   { text: "A snake got my dog. I need an antidote, and quickly.", item: "antidote" },
                                   { text: "My eyes are going. A drop of the good stuff would help.", item: "eye_drops" },
                                   { text: "I've lost my voice, and the choir sings on Sunday.", item: "echo_screen" },
                                   { text: "My wife is laid up with a wound that won't close.", item: "hi_potion" },
                                   { text: "I promised my brother a feather that brings you back.", item: "phoenix_down" } ] },
      # Offered to the GM on each arrival, the one that fits the moment best
      # (Campaign::Remarks). Facts: the generation book's "What rows can ask
      # about" page.
      arrivals: { name: "Arrivals", kind: "arrivals",
                  entries: [ { text: "{place}. The road ends here, for now." },
                             { text: "{place} again. The same dogs bark at the same gate.", when: "town, visits >= 2" },
                             { text: "Smoke from the chimneys of {place}, and somebody frying onions.", when: "town, first_visit, day" },
                             { text: "{place} at dawn: shutters banging open, a baker already shouting.", when: "town, dawn" },
                             { text: "Lamps going on in {place}, one window at a time.", when: "town, dusk" },
                             { text: "{place} is asleep. One window is lit, and someone in it watches the road.", when: "town, night, !watcher_seen", sets: "watcher_seen" },
                             { text: "The lit window in {place} again. Whoever it is, they waited up.", when: "town, night, watcher_seen" },
                             { text: "People in {place} stop talking as the party passes. They know the name.", when: "town, standing = heroes" },
                             { text: "A child in {place} runs ahead to tell everyone who's coming. Nobody runs to greet them.", when: "town, reputation <= -1" },
                             { text: "{home} slows down at the gate of {place}. Nothing's changed, and everything has.", when: "town, first_visit" },
                             { text: "They limp into {place}. Somebody points them to the temple without being asked.", when: "town, hurt >= 2" },
                             { text: "The air at the mouth of {place} is {cold|stale|wet} and smells of old iron.", when: "dungeon, first_visit" },
                             { text: "{place} is quiet now. Water drips where the noise used to be.", when: "dungeon, cleared" },
                             { text: "The wind across {place} has teeth in it after dark.", when: "wilds, dark" },
                             { text: "{place}. Someone has left flowers here, not long ago.", when: "landmark, first_visit" },
                             { text: "A child in {place} is playing with a coin too old and too cold to be hers.", when: "town, goblin_silver >= 1, !goblin_silver_known" } ] },
      # The GM's moves when a check fails (Campaign::Remarks): the best soft
      # one (words) and the best hard one (what it takes) are offered.
      complications: { name: "Complications", kind: "complications",
                       entries: [ { text: "Something shifts in the dark beyond the light. It isn't the wind." },
                                  { text: "{who} hears it too late: the sound of someone else who wanted this first.", when: "failed >= 2" },
                                  { text: "It goes wrong, and in going wrong shows {who} a way nobody meant them to see. It won't be cheap.", when: "!dungeon" },
                                  { text: "A door somewhere slams. Whatever lives here knows they've come.", when: "dungeon" },
                                  { text: "{who} was seen. By the time anyone thinks to look, the watcher has gone to tell someone.", when: "skill = stealth, town" },
                                  { text: "The lock holds, and the pick snaps in it. Now there's a reason to come back with the right key.", when: "skill = thievery" },
                                  { text: "The page {who} needed has been torn out, recently, and carefully.", when: "skill = lore" },
                                  { text: "They smile and agree, and {who} realises too late that they agreed to nothing.", when: "skill = persuasion" },
                                  { text: "The ground goes out from under {who}.", when: "skill = athletics", does: "hurt 10" },
                                  { text: "It takes everything they have, and then a little more.", when: "skill = endurance", does: "weary 25" },
                                  { text: "The trail doubles back on itself. Hours go by before anyone admits it.", when: "skill = survival", does: "time 1" },
                                  { text: "A purse is lighter than it was. Nobody saw a thing.", when: "town", does: "lose 50" },
                                  { text: "Word gets around. Whatever's coming is coming faster now.", does: "tick" },
                                  { text: "The noise carries. Something answers it.", when: "dungeon", does: "ambush" },
                                  { text: "{who} pays for it in blood, a little.", does: "hurt 10" } ] },
      # What happens at camp or on the road (Campaign::Remarks): offered to
      # the GM, who can put its choice to the table. Each option costs
      # something the other doesn't.
      events: { name: "Camp and road", kind: "events",
                entries: [ { text: "A stranger walks out of the dark and asks to share the fire. She's soaked through and won't give a name.",
                             when: "camp, !stranger_met", sets: "stranger_met",
                             choices: "Let her sit: give potion, rumour | Send her on her way: tick -> shared_the_fire" },
                           { text: "The woman from the fire is waiting at the fork. She says she owes them, and she knows a way round.",
                             when: "road, shared_the_fire = Let her sit, !stranger_repaid", sets: "stranger_repaid",
                             choices: "Take her way: safe road, time 1 | Thank her and go on: exp 20 -> took_her_way" },
                           { text: "Whoever was turned away from the fire was seen again, further on, talking to men with lanterns.",
                             when: "road, shared_the_fire = Send her on her way" },
                           { text: "{hurt_one} can't keep up. Somebody has to say it.", when: "road, hurt_one",
                             choices: "Slow down: time 1, restore 25 | Push on: hurt 10, exp 20 -> pushed_on" },
                           { text: "{tied} dreams of {tied_to}, and wakes sure something is wrong.", when: "camp, tied" },
                           { text: "A cart in the ditch, a wheel off, and a family with nowhere to sleep.", when: "road, !cart_helped", sets: "cart_helped",
                             choices: "Help them: time 1, money 30 | Leave them: tick -> helped_the_cart" },
                           { text: "Somebody's been through the packs in the night.", when: "camp, gil >= 50",
                             choices: "Go after them: ambush, money 50 | Let it go: lose 30" },
                           { text: "A sick traveller begs at the roadside for a remedy.", when: "road",
                             choices: "Give one: give remedy, exp 30 | Walk past: tick -> fed_the_sick" },
                           { text: "The innkeeper leans in: there's a man asking after the party by name.", when: "inn",
                             choices: "Find out who: rumour, lose 20 | Leave before dawn: time 1 -> asked_after" },
                           { text: "The fire burns low. Somebody tells a story about home.", when: "camp" } ] },
      service_names: { name: "Service names", kind: "service_names",
                       entries: texts("The Sleepy Chocobo", "The Crossed Keys", "Last Light Inn", "The Wandering Moogle", "The Hearth & Kettle",
                                      "The Tipsy Wyvern", service: "inn") +
                                texts("Odds & Ends", "The Tinker's Cart", "Crystal Supply", "Hammer & Tongs", "The Traveller's Pack",
                                      service: "shop") +
                                texts("Adventurers' Hall", "The Compass Guild", "The Lantern Society", service: "guild") +
                                texts("Chapel of Light", "Shrine of the Four Winds", "Temple of the Quiet Flame", service: "temple") },
      buildings: { name: "Building archetypes", kind: "buildings",
                   entries: [ { text: "Inn", service: "inn", width: 90, height: 90, roof: "peak" },
                              { text: "Shop", service: "shop", width: 70, height: 70, roof: "peak" },
                              { text: "Guild", service: "guild", width: 80, height: 105, roof: "flat" },
                              { text: "Temple", service: "temple", width: 70, height: 135, roof: "dome" },
                              { text: "House", width: 50, height: 60, weight: 4 },
                              { text: "Cottage", width: 45, height: 50, roof: "peak", weight: 2 },
                              { text: "Tower", width: 36, height: 125 },
                              { text: "Warehouse", width: 95, height: 55, roof: "flat" },
                              { text: "Windmill", width: 40, height: 100, roof: "peak" } ] },
      # A port sells the second and third steps of every ladder; a village
      # the first and second (the ladders in items.rb). The fourth is found.
      shop_stock: { name: "General store stock", kind: "stock",
                    entries: %w[potion hi_potion phoenix_down smoke_pellet antidote eye_drops echo_screen remedy
                                longsword mythril_sword mythril_knife main_gauche battle_axe mythril_axe partisan mythril_spear
                                oak_staff healing_staff flame_rod mythril_rod iron_shield mythril_shield horned_helm mythril_helm
                                feathered_hat wizards_hat iron_armor mythril_armor chain_vest mythril_vest silk_robe sages_robe
                                hermes_sandals silver_bracer faerie_earring power_ring]
                               .map { |item| { item: item } } },
      village_stock: { name: "Village store stock", kind: "stock",
                       entries: [ { item: "potion", weight: 3 }, { item: "antidote", weight: 2 }, { item: "eye_drops" }, { item: "echo_screen" },
                                  { item: "smoke_pellet" }, { item: "longsword" }, { item: "mythril_knife" }, { item: "battle_axe" },
                                  { item: "partisan" }, { item: "oak_staff" }, { item: "flame_rod" }, { item: "iron_shield" },
                                  { item: "horned_helm" }, { item: "feathered_hat" }, { item: "chain_vest" }, { item: "silk_robe" },
                                  { item: "leather_armor" }, { item: "iron_armor" } ] },
      rooms: { name: "Room names", kind: "rooms",
               entries: texts("Flooded Hall", "Ossuary", "Collapsed Stair", "Crystal Chamber", "Guardroom", "Cistern",
                              "Vault", "Crossing", "Chapel", "Kennels", "Forge", "Gallery", "Well Room", "Barracks",
                              "Fungus Grotto", "Root Cellar", "Bone Pit", "Echoing Hall", "Mushroom Garden", "Larder",
                              "Shrine Room", "Broken Bridge", "Sunken Library", "Throne Room") },
      room_events: { name: "Room events", kind: "room_events",
                     entries: texts("A voice asks each of you for your name, and repeats it back wrong.",
                                    "The floor tilts. Something rolls toward the dark end of the room.",
                                    "Old bones, arranged in a careful circle. One is missing.",
                                    "A mural shows four heroes. Their faces have been scratched out.",
                                    "Wind howls through a crack in the wall, though you're far underground.",
                                    "A goblin, too scared to fight, offers to trade a secret for its life.",
                                    "A lantern still burns here. Someone lit it today.",
                                    "Fresh footprints lead in and don't lead out.",
                                    "A chest sits open and empty. The dust inside it is disturbed.",
                                    "The walls are covered in tally marks. Hundreds of them.",
                                    "A statue's eyes follow whoever holds a light.",
                                    "Water drips upward from a puddle into the ceiling.",
                                    "A skeleton in old armor clutches a note: \"Don't trust the map.\"",
                                    "Somewhere ahead, someone is humming the song from the inn.",
                                    "A sleeping monster, enormous, blocks half the room. It doesn't wake. Yet.",
                                    "The room is warm, and smells of bread.",
                                    "Carved above the door: a warning, in a language one of you almost reads.",
                                    "A mirror shows the room with one more person in it.",
                                    "The crystal dust on the floor glows where you step.",
                                    "An old campsite. The bedrolls are still warm.") },
      forks: { name: "Fork costs", kind: "forks",
               entries: texts("A rope bridge: someone must stay behind to hold it.",
                              "Poison gas: everyone who goes this way loses a tenth of their HP. (hurt 10)",
                              "A sealed door that opens only for 100 gil in the slot. (pay 100)",
                              "A narrow crawlway: no heavy armor fits through.",
                              "Rising water: the way back will be flooded behind you.",
                              "A toll-troll: it wants 60 gil, and it won't haggle. (pay 60)",
                              "Loose rock: the noise will wake whatever sleeps below. (ambush)",
                              "A dark stair: no light will burn on it.",
                              "A warded arch: it drinks the magic of everyone who passes under it. (weary 25)",
                              "Thorns: they tear at everyone who pushes through. (hurt 20)",
                              "A long climb: it takes half the day, and the party arrives spent. (2)",
                              "A silent hall: speak, and it answers with something worse.") },
      locks: { name: "Locks and keys", kind: "locks",
               entries: [ { text: "Crystal portal", key: "Blue crystal" }, { text: "Bone altar", key: "Goat's skull" },
                          { text: "Iron door", key: "Rusty key" }, { text: "Sealed coffin", key: "Grave-warden's ring" },
                          { text: "Rune wall", key: "Moon rune" }, { text: "Drawbridge winch", key: "Crank handle" },
                          { text: "Goblin gate", key: "Chief's tooth" }, { text: "Weeping statue", key: "Silver tear" },
                          { text: "Bell-rope portcullis", key: "Brass bell" }, { text: "Flooded sluice", key: "Valve wheel" } ] },
      treasure: { name: "Dungeon treasure", kind: "treasure",
                  entries: [ { item: "potion", weight: 8 }, { item: "hi_potion", weight: 4 }, { item: "phoenix_down", weight: 4 },
                             { item: "antidote", weight: 4 }, { item: "remedy", weight: 2 }, { item: "power_ring", weight: 2 }, { item: "bronze_armor", weight: 2 },
                             { item: "main_gauche", weight: 2 }, { item: "mythril_sword", weight: 2 }, { item: "healing_staff", weight: 2 },
                             { item: "mythril_vest", weight: 2 }, { item: "protect_ring", weight: 2 }, { item: "rune_blade" }, { item: "wizards_rod" },
                             { item: "aegis_shield" }, { item: "ninja_gear" },
                             { gil: 50, weight: 6 }, { gil: 120, weight: 4 }, { gil: 300, weight: 2 } ] }
    }.freeze

    # The setting's lore (Generators::Lore): what its pocket history and the
    # pasts of its places are made of. Tables like the rest, so a world
    # copied from this one can make them its own.
    LORE_NAMES = { "trades" => "Trades", "pasts" => "What dungeons were", "falls" => "How places fall", "quarrels" => "Quarrels",
                   "betrayals" => "Betrayals", "fortunes" => "Good fortune", "waters" => "Waters", "owners" => "Changing hands",
                   "sightings" => "Sightings", "raids" => "Raided roads" }.freeze
    LORE_TABLES = Generators::Lore.to_tables.to_h do |kind, entries|
      [ :"lore_#{kind}", { name: LORE_NAMES.fetch(kind), kind: kind, entries: entries } ]
    end.freeze
  end
end
