# frozen_string_literal: true

# The Grimoire: what the unfired can do, what the creatures do, and each
# archetype's lessons. Numbers follow the Base World's tuning for a
# level-5 party; the words are the valley's. (Seeds::Greenware)
module Seeds
  module Greenware
    ABILITIES = {
      # --- the small arts: one type each, single and spread --------------------------
      ember: { name: "Ember", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
               effects: [ { primitive: "elemental", type: "fire", power: 12 } ],
               description: "A coal held in the palm and thrown. The first thing a Firekeeper learns, and the hardest to put down." },
      douse: { name: "Douse", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
               effects: [ { primitive: "elemental", type: "water", power: 12 } ],
               description: "A bucket's worth of cold river, from nowhere. Greenware hates it." },
      ashfall: { name: "Ashfall", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "fade",
                 effects: [ { primitive: "elemental", type: "ash", power: 12 } ],
                 description: "Hot ash, settling. It gets in everything." },
      shard: { name: "Shard", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
               effects: [ { primitive: "elemental", type: "glass", power: 12 } ],
               description: "One sliver of the Flats, thrown edge first." },
      blaze: { name: "Blaze", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
               effects: [ { primitive: "elemental", type: "fire", power: 10 } ],
               description: "Fire down the whole line, like a firemouth opened." },
      deluge: { name: "Deluge", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
                effects: [ { primitive: "elemental", type: "water", power: 10 } ],
                description: "The slip tank, upended over everyone." },
      ash_storm: { name: "Ash Storm", kind: "magic", target: "all_enemies", mp_cost: 10, gesture: "spin",
                   effects: [ { primitive: "elemental", type: "ash", power: 10 } ],
                   description: "The woods' whole year of burning, in one breath." },
      white_heat: { name: "White Heat", kind: "magic", target: "single_enemy", mp_cost: 24, gesture: "flash",
                    effects: [ { primitive: "elemental", type: "fire", power: 40 } ],
                    description: "Cone ten and past it: the heat a kiln reaches once, at the end. The Firekeeper's last lesson." },
      gold_line: { name: "Gold Line", kind: "magic", target: "single_enemy", mp_cost: 24, gesture: "flash",
                   effects: [ { primitive: "elemental", type: "glass", power: 38 } ],
                   description: "A seam of molten gold, laid along a foe instead of a crack. The Mender's last lesson, and not a kind one." },
      # --- mending ----------------------------------------------------------------------
      slake: { name: "Slake", kind: "magic", target: "single_ally", mp_cost: 4, gesture: "float",
               effects: [ { primitive: "heal", power: 25 } ],
               description: "Wet the clay and work the crack closed. The first mending." },
      slurry: { name: "Slurry", kind: "magic", target: "all_allies", mp_cost: 9, gesture: "float",
                effects: [ { primitive: "heal", power: 18 } ],
                description: "Thin slip over everyone, filling the small cracks before they spread." },
      mend: { name: "Mend", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
              effects: [ { primitive: "cleanse" } ],
              description: "Lifts every affliction from one ally: the crazing, the warp, the cold." },
      gold_seam: { name: "Gold Seam", kind: "magic", target: "single_ally", mp_cost: 10, gesture: "pop",
                   effects: [ { primitive: "revive", fraction: 25 } ],
                   description: "Gold along the break, the old way. A fallen ally stands, and is more beautiful for it." },
      gold_flood: { name: "Gold Flood", kind: "magic", target: "all_allies", mp_cost: 16, gesture: "float",
                    effects: [ { primitive: "heal", power: 32 } ],
                    description: "Gold runs into every crack in the party at once." },
      breathe: { name: "Breathe", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
                 effects: [ { primitive: "heal", power: 40 }, { primitive: "cleanse" } ],
                 description: "The Wedger stops, breathes, and the clay settles back where it should be." },
      mulch: { name: "Mulch", kind: "magic", target: "all_allies", mp_cost: 8, gesture: "float",
               effects: [ { primitive: "heal", power: 20 } ],
               description: "Leaf-rot and warm ash round the party's feet, and the cracks close." },
      # --- afflictions, in the valley's words -------------------------------------
      leather_hard: { name: "Leather-Hard", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "float",
                      effects: [ { primitive: "status", kind: "sleep", chance: 70, duration: 3 } ],
                      description: "Stiffens a foe to leather-hard: standing, but not moving. A hard blow softens them again." },
      choke: { name: "Choke", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "fade",
               effects: [ { primitive: "status", kind: "silence", chance: 80, duration: 3 } ],
               description: "Shuts a foe's draft the way a damper shuts a flue. No arts come out." },
      craze: { name: "Craze", kind: "magic", target: "single_enemy", mp_cost: 6, gesture: "tint",
               effects: [ { primitive: "elemental", type: "glass", power: 12 }, { primitive: "status", kind: "poison", chance: 100, duration: 4 } ],
               description: "Fine cracks all over, like frost, and they keep going." },
      warp: { name: "Warp", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "tint",
              effects: [ { primitive: "status", kind: "confuse", chance: 60, duration: 3 } ],
              description: "Dries a foe unevenly. They can't tell their friends from their shelf." },
      cool: { name: "Cool", kind: "magic", target: "single_enemy", mp_cost: 7, gesture: "tint",
              effects: [ { primitive: "status", kind: "stop", chance: 60, duration: 2 } ],
              description: "Takes the heat out of a foe so fast they stop. A blow doesn't start them." },
      bone_dry: { name: "Bone-Dry", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "fade",
                  effects: [ { primitive: "status", kind: "paralyze", chance: 60, duration: 2 } ],
                  description: "Dries a foe past leather-hard to brittle. Moving would break them, so they don't." },
      the_firing: { name: "The Firing", kind: "magic", target: "single_enemy", mp_cost: 10, gesture: "flash",
                    effects: [ { primitive: "status", kind: "doom", chance: 50, duration: 4 } ],
                    description: "The Kilnmaster's word: your name is on the list, and the heat is coming. A countdown, and at the end of it you are finished." },
      spin_up: { name: "Spin Up", kind: "magic", target: "single_ally", mp_cost: 8, gesture: "spin",
                 effects: [ { primitive: "status", kind: "haste", chance: 100, duration: 3 } ],
                 description: "The wheel under an ally goes faster: a second go at the end of each round, the same move again." },
      glaze_coat: { name: "Glaze Coat", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
                    effects: [ { primitive: "shield", power: 8, duration: 4 } ],
                    description: "A skin of raw glaze that takes the next blows before they reach the body." },
      hot_hands: { name: "Hot Hands", kind: "magic", target: "self", mp_cost: 4, gesture: "flash",
                   effects: [ { primitive: "imbue", type: "fire", duration: 3 } ],
                   description: "Your hands go kiln-hot: your Attack strikes as fire for a while." },
      wet_hands: { name: "Wet Hands", kind: "magic", target: "self", mp_cost: 4, gesture: "flash",
                   effects: [ { primitive: "imbue", type: "water", duration: 3 } ],
                   description: "Your hands run with slip: your Attack strikes as water for a while." },
      wick: { name: "Wick", kind: "magic", target: "single_enemy", mp_cost: 0, gesture: "tint",
              effects: [ { primitive: "sap", power: 16, keep: 100 } ],
              description: "Draws a foe's slip up into your own, like water into a dry pot." },
      settle: { name: "Settle", kind: "magic", target: "single_enemy", mp_cost: 9, gesture: "shake",
                effects: [ { primitive: "percent", power: 25, chance: 80 } ],
                description: "A quarter of whatever a foe has left slumps off it, whatever its armour. It never finishes anyone, and bosses barely notice." },
      draw_off: { name: "Draw Off", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "tint",
                  effects: [ { primitive: "drain", power: 14 } ],
                  description: "Takes the water out of a foe and puts it in you." },
      # --- the body's arts ------------------------------------------------------------
      twice_round: { name: "Twice Round", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 60, hits: 2 } ],
                     description: "Two blows in the time of one turn of the wheel." },
      stoke_up: { name: "Stoke Up", kind: "skill", target: "self", mp_cost: 2, gesture: "shake",
                  effects: [ { primitive: "buff", stat: "str", amount: 50, duration: 3 }, { primitive: "buff", stat: "atk", amount: 50, duration: 3 } ],
                  description: "A breath taken the way a kiln takes one: everything in you burns a little hotter." },
      chip: { name: "Chip", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "lunge",
              effects: [ { primitive: "physical", power: 80 }, { primitive: "debuff", stat: "def", amount: 50, duration: 3 } ],
              description: "A blow at the rim, where it's thinnest. What's chipped breaks easier." },
      sweep: { name: "Sweep", kind: "skill", target: "all_enemies", mp_cost: 3, gesture: "spin",
               effects: [ { primitive: "physical", power: 45 } ],
               description: "A low sweep that takes every foe's feet, if none of them is heavy." },
      kiln_smoke: { name: "Kiln Smoke", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
                    effects: [ { primitive: "escape" } ],
                    description: "A handful of wet sawdust on a coal, and nobody sees which way you went. Guarantees an escape, if escape is possible at all." },
      palm: { name: "Palm", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
              effects: [ { primitive: "steal", chance: 50 } ],
              description: "Lifts something from a foe: one of the things it would drop. Quicker hands, better odds." },
      pocket: { name: "Pocket", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                effects: [ { primitive: "steal", chance: 90 } ],
                description: "Hands so quick the pocket is empty before it's missed." },
      read_the_cone: { name: "Read the Cone", kind: "magic", target: "single_enemy", mp_cost: 1, gesture: "float",
                       effects: [ { primitive: "scan" } ],
                       description: "Reads a foe like a bent cone: its Body, what it's weak to, what it shrugs off. The party remembers." },
      into_the_racks: { name: "Into the Racks", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
                        effects: [ { primitive: "away", who: "self", duration: 1 } ],
                        description: "One more pot among a thousand until your next turn: nothing can reach you, then you're back to act." },
      overfire: { name: "Overfire", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
                  effects: [ { primitive: "status", kind: "berserk", chance: 100, duration: 3 } ],
                  description: "Past cone ten and still stoking. You attack on your own, harder, until it passes." },
      bat_shove: { name: "Bat Shove", kind: "skill", target: "single_enemy", mp_cost: 3, gesture: "lunge",
                   effects: [ { primitive: "physical", power: 60 }, { primitive: "away", who: "target", duration: 1, chance: 60 } ],
                   description: "A wheel bat in both hands, and a foe sent reeling off the field for a turn." },
      grudge: { name: "Grudge", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                effects: [ { primitive: "physical", power: 90, grudge: 200 } ],
                description: "Every crack paid back: the nearer you are to breaking, the harder it lands." },
      stand_firm: { name: "Stand Firm", kind: "skill", target: "all_allies", mp_cost: 6, gesture: "shake",
                    effects: [ { primitive: "buff", stat: "def", amount: 50, duration: 3 } ],
                    description: "Everyone stands a little behind the Thrower, and it helps." },
      wheel_oath: { name: "Wheel Oath", kind: "skill", target: "single_enemy", mp_cost: 10, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 260 } ],
                    description: "The Thrower's last lesson: one blow with the whole wheel's weight behind it." },
      shard_dance: { name: "Shard Dance", kind: "skill", target: "single_enemy", mp_cost: 8, gesture: "spin",
                     effects: [ { primitive: "physical", type: "glass", power: 70, hits: 4 } ],
                     description: "Four cuts from four places at once. The Shardwalker's last lesson." },
      final_press: { name: "Final Press", kind: "skill", target: "single_enemy", mp_cost: 10, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "clay", power: 320 } ],
                     description: "Everything the Wedger has pressed into the clay, pressed into one foe." },
      # --- the colliers' land arts -----------------------------------------------------
      cinder_pit: { name: "Cinder Pit", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "shake",
                    effects: [ { primitive: "elemental", type: "ash", power: 16 } ],
                    description: "The turf gives, and a foe is in last year's burning." },
      ash_cloud: { name: "Ash Cloud", kind: "magic", target: "all_enemies", mp_cost: 6, gesture: "spin",
                   effects: [ { primitive: "elemental", type: "ash", power: 12 }, { primitive: "status", kind: "blind", chance: 40, duration: 3 } ],
                   description: "A stack kicked open. Nobody sees for a while." },
      lye: { name: "Lye", kind: "magic", target: "all_enemies", mp_cost: 8, gesture: "flash",
             effects: [ { primitive: "elemental", type: "water", power: 14 }, { primitive: "status", kind: "slow", chance: 40, duration: 3 } ],
             description: "Rainwater through ash: it eats, and it clings." },
      kiln_quake: { name: "Kiln Quake", kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "shake",
                    effects: [ { primitive: "elemental", type: "clay", power: 16 } ],
                    description: "The ground remembers being clay, and moves." },
      ash_wrath: { name: "Ash Wrath", kind: "magic", target: "all_enemies", mp_cost: 26, gesture: "shake",
                   effects: [ { primitive: "elemental", type: "ash", power: 30 } ],
                   description: "Every fire the woods ever fed, come back at once. The Collier's last lesson." },
      brine_rain: { name: "Brine Rain", kind: "magic", target: "all_enemies", mp_cost: 18, gesture: "flash",
                    effects: [ { primitive: "elemental", type: "water", power: 18 } ],
                    description: "Salt water falling on everything, and everything it falls on going white. The Salter's last lesson." },
      # --- signature commands: each archetype's own, always on its menu ------------
      muck_in: { name: "Muck In", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "shake",
                 effects: [ { primitive: "buff", stat: "str", amount: 25, duration: 3 }, { primitive: "buff", stat: "atk", amount: 25, duration: 3 } ],
                 description: "Sleeves up, everyone. A shout that lifts every arm a little. The Greenhand's own command." },
      centre: { name: "Centre", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
                effects: [ { primitive: "status", kind: "aggro", chance: 100, duration: 2 } ],
                description: "Take the middle of the wheel until your next turn: the enemy's single blows land on you instead. The Thrower's own command." },
      stoke: { name: "Stoke", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
               effects: [ { primitive: "status", kind: "charged", chance: 100, duration: 3 } ],
               description: "Feed the fire and wait: the next art lands twice as hard, for the same Slip. The Firekeeper's own command." },
      patch: { name: "Patch", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "float",
               effects: [ { primitive: "heal", power: 6 } ],
               description: "A wet sponge over everyone's small cracks, for free. The Mender's own command." },
      lift: { name: "Lift", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
              effects: [ { primitive: "physical", power: 60 }, { primitive: "steal", chance: 40 } ],
              description: "Hit them, and help yourself on the way past. The Shardwalker's own command." },
      cast_slip_cat: { name: "Cast Slip Cat", kind: "magic", target: "self", mp_cost: 12, gesture: "pop",
                       effects: [ { primitive: "summon", creature: "slip_cat" } ],
                       description: "A cat poured from slip, quick and cold. It pounces once and runs back into the bucket. The Slipcaster's own command." },
      knead: { name: "Knead", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "status", kind: "charged", chance: 100, duration: 3 } ],
               description: "Work the clay in your own arms until it's even: the next blow lands twice as hard. The Wedger's own command." },
      rake_the_ash: { name: "Rake the Ash", kind: "skill", target: "all_enemies", mp_cost: 4, gesture: "flash",
                      effects: [ { primitive: "elemental", type: "terrain", power: 12 } ],
                      description: "The ground itself answers, in the type of wherever you're fighting. The Collier's own command." },
      salt_glaze: { name: "Salt Glaze", kind: "magic", target: "self", mp_cost: 3, gesture: "flash",
                    effects: [ { primitive: "imbue", type: "glass", duration: 3 } ],
                    description: "Salt thrown on your own heat: a glass skin on your hands, and your Attack cuts as glass for a while. The Salter's own command." },
      # --- small summons: a creature comes, does one thing, and goes ----------------
      call_ash_moth: { name: "Call Ash Moth", kind: "magic", target: "self", mp_cost: 5, gesture: "pop",
                       effects: [ { primitive: "summon", creature: "ash_moth" } ], description: "A moth the colour of a cold stack. Everything it brushes goes grey." },
      call_glass_finch: { name: "Call Glass Finch", kind: "magic", target: "self", mp_cost: 7, gesture: "pop",
                          effects: [ { primitive: "summon", creature: "glass_finch" } ], description: "A finch off the Flats, all edges. It goes for the eyes." },
      call_kiln_hound: { name: "Call Kiln Hound", kind: "magic", target: "self", mp_cost: 9, gesture: "pop",
                         effects: [ { primitive: "summon", creature: "kiln_hound" } ], description: "A dog made of firebrick, still warm from the last firing." },
      call_clay_tortoise: { name: "Call Clay Tortoise", kind: "magic", target: "self", mp_cost: 14, gesture: "pop",
                            effects: [ { primitive: "summon", creature: "clay_tortoise", duration: 3 } ],
                            description: "An old tortoise of unfired clay stays a while and wards the party each turn." },
      call_slip_eel: { name: "Call Slip Eel", kind: "magic", target: "self", mp_cost: 20, gesture: "pop",
                       effects: [ { primitive: "summon", creature: "slip_eel", duration: 2 } ],
                       description: "Something long from the bottom of the slip tank coils round the fight for two turns." },
      call_bottle_wyrm: { name: "Call Bottle Wyrm", kind: "magic", target: "self", mp_cost: 30, gesture: "pop",
                          effects: [ { primitive: "summon", creature: "bottle_wyrm", duration: 2 } ],
                          description: "The thing that lives in a bottle kiln's crown comes down for two turns. The Slipcaster's last lesson." },
      # --- what the creatures do ------------------------------------------------------
      pounce: { name: "Pounce", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                effects: [ { primitive: "physical", type: "clay", power: 180 } ], description: "Cold, wet, and all claws." },
      dust: { name: "Dust", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "tint",
              effects: [ { primitive: "elemental", type: "ash", power: 12 }, { primitive: "status", kind: "blind", chance: 30, duration: 2 } ],
              description: "Wing-dust, grey and fine." },
      peck: { name: "Peck", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
              effects: [ { primitive: "physical", type: "glass", power: 180 } ], description: "A beak like a cut." },
      fire_breath: { name: "Fire Breath", kind: "magic", target: "single_enemy", mp_cost: 0, gesture: "flash",
                     effects: [ { primitive: "elemental", type: "fire", power: 30 } ], description: "A long, hot breath." },
      shell_ward: { name: "Shell Ward", kind: "magic", target: "all_allies", mp_cost: 0, gesture: "float",
                    effects: [ { primitive: "shield", power: 5, duration: 2 } ], description: "The tortoise's patience, spread thin over everyone." },
      eel_coil: { name: "Eel Coil", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "shake",
                  effects: [ { primitive: "elemental", type: "water", power: 18 } ], description: "Slip, and the weight of the eel in it." },
      bottle_breath: { name: "Bottle Breath", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "flash",
                       effects: [ { primitive: "elemental", type: "fire", power: 26 } ], description: "The crown of a kiln, breathed out." },
      slip_slap: { name: "Slip Slap", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                   effects: [ { primitive: "physical", power: 150 } ], description: "An unreasonably heavy wet slap from an unreasonably small creature." },
      craze_bite: { name: "Craze Bite", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", type: "glass", power: 80 }, { primitive: "status", kind: "poison", chance: 60, duration: 3 } ],
                    description: "A bite that leaves fine cracks, and the cracks keep going." },
      pack_bay: { name: "Pack Bay", kind: "skill", target: "all_allies", mp_cost: 0, gesture: "shake",
                  effects: [ { primitive: "buff", stat: "agi", amount: 30, duration: 3 } ], description: "The pack runs faster together." },
      cold_strike: { name: "Cold Strike", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "water", power: 120 } ], description: "A blow from something that was never warm." },
      spout: { name: "Spout", kind: "magic", target: "single_enemy", mp_cost: 3, gesture: "flash",
               effects: [ { primitive: "elemental", type: "water", power: 14 } ], description: "A jug that leaks on purpose." },
      kiln_fall: { name: "Kiln Fall", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                   effects: [ { primitive: "physical", type: "fire", power: 180 } ], description: "A firebrick wall's whole weight in one fall. Every third round: be ready." },
      tongs: { name: "Tongs", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
               effects: [ { primitive: "physical", type: "fire", power: 150 } ], description: "Kiln tongs, red at the tips, closing." },
      shatter_arm: { name: "Shatter Arm", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", type: "glass", power: 120 } ], description: "An arm of the Flats, swung, and breaking as it lands." },
      glass_breath: { name: "Glass Breath", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                      effects: [ { primitive: "elemental", type: "glass", power: 22 } ], description: "A storm of slivers across the whole party. Armour helps; soft clay doesn't." },
      swallow: { name: "Swallow", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                 effects: [ { primitive: "physical", type: "clay", power: 180 } ], description: "The slip opens, and closes. Every third round, on whoever looks weakest." },
      wrong_note: { name: "Wrong Note", kind: "magic", target: "single_enemy", mp_cost: 2, gesture: "tint",
                    effects: [ { primitive: "elemental", type: "bone", power: 14 } ], description: "A note sung a little off, and it goes through you." },
      bone_note: { name: "Bone Note", kind: "magic", target: "single_enemy", mp_cost: 6, gesture: "tint",
                   effects: [ { primitive: "elemental", type: "bone", power: 26 } ], description: "One note, held, from something that has been holding it a century." },
      the_song: { name: "The Song", kind: "magic", target: "all_enemies", mp_cost: 8, gesture: "float",
                  effects: [ { primitive: "status", kind: "sleep", chance: 50, duration: 2 } ],
                  description: "The Choir's part for the living: it goes leather-hard in the ears, and then everywhere else." },
      # --- field abilities: an archetype's move outside battle, once per rest -------
      odd_jobs: { name: "Odd Jobs", kind: "field", field_skill: "hands", field_outcome: "find", field_difficulty: "easy", field_power: 100,
                  effects: [], description: "There's always a shelf to turn or a barrow to push, and someone pays in something." },
      shoulder_the_door: { name: "Shoulder the Door", kind: "field", field_skill: "heft", field_outcome: "sneak", field_difficulty: "hard",
                           effects: [], description: "Whatever waits on the road, a kiln door shut in its face makes it think again." },
      read_the_draft: { name: "Read the Draft", kind: "field", field_skill: "firing", field_outcome: "learn", field_difficulty: "normal",
                        effects: [], description: "Hold a wet finger up: what's waiting on the road, and what it's weak to, known before the fight." },
      field_mend: { name: "Field Mend", kind: "field", field_skill: "reading", field_outcome: "restore", field_difficulty: "easy", field_power: 40,
                    effects: [], description: "A sponge, a little gold, a quiet word: everyone standing gets some of their strength back." },
      slip_the_latch: { name: "Slip the Latch", kind: "field", field_skill: "hands", field_outcome: "story", field_difficulty: "normal",
                        effects: [], description: "A door, a shelf-lock, a Guild seal. What's behind it is the GM's to tell." },
      send_the_cat: { name: "Send the Cat", kind: "field", field_skill: "roadcraft", field_outcome: "reveal", field_difficulty: "normal",
                      effects: [], description: "The slip cat runs ahead and comes back with what's near in its eyes." },
      sit_still: { name: "Sit Still", kind: "field", field_skill: "standing", field_outcome: "restore", field_difficulty: "normal", field_power: 25,
                   effects: [], description: "The Wedger sits, and everyone sits, and a quarter of everyone's Body and Slip comes back." },
      read_the_land: { name: "Read the Land", kind: "field", field_skill: "roadcraft", field_outcome: "safe_road", field_difficulty: "normal",
                       effects: [], description: "Find the way the land wants you to go: the next dangerous path is safe." },
      talk_the_price: { name: "Talk the Price", kind: "field", field_skill: "haggling", field_outcome: "sneak", field_difficulty: "normal",
                        effects: [], description: "Everything in the valley has a price, including the thing on the road. Talk your way past it." },
      # --- desperation moves: never learned, found; at a quarter Body or less -------
      last_push: { name: "Last Push", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                   effects: [ { primitive: "physical", power: 220 } ],
                   description: "Everything, in one shove. A Greenhand's desperation move." },
      collapse_the_wall: { name: "Collapse the Wall", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                           effects: [ { primitive: "physical", type: "clay", power: 130 } ],
                           description: "The Thrower brings a wall of wet clay down across the whole line. A desperation move." },
      blowout: { name: "Blowout", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                 effects: [ { primitive: "elemental", type: "fire", power: 45 } ],
                 description: "What happened at the Second Kiln, small. A Firekeeper's desperation move." },
      shatter: { name: "Shatter", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
                 effects: [ { primitive: "elemental", type: "glass", power: 26 }, { primitive: "status", kind: "blind", chance: 50, duration: 3 } ],
                 description: "Every seam the Mender ever closed, opened at once in the enemy. A desperation move." },
      thousand_shards: { name: "Thousand Shards", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "fade",
                         effects: [ { primitive: "physical", type: "glass", power: 75, hits: 4 } ],
                         description: "Not quite a thousand. A Shardwalker's desperation move." },
      flood: { name: "Flood", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "flash",
               effects: [ { primitive: "elemental", type: "water", power: 45 } ],
               description: "Every slip tank in the valley, answering at once. A Slipcaster's desperation move." },
      hundred_slaps: { name: "Hundred Slaps", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "shake",
                       effects: [ { primitive: "physical", type: "clay", power: 50, hits: 6 } ],
                       description: "Wedging, done to a person. A Wedger's desperation move." },
      kiln_collapse: { name: "Kiln Collapse", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "shake",
                       effects: [ { primitive: "elemental", type: "terrain", power: 30 } ],
                       description: "The whole land turns on them. A Collier's desperation move." },
      brine_storm: { name: "Brine Storm", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "spin",
                     effects: [ { primitive: "elemental", type: "water", power: 20, hits: 3 } ],
                     description: "Salt and water and glass, three times over. A Salter's desperation move." }
    }.freeze
  end
end
