# frozen_string_literal: true

# The Bestiary: what's met on the towpaths and in the pits, the misfired,
# the bosses, and what a Slipcaster pours. (Seeds::Greenware)
module Seeds
  module Greenware
    MONSTERS = {
      # Poured, not met: the Slipcaster's creatures (the summon primitive).
      slip_cat: { name: "Slip Cat", level: 3, stats: stats(max_hp: 40, str: 14, atk: 10, agi: 30, def: 2, mdef: 2), base_type: "clay",
                  exp: 0, gil: 0, abp: 0, ai_script: [ { use: "pounce" } ], description: "Poured from a bucket. Pounces once, and runs back in." },
      ash_moth: { name: "Ash Moth", level: 3, stats: stats(max_hp: 30, mag: 16, agi: 20, mdef: 8), base_type: "ash",
                  exp: 0, gil: 0, abp: 0, ai_script: [ { use: "dust" } ], description: "The colour of a cold stack. Don't breathe in." },
      glass_finch: { name: "Glass Finch", level: 5, stats: stats(max_hp: 60, str: 18, atk: 12, agi: 26, def: 4, mdef: 6), base_type: "glass",
                     exp: 0, gil: 0, abp: 0, ai_script: [ { use: "peck" } ], description: "All edges. It goes for the eyes." },
      kiln_hound: { name: "Kiln Hound", level: 5, stats: stats(max_hp: 60, mag: 20, agi: 12, def: 4, mdef: 6), base_type: "fire",
                    exp: 0, gil: 0, abp: 0, ai_script: [ { use: "fire_breath" } ], description: "Firebrick, and still warm. Don't pat it." },
      clay_tortoise: { name: "Clay Tortoise", level: 10, stats: stats(max_hp: 200, mag: 18, agi: 4, def: 30, mdef: 20), base_type: "clay",
                       exp: 0, gil: 0, abp: 0, ai_script: [ { use: "shell_ward" } ], description: "Unfired for a hundred years and in no hurry to be." },
      slip_eel: { name: "Slip Eel", level: 15, stats: stats(max_hp: 160, mag: 26, agi: 14, def: 8, mdef: 10), base_type: "water",
                  exp: 0, gil: 0, abp: 0, ai_script: [ { use: "eel_coil" } ], description: "Lives at the bottom of the slip tank. Owes the Slipcaster a favour." },
      bottle_wyrm: { name: "Bottle Wyrm", level: 25, stats: stats(max_hp: 260, mag: 34, agi: 22, def: 12, mdef: 12), base_type: "fire",
                     exp: 0, gil: 0, abp: 0, ai_script: [ { use: "bottle_breath" } ], description: "Lives in the crown of a bottle kiln. Answers only a master's call." },

      # --- the towpaths and pits ---------------------------------------------------------
      slip_hound: { name: "Slip Hound", level: 1, stats: stats(max_hp: 81, str: 12, atk: 11, agi: 8, def: 3, mdef: 2),
                    base_type: "clay", exp: 30, gil: 30, abp: 2,
                    ai_script: [ { if: { chance: 25 }, use: "slip_slap" }, { use: "attack" } ],
                    drops: [ { item: "slip_pot", chance: 30 } ],
                    description: "A dog's shape the slip took and kept. Small, wet, and far braver in packs." },
      grog_beetle: { name: "Grog Beetle", level: 2, stats: stats(max_hp: 63, str: 11, atk: 12, agi: 22, def: 1, mdef: 2),
                     base_type: "glass", exp: 36, gil: 15, abp: 2,
                     ai_script: [ { if: { chance: 40 }, use: "craze_bite", target: "lowest_hp" }, { use: "attack" } ],
                     description: "A beetle with a shell of fired grit. The clicking arrives before it does." },
      collier_hound: { name: "Collier's Hound", level: 2, stats: stats(max_hp: 108, str: 15, atk: 14, agi: 16, def: 3, mdef: 3),
                       base_type: "ash", exp: 45, gil: 20, abp: 2,
                       ai_script: [ { if: { round_multiple: 3 }, use: "pack_bay" }, { if: { chance: 30 }, use: "craze_bite" }, { use: "attack" } ],
                       drops: [ { item: "slip_pot", chance: 25 } ],
                       description: "Ran off from the colliers' camps and runs the woods now, with ash in its coat." },
      cinder_imp: { name: "Cinder Imp", level: 2, stats: stats(max_hp: 90, max_mp: 20, mag: 16, str: 8, atk: 10, agi: 14, def: 2, mdef: 6),
                    base_type: "fire", exp: 48, gil: 25, abp: 2,
                    ai_script: [ { if: { chance: 60 }, use: "ember" }, { use: "attack" } ],
                    drops: [ { item: "slip_pot", chance: 20 } ],
                    description: "A coal that got up and walked out of the stack. Likes to be looked at." },
      crazed_jug: { name: "Crazed Jug", level: 2, stats: stats(max_hp: 126, max_mp: 20, mag: 19, atk: 8, agi: 6, def: 60, mdef: 0),
                    base_type: "water", exp: 63, gil: 40, abp: 3,
                    ai_script: [ { if: { chance: 50 }, use: "spout" }, { use: "attack" } ],
                    description: "A jug, crazed all over, that leaks on purpose. Paddles bounce off. Bring a Firekeeper." },
      glass_wasp: { name: "Glass Wasp", level: 2, stats: stats(max_hp: 70, str: 12, atk: 12, agi: 24, def: 1, mdef: 3),
                    base_type: "glass", exp: 40, gil: 18, abp: 2,
                    ai_script: [ { if: { chance: 40 }, use: "craze_bite", target: "lowest_hp" }, { use: "attack" } ],
                    description: "Nests in the Flats. You hear it like a glass rim rubbed." },
      salt_eel: { name: "Salt Eel", level: 3, stats: stats(max_hp: 135, max_mp: 30, mag: 20, str: 9, atk: 7, agi: 14, def: 3, mdef: 8),
                  base_type: "water", exp: 57, gil: 45, abp: 3,
                  ai_script: [ { if: { self_hp_below: 40 }, use: "slake", target: "self" }, { if: { chance: 60 }, use: "spout" }, { use: "attack" } ],
                  drops: [ { item: "grog_paste", chance: 15 } ],
                  description: "Lives in the flooded pans, crusted white. Doesn't like to be looked at." },
      misfire: { name: "Misfire", level: 3, stats: stats(max_hp: 187, str: 16, atk: 16, agi: 4, def: 4, mdef: 1),
                 base_type: "bone", undead: true, status_immune: %w[poison sleep], exp: 72, gil: 50, abp: 3,
                 ai_script: [ { if: { chance: 30 }, use: "wrong_note" }, { use: "attack", target: "lowest_hp" } ],
                 description: "Someone who came out of the fire wrong: slumped, half-glazed, shelved. Slow, relentless, and finished." },
      bone_china_doll: { name: "Bone China Doll", level: 3, stats: stats(max_hp: 144, str: 18, atk: 16, agi: 9, def: 5, mdef: 3),
                         base_type: "bone", undead: true, status_immune: %w[poison sleep], exp: 60, gil: 35, abp: 3,
                         ai_script: [ { if: { chance: 35 }, use: "cold_strike" }, { use: "attack" } ],
                         drops: [ { item: "menders_gold", chance: 10 } ],
                         description: "Fired thin and white in the Great Kiln's first years, and never put down. It remembers how to hold a knife." },
      shard_golem: { name: "Shard Golem", level: 4, stats: stats(max_hp: 306, str: 20, atk: 19, agi: 6, def: 6, mdef: 4),
                     base_type: "glass", affinities: { glass: "absorb" }, exp: 105, gil: 75, abp: 4,
                     ai_script: [ { if: { chance: 35 }, use: "shatter_arm" }, { use: "attack", target: "highest_hp" } ],
                     drops: [ { item: "menders_gold", chance: 10 } ],
                     description: "Rises out of the Flats when something soft walks over it. Every blow of glass it takes, it keeps." },
      firebrick_golem: { name: "Firebrick Golem", level: 5, stats: stats(max_hp: 360, str: 22, atk: 21, agi: 5, def: 14, mdef: 6),
                         base_type: "fire", status_immune: %w[sleep], exp: 130, gil: 90, abp: 4,
                         ai_script: [ { if: { round_multiple: 3 }, use: "kiln_fall", target: "lowest_hp" }, { use: "attack" } ],
                         description: "A bag wall that stood up. Every third round it falls on whoever looks weakest: be ready." },
      kiln_warden: { name: "Kiln Warden", level: 6, stats: stats(max_hp: 420, max_mp: 40, str: 20, mag: 20, atk: 19, agi: 10, def: 8, mdef: 8),
                     base_type: "fire", exp: 160, gil: 120, abp: 5,
                     ai_script: [ { if: { chance: 30 }, use: "blaze" }, { if: { chance: 30 }, use: "tongs" }, { use: "attack" } ],
                     drops: [ { item: "firebrick_helm", chance: 15 } ],
                     description: "The Guild's fired men, with tongs and a loading list. Perfect, and they'll tell you so." },

      # --- bosses ----------------------------------------------------------------------
      pit_mother: { boss: true, boss_line: "You dug me up. Every one of you, out of me. Come home.", name: "The Pit Mother", level: 4,
                    stats: stats(max_hp: 520, max_mp: 12, str: 18, atk: 17, agi: 10, def: 7, mdef: 5, mag: 13),
                    base_type: "clay", affinities: { water: "absorb", fire: "resist", glass: "resist" }, exp: 128, gil: 150, abp: 4,
                    ai_script: [ { if: { self_hp_below: 30 }, use: "slake", target: "self" },
                                { if: { round_multiple: 3 }, use: "swallow", target: "lowest_hp" }, { use: "attack" } ],
                    drops: [ { item: "ironwood_paddle", chance: 15 } ],
                    variant: { hue: 20, scale: 140 },
                    description: "The slip at the bottom of the Harrow galleries, with a shape and a wish. Water feeds it; fire only steams off it, and glass sinks in. Every third round it swallows whoever looks weakest. A boss for a party of about level 5." },
      choirmaster: { boss: true, boss_line: "We were fired wrong, and we sing right. Stay. Learn your part.", name: "The Choirmaster", level: 6,
                     stats: stats(max_hp: 312, max_mp: 60, str: 8, mag: 26, spr: 16, atk: 5, agi: 12, def: 3, mdef: 12),
                     base_type: "bone", undead: true, affinities: { bone: "absorb" }, status_immune: %w[poison sleep], exp: 150, gil: 200, abp: 4,
                     ai_script: [ { if: { ally_hp_below: 40 }, use: "draw_off" }, { if: { chance: 30 }, use: "the_song" },
                                 { if: { chance: 20 }, use: "warp" }, { if: { chance: 60 }, use: "bone_note" }, { use: "wrong_note" } ],
                     drops: [ { item: "readers_hood", chance: 20 } ],
                     description: "Keeps time for the Choir in the Vaults. The Song puts the living to sleep where they stand; keep a Mender awake. A boss for a party of about level 6." },
      salt_wyrm: { boss: true, boss_line: "The works flooded and I stayed. Everything after that is salt.", name: "The Salt Wyrm", level: 7,
                   stats: stats(max_hp: 640, max_mp: 30, str: 27, mag: 10, atk: 25, agi: 7, def: 12, mdef: 6),
                   base_type: "water", status_immune: %w[sleep], exp: 364, gil: 400, abp: 8,
                   ai_script: [ { if: { self_hp_below: 30 }, use: "slake", target: "self" },
                               { if: { round_multiple: 3 }, use: "eel_coil" }, { if: { round_multiple: 4 }, use: "cool", target: "random" },
                               { use: "attack", target: "lowest_hp" } ],
                   drops: [ { item: "saggar_plate", chance: 50 }, { item: "gold_seam_ring", chance: 5 } ],
                   description: "Grew in the flooded saltworks round a glaze vat. Every third round it coils the whole party in brine. A boss for a party of about level 8." },
      kilnmaster: { boss: true, boss_line: "Forty years I kept it cold for you. Forty years of soft things breaking. No more.", name: "The Kilnmaster", level: 10,
                    stats: stats(max_hp: 1600, max_mp: 200, str: 32, mag: 30, spr: 20, atk: 30, agi: 14, def: 16, mdef: 16),
                    base_type: "fire", status_immune: %w[sleep paralyze silence poison doom], exp: 1680, gil: 2500, abp: 16,
                    ai_script: [ { if: { self_hp_below: 25, chance: 50 }, use: "slurry" },
                                { if: { round_multiple: 4 }, use: "the_firing", target: "random" }, { if: { chance: 30 }, use: "white_heat" },
                                { if: { chance: 30 }, use: "tongs", target: "lowest_hp" }, { use: "attack" } ],
                    drops: [ { item: "gold_seam_ring", chance: 100 } ],
                    description: "Orrin Vask, First of the Guild, in the firemouth of the Great Kiln with the tongs in his hands. Every fourth round he reads a name off the list: a Firing, four turns to run. Water is what he fears. The valley's first real boss." }
    }.freeze
  end
end
