# frozen_string_literal: true

# Encounter tables and generator tables: what's met on a towpath, and what
# the valley's towns, pits and vaults are rolled from. (Seeds::Greenware)
module Seeds
  module Greenware
    ENCOUNTER_TABLES = {
      towpath: { name: "Towpath", terrain: "plains", tier: 1,
                 description: "The barge roads between the kiln-towns: slip in the ruts, and things the slip made.",
                 entries: [ { weight: 4, monsters: { slip_hound: 3 } }, { weight: 2, monsters: { collier_hound: 2 } },
                            { weight: 1, monsters: { slip_hound: 2, grog_beetle: 1 } } ] },
      pits: { name: "Clay Pits", terrain: "cave", tier: 1,
              description: "Harrow galleries, and whatever the slip has learned to make.",
              entries: [ { weight: 4, monsters: { slip_hound: 3 } }, { weight: 3, monsters: { grog_beetle: 3 } },
                         { weight: 2, monsters: { slip_hound: 2, crazed_jug: 1 } }, { weight: 1, monsters: { grog_beetle: 2, slip_hound: 2 } } ] },
      charcoal_woods: { name: "Charcoal Woods", terrain: "forest", tier: 1,
                        description: "The colliers' woods: stacks smouldering under turf, and what crawled out of them.",
                        entries: [ { weight: 3, monsters: { collier_hound: 3 } }, { weight: 3, monsters: { cinder_imp: 2 } },
                                   { weight: 2, monsters: { grog_beetle: 3 } }, { weight: 1, monsters: { cinder_imp: 1, collier_hound: 2 } } ] },
      flats: { name: "Glass Flats", terrain: "desert", tier: 2,
               description: "A mile of ground that rings underfoot and cuts anything soft.",
               entries: [ { weight: 3, monsters: { glass_wasp: 4 } }, { weight: 3, monsters: { shard_golem: 1 } },
                          { weight: 2, monsters: { glass_wasp: 2, grog_beetle: 2 } } ] },
      estuary: { name: "Estuary", terrain: "sea", tier: 2,
                 description: "Where the river goes white at the edges.",
                 entries: [ { weight: 3, monsters: { salt_eel: 2 } }, { weight: 3, monsters: { crazed_jug: 2 } },
                            { weight: 2, monsters: { salt_eel: 1, crazed_jug: 1 } } ] },
      vaults: { name: "Misfire Vaults", terrain: "crypt", tier: 2,
                description: "Shelves of the misfired, and a song.",
                entries: [ { weight: 3, monsters: { misfire: 2 } }, { weight: 3, monsters: { bone_china_doll: 3 } },
                           { weight: 2, monsters: { misfire: 1, bone_china_doll: 1, crazed_jug: 1 } } ] },
      kiln: { name: "The Great Kiln", terrain: "mountain", tier: 3,
              description: "Inside the Kiln: firebrick that stood up, and the Guild's wardens.",
              entries: [ { weight: 3, monsters: { firebrick_golem: 1 } }, { weight: 2, monsters: { kiln_warden: 1, cinder_imp: 2 } },
                         { weight: 2, monsters: { cinder_imp: 4 } } ] }
    }.freeze

    GENERATOR_TABLES = {
      town_names: { name: "Town names", kind: "town_names",
                    entries: texts("Cone", "Bisque", "Slipway", "Saggar", "Marl", "Kaolin", "Fettle", "Grogham", "Wadding", "Engobe",
                                   "Sherdlow", "Flintcross", "Slaketon", "Cobble", "Tarnwick", "Loamford", "Sgraffi", "Firemouth", "Crownhill", "Wicket") },
      pit_names: { name: "Pit names", kind: "dungeon_names",
                   entries: texts("The Harrow Galleries", "The Deep Face", "Old Marl Pit", "The Drowned Drift", "Slip Bottom",
                                  "The Barrow Run", "Cobble's Delve", "The Wet Gallery", "Tally Pit", "The Shoring") },
      vault_names: { name: "Vault names", kind: "dungeon_names",
                     entries: texts("The Misfire Vaults", "The Long Shelves", "The Sorting Floor", "The Quiet Shelves", "The Choir Loft",
                                    "The First Shelf", "The Tagged Dark", "Shelf Hall") },
      works_names: { name: "Saltworks names", kind: "dungeon_names",
                     entries: texts("The Old Saltworks", "The White Pans", "The Glaze Vats", "Brine House", "The Drowned Pans", "The Mother Pan") },
      kiln_names: { name: "Kiln names", kind: "dungeon_names",
                    entries: texts("The Great Kiln", "The Cold Kiln", "The First Firing", "Crown Chamber", "The Firemouth", "The Bottle") },
      given_names: { name: "Given names", kind: "names",
                     entries: texts("Marl", "Fen", "Oda", "Tam", "Wick", "Rue", "Hale", "Brann", "Ilse", "Cobb", "Nell", "Dunn", "Ashe", "Gret",
                                    "Pim", "Sorrel", "Teal", "Vey", "Wren", "Ora", "Kell", "Loam", "Mott", "Pell", "Rill", "Sedge", "Tansy", "Umber",
                                    "Wyn", "Jory", "Bex", "Corin", "Edda", "Gile", "Ines", "Kessa", "Lorn", "Nim", "Piet",
                                    "Quill", "Saul", "Tilde", "Varro", "Zeb", "Alma", "Doro", "Faye", "Hanne", "Kit", "Marek", "Noor", "Runa", "Sten") },
      family_names: { name: "Families", kind: "families",
                      entries: texts("Vask", "Harrow", "Weld", "Grell", "Saggar", "Wedge", "Marlow", "Cobble", "Fettle", "Ashby", "Flint", "Tarn",
                                     "Wadd", "Sherd", "Loam", "Brindle", "Pitt", "Kiln", "Glaze", "Slake") },
      hooks: { name: "Townsfolk hooks", kind: "hooks",
               entries: texts("Has a crack down one arm and won't let a Mender near it.", "Was on the loading list last time. Doesn't say how they came off it.",
                              "Saw the chimneys of the Great Kiln steam, one morning, when nobody had lit anything.", "Sells cones that bend at the wrong heat.",
                              "Wants an escort to {town} before the first of Cone and can't pay yet.", "Is hiding an unfired cousin from the wardens.",
                              "Swears a pot on their shelf has started humming on Crackday.", "Collects maker's marks. Asks to see your heel.",
                              "Knows the old flue into {dungeon}.", "Wants their mother's gold seam back; a warden took it for the Guild.",
                              "Was a Kiln warden once. Won't say why they stopped.", "Keeps a slip hound that bites everyone but them.",
                              "Has a letter for someone who went into the Vaults 'to be mended'.", "Is certain Kilnmaster Vask is painted.",
                              "Pays well for grog beetle shells, and doesn't say why.", "Dreams of the sea, though the estuary's as far as they've been.",
                              "Heard singing from the slip tank.", "Is saving for a glass paddle they'll never be able to lift.",
                              "Their greenware all cracked overnight, in a perfect circle.", "Needs lime wash from {town} before the crazing reaches their face.",
                              "Was robbed on the towpath by someone very polite and very wet.", "Knows a song about the unfired that isn't flattering.",
                              "Runs a card game on Crackday with a marked deck.", "Is looking for a missing apprentice. The wardens aren't.",
                              "Found a key they can't find a lock for. It's warm.", "Remembers the last firing. Doesn't talk about it. Shakes a little.",
                              "Carves charms against the Firing. Some of them work.", "Wants the party to take a message to the Cone-Reader.",
                              "Is writing a book about misfires. Needs a closer look.", "Heard the Kiln Hall bell ring with no one pulling.",
                              "Sold their place on the loading list and regrets it.", "Hasn't slept since the lamps went out at the Vaults.",
                              "Will trade anything for news from Slipway.", "Keeps staring at one of the party as if they know their maker.",
                              "Buried something by the slip tank and forgot which post.", "Thinks the river is running salt. It is.") },
      # Townsfolk couplets (Generators::Town#couplets): a memory and a wish,
      # in their own words, in a valley where the old are fired and the
      # young aren't. A wish can be for something the party can bring.
      townsfolk_memories: { name: "Townsfolk memories", kind: "memories",
                            entries: texts("I was fired the year before the Kiln went cold. I was nineteen. I'm still nineteen.",
                                           "I watched my mother go into the Great Kiln. She came out a teapot.",
                                           "I threw pots for the Kilnmasters for thirty years and never signed one.",
                                           "I was on the loading list once. My brother took my place.",
                                           "I've been leather-hard since the floods. I don't bend the way I did.",
                                           "I mended my own arm with gold the winter the Menders went away.",
                                           "I walked out of {dungeon} alone. The others are still drying in there.",
                                           "I ran from {town} the night they started measuring us for the shelves.",
                                           "I sold the cones my father left me. I needed the bread more than the pride.",
                                           "I was the last apprentice at the Works before they bricked it up.",
                                           "I heard the Choir sing once, from the road. I haven't slept well since.",
                                           "I kept the drying shed for forty years. I know every crack in it.",
                                           "I've never been fired and I never will be. I've made sure.",
                                           "I lost a finger to a kiln shelf. Nobody remembers whose fault it was.") },
      townsfolk_wishes: { name: "Townsfolk wishes", kind: "wishes",
                          entries: texts("I want to be soft again, just for a day.", "I'm saving for a seat at the Firing, and I hope I never use it.",
                                         "I want my daughter off the loading list before the first of Cone.", "I'm teaching the children to throw, while they still can.",
                                         "I'd trade anything for news from {town}.", "I don't go near the chimneys after Cooling any more.",
                                         "I want to know who keeps lighting the old kilns at night.", "I'm going to leave the valley. I just haven't started.") +
                                   texts("I'd give anything to hear {dungeon} go quiet.", "My son went into {dungeon} for shards. I want it safe to look for him.") +
                                   [ { text: "My husband is crazing from the feet up. A little lime wash would buy him a season.", item: "lime_wash" },
                                     { text: "My grandmother's glaze has run into her eyes. She can't see the street.", item: "clear_glaze" },
                                     { text: "I've lost my voice to the flue dust, and I'm meant to call the names on Firing day.", item: "draft_whistle" },
                                     { text: "My sister cracked through, falling off the shed roof. Grog would hold her.", item: "grog_paste" },
                                     { text: "I promised my brother gold for his seams if he ever came home.", item: "menders_gold" } ] },
      # Offered to the GM on each arrival, the one that fits the moment best
      # (Campaign::Remarks).
      arrivals: { name: "Arrivals", kind: "arrivals",
                  entries: [ { text: "{place}. Dust on everything, and the kilns ticking as they cool." },
                             { text: "{place} again. The same pots on the same sills, a little drier.", when: "town, visits >= 2" },
                             { text: "{place} is wedging: the whole street slapping clay on boards.", when: "town, wedging" },
                             { text: "Wheels hum behind every door in {place}.", when: "town, throwing" },
                             { text: "Racks of greenware in the lanes of {place}, and everybody walking soft so nothing falls.", when: "town, drying" },
                             { text: "{place} after Cooling: the chimneys ticking, and a lamp in the old kiln that nobody admits to lighting.",
                               when: "town, cooling, !old_kiln_lamp", sets: "old_kiln_lamp" },
                             { text: "The lamp in the old kiln of {place} again. It moves, if you watch it long enough.", when: "town, cooling, old_kiln_lamp" },
                             { text: "The Firing is coming and {place} knows it: names chalked on doors, and some of them rubbed off.", when: "town, firing" },
                             { text: "{home} touches the doorpost of {place}, the way everyone here does, and finds it's still warm.", when: "town, first_visit" },
                             { text: "People in {place} crack a little, watching them pass. They've heard.", when: "town, standing = heroes" },
                             { text: "They come into {place} crazed and chipped. Somebody brings out the slip without asking.", when: "town, hurt >= 2" },
                             { text: "The air at the mouth of {place} is {damp|gritty|still} and tastes of iron.", when: "dungeon, first_visit" },
                             { text: "{place} is quiet now. The shoring creaks, and nothing answers.", when: "dungeon, cleared" } ] },
      # The GM's moves when a check fails (Campaign::Remarks).
      complications: { name: "Complications", kind: "complications",
                       entries: [ { text: "A tick in the clay somewhere close, like a pot cooling too fast." },
                                  { text: "{who} feels a hairline run somewhere it shouldn't. Nothing yet. Yet.", when: "failed >= 2" },
                                  { text: "It goes wrong, and the wrong way shows {who} a seam in the wall nobody fired shut. It'll cost to open.", when: "!dungeon" },
                                  { text: "Shoring creaks all along the gallery. The pit knows they're here.", when: "dungeon" },
                                  { text: "Someone on the racks saw {who}. They won't say who they tell.", when: "skill = softfoot, town" },
                                  { text: "The glaze in the ledger has run: the one line {who} wanted is a smear.", when: "skill = reading" },
                                  { text: "They nod and keep counting, and {who} understands the price just went up.", when: "skill = haggling" },
                                  { text: "{who} takes the weight wrong and something chips.", when: "skill = heft", does: "hurt 10" },
                                  { text: "The road gives out into slurry. The day goes with it.", when: "skill = roadcraft", does: "time 1" },
                                  { text: "Cones go missing from a pocket in the crush.", when: "town", does: "lose 50" },
                                  { text: "The kilns are being lit early. Whatever's coming, it's coming hotter.", does: "tick" },
                                  { text: "The noise carries down the gallery. Something comes up it.", when: "dungeon", does: "ambush" },
                                  { text: "It dries {who} out to the slip.", does: "weary 25" } ] },
      # What happens at camp or on the road (Campaign::Remarks).
      events: { name: "Camp and road", kind: "events",
                entries: [ { text: "A runaway from the loading list creeps up to the fire, still wet from the slip, and asks for nothing.",
                             when: "camp, !runaway_met", sets: "runaway_met",
                             choices: "Hide him: give lime_wash, rumour | Send him back: tick -> hid_the_runaway" },
                           { text: "Wardens on the road, checking names against a list. The runaway's name is on it.",
                             when: "road, hid_the_runaway = Hide him",
                             choices: "Talk them round: lose 50 | Go round by the pits: time 1, ambush -> passed_the_wardens" },
                           { text: "{hurt_one} is crazing badly. Every step opens it further.", when: "road, hurt_one",
                             choices: "Stop and mend: time 1, restore 25 | Keep walking: hurt 10, exp 20 -> walked_on_cracked" },
                           { text: "{from_pit_born} hears the slip singing under the road, and knows the tune.", when: "road, from_pit_born" },
                           { text: "{from_kiln_family} smells the kiln-wood on the wind and won't say what it means.", when: "from_kiln_family" },
                           { text: "{tied} dreams of {tied_to}, fired and glazed and smiling.", when: "camp, tied" },
                           { text: "A barge stuck on the shallows, and a bargewoman who'll pay for a shove.", when: "road, !barge_helped", sets: "barge_helped",
                             choices: "Wade in: weary 25, money 40 | Leave her: tick -> helped_the_barge" },
                           { text: "The sheds around the fire are all chalked. One door has been rubbed clean.", when: "camp" } ] },
      service_names: { name: "Service names", kind: "service_names",
                       entries: texts("The Leaning Pot", "The Warm Shelf", "Cone Six", "The Cracked Jug", "The Long Rack", "Leather-Hard", service: "inn") +
                                texts("Slip & Grog", "Harrow Supply", "The Fettling Bench", "Kaolin & Daughters", "Odd Shelves", service: "shop") +
                                texts("Kiln Hall", "The Stokers' Lodge", "Cone Hall", service: "guild") +
                                texts("The Menders' House", "House of Gold Seams", "The Quiet Shelf", service: "temple") },
      buildings: { name: "Building archetypes", kind: "buildings",
                   entries: [ { text: "Drying shed", service: "inn", width: 100, height: 70, roof: "peak" },
                              { text: "Supply", service: "shop", width: 70, height: 70, roof: "peak" },
                              { text: "Kiln Hall", service: "guild", width: 90, height: 110, roof: "flat" },
                              { text: "Menders' House", service: "temple", width: 70, height: 120, roof: "dome" },
                              { text: "Bottle kiln", width: 50, height: 130, roof: "dome", weight: 3 },
                              { text: "Workshop", width: 60, height: 60, roof: "peak", weight: 4 },
                              { text: "Cottage", width: 45, height: 50, roof: "peak", weight: 2 },
                              { text: "Chimney", width: 24, height: 140, roof: "flat" },
                              { text: "Slip house", width: 95, height: 55, roof: "flat" },
                              { text: "Rack shed", width: 110, height: 50, roof: "peak" } ] },
      # Cone and Slipway sell the second and third steps of every ladder;
      # Bisque the first and second. The fourth is found.
      kiln_stock: { name: "Kiln-town stock", kind: "stock",
                    entries: %w[slip_pot grog_paste menders_gold smoke_pot lime_wash clear_glaze draft_whistle kintsugi_kit
                                ironwood_paddle fired_paddle fettling_knife trimming_loop pit_mattock firebrick_maul ash_rake long_poker
                                ash_staff menders_staff ember_rod glaze_rod kiln_shelf saggar_lid firebrick_helm saggar_helm
                                dust_scarf readers_hood firebrick_jacket saggar_plate leather_apron slip_coat menders_robe kiln_robe
                                throwers_band wire_bracer cone_charm makers_ring]
                               .map { |item| { item: item } } },
      village_stock: { name: "Shed-village stock", kind: "stock",
                       entries: [ { item: "slip_pot", weight: 3 }, { item: "lime_wash", weight: 2 }, { item: "clear_glaze" }, { item: "draft_whistle" },
                                  { item: "smoke_pot" }, { item: "ironwood_paddle" }, { item: "fettling_knife" }, { item: "pit_mattock" },
                                  { item: "ash_rake" }, { item: "ash_staff" }, { item: "ember_rod" }, { item: "kiln_shelf" },
                                  { item: "firebrick_helm" }, { item: "dust_scarf" }, { item: "leather_apron" }, { item: "menders_robe" },
                                  { item: "canvas_apron" }, { item: "firebrick_jacket" } ] },
      # Each kind of dungeon has its own rooms and locks; the events, forks
      # and treasure are the valley's, shared.
      pit_rooms: { name: "Pit rooms", kind: "rooms",
                   entries: texts("Pithead", "Slip Tank", "Barrow Run", "Flooded Gallery", "Tally Hut", "Shoring", "Wet Gallery", "Clay Cellar",
                                  "Barrow Store", "Shored Drift", "The Sump", "Deep Face", "Winding Gear", "Lamp Room") },
      kiln_rooms: { name: "Kiln rooms", kind: "rooms",
                    entries: texts("Firemouth", "Ash Pit", "Saggar Store", "Bag Wall", "Cooling Chamber", "Wicket", "Flue", "Bottle Chamber", "Crown",
                                   "Spy Hole", "Loading Door", "Cone Shelf", "Wedging Table", "Glaze Room", "Wire Room", "Mould Store", "Stokehole", "Damper Gallery") },
      vault_rooms: { name: "Vault rooms", kind: "rooms",
                     entries: texts("Sorting Floor", "Shelf Hall", "Misfire Shelf", "Choir Loft", "Glue Room", "Sealed Niches", "Tag Room", "Long Shelves",
                                    "Rehearsal Room", "The Quiet Shelf", "Mending Bench", "Cold Store", "Lower Shelves", "The First Shelf") },
      works_rooms: { name: "Saltworks rooms", kind: "rooms",
                     entries: texts("Salt Pan", "Brine Cistern", "Glaze Vat", "Boiling House", "Pan Floor", "Crust Room", "Ledger Room", "Drowned Quay",
                                    "Salt Store", "Vat Gallery", "Sluice House", "The Mother Pan") },
      room_events: { name: "Room events", kind: "room_events",
                     entries: texts("A shelf of greenware, every pot turned to face the door. They were turned recently.",
                                    "The floor is warm. Nothing has been lit here in forty years.",
                                    "A row of misfires, shelved and tagged. One tag has your maker's mark on it.",
                                    "Someone has chalked a loading list on the wall. Your names are near the bottom.",
                                    "A draft, from a flue that should be bricked up. It smells of bread.",
                                    "A slip hound, too scared to fight, offers to trade a secret for its life. It can't talk. It tries.",
                                    "A lamp still burns here. The oil is fresh.",
                                    "Wet footprints lead in and don't lead out.",
                                    "A saggar sits open and empty. The dust inside it is disturbed, in the shape of a hand.",
                                    "The walls are covered in tally marks, in slip. Hundreds. Some are fresh.",
                                    "A bone china doll's eyes follow whoever holds a light.",
                                    "Water drips upward from a puddle into the ceiling, and sets there as glaze.",
                                    "A fired man in old Guild robes, cracked across the chest, clutches a note: \"The cones lied.\"",
                                    "Somewhere ahead, someone is humming. It's the song from the Kiln Hall, slowed.",
                                    "A sleeping firebrick golem blocks half the room. It doesn't wake. Yet.",
                                    "The room is cold, and smells of the river.",
                                    "Carved over the door: a maker's mark one of you almost knows.",
                                    "A glaze vat shows the room with one more person in it.",
                                    "Grog on the floor glows faintly where you step.",
                                    "An old campsite. The bedrolls are still warm, and there's a bent cone on each one.") },
      forks: { name: "Fork costs", kind: "forks",
               entries: texts("A kiln shelf across a drop: someone must stay behind to hold it level.",
                              "Glaze fumes: everyone who goes this way loses a tenth of their Body. (hurt 10)",
                              "A sealed wicket that opens only for 100 cones in the slot. (pay 100)",
                              "A narrow flue: no heavy armour fits through.",
                              "Rising slip: the way back will be under it behind you.",
                              "A toll-misfire: it wants 60 cones, and it won't haggle. (pay 60)",
                              "Loose saggars: the noise will wake whatever sleeps below. (ambush)",
                              "A dark stair: no flame will burn on it.",
                              "A cold chamber: it drinks the Slip of everyone who passes through. (weary 25)",
                              "Glass underfoot: it cuts everyone who crosses. (hurt 20)",
                              "A long climb through the crown: it takes half the day, and the party arrives spent. (2)",
                              "A hall that sings back: speak, and the Choir answers with something worse.") },
      pit_locks: { name: "Pit locks and keys", kind: "locks",
                   entries: [ { text: "Slip gate", key: "Valve wheel" }, { text: "Shored door", key: "Pit prop" },
                              { text: "Flooded drift", key: "Barrow pump" }, { text: "Tally gate", key: "Foreman's tally-stick" } ] },
      kiln_locks: { name: "Kiln locks and keys", kind: "locks",
                    entries: [ { text: "Guild-sealed wicket", key: "Kilnmaster's tongs" }, { text: "Bricked flue", key: "Firebrick chisel" },
                               { text: "Cone gate", key: "A cone-ten, unbent" }, { text: "Loading door", key: "The loading list" },
                               { text: "Saggar seal", key: "Warden's seal-stamp" } ] },
      vault_locks: { name: "Vault locks and keys", kind: "locks",
                     entries: [ { text: "Choir door", key: "A held note (a bell)" }, { text: "Shelf-lock", key: "Sorting tag" },
                                { text: "Glaze-fused door", key: "Flux jar" }, { text: "Glue-shut niche", key: "Mender's solvent" } ] },
      works_locks: { name: "Saltworks locks and keys", kind: "locks",
                     entries: [ { text: "Drowned sluice", key: "Pan key" }, { text: "Salt-crusted hatch", key: "Brine pick" },
                                { text: "Vat lid", key: "Glaze ladle" } ] },
      treasure: { name: "Dungeon treasure", kind: "treasure",
                  entries: [ { item: "slip_pot", weight: 8 }, { item: "grog_paste", weight: 4 }, { item: "menders_gold", weight: 4 },
                             { item: "lime_wash", weight: 4 }, { item: "kintsugi_kit", weight: 2 }, { item: "makers_ring", weight: 2 },
                             { item: "apron_and_plates", weight: 2 }, { item: "trimming_loop", weight: 2 }, { item: "fired_paddle", weight: 2 },
                             { item: "menders_staff", weight: 2 }, { item: "slip_coat", weight: 2 }, { item: "gold_seam_ring", weight: 2 },
                             { item: "glass_paddle" }, { item: "cone_readers_rod" }, { item: "glass_pane" }, { item: "shardwalkers_wrap" },
                             { gil: 50, weight: 6 }, { gil: 120, weight: 4 }, { gil: 300, weight: 2 } ] }
    }.freeze

    # The valley's lore (Generators::Lore): what its pocket history and the
    # pasts of its places are made of.
    LORE = {
      "trades" => { "potter" => %w[jug bowl urn], "digger" => [], "collier" => [], "mender" => [ "gold seam" ], "glazier" => [ "glaze jar", "tile" ],
                    "bargeman" => [], "salter" => [ "salt cellar" ], "cone-reader" => %w[cone pyrometer] },
      "pasts" => {
        "kiln" => { "rooms" => [ "Firemouth", "Ash Pit", "Bag Wall", "Chamber", "Crown", "Spy Hole", "Loading Door", "Cooling Shelf" ],
                    "heart" => "The Firebox", "keeps" => [ "tongs", "spy-glass", "first cone" ], "named" => %w[kiln oven bottle firing] },
        "pit" => { "rooms" => [ "Pithead", "Slip Tank", "Barrow Run", "Flooded Gallery", "Tally Hut", "Shoring", "Deep Face" ],
                   "heart" => "The Bottom Face", "keeps" => %w[shovel tally-stick lamp], "named" => %w[pit pits quarry delve dig galleries] },
        "shed" => { "rooms" => [ "Rack Hall", "Turning Floor", "Wet Room", "Cloth Store", "Sponge Bench" ],
                    "heart" => "The Long Rack", "keeps" => [ "sponge", "rib", "wet cloth" ], "named" => %w[shed sheds racks drying] },
        "vault" => { "rooms" => [ "Sorting Floor", "Shelf Hall", "Misfire Shelf", "Choir Loft", "Glue Room", "Sealed Niches" ],
                     "heart" => "The First Shelf", "keeps" => [ "shelf tag", "gold leaf", "bell" ], "named" => %w[vault vaults store shelves] },
        "saltworks" => { "rooms" => [ "Salt Pan", "Brine Cistern", "Glaze Vat", "Boiling House", "Pan Floor", "Crust Room" ],
                         "heart" => "The Mother Pan", "keeps" => [ "salt cellar", "glaze ladle", "ledger" ], "named" => %w[saltworks works pans salting] },
        "tower" => { "rooms" => [ "Long Stair", "Reading Room", "Cone Shelf", "Lens Room", "Map Floor" ],
                     "heart" => "The Top Room", "keeps" => [ "lens", "journal", "bent cone" ], "named" => %w[tower spire lookout] }
      },
      "falls" => {
        "blowout" => { "did" => "blew out", "sealed" => "left as glass", "trace" => "The walls run like candle wax, and the floor rings.",
                       "dead" => "who was inside when it blew", "town" => "The kiln at %s blew" },
        "slip" => { "did" => "slipped", "sealed" => "shored and left", "trace" => "A tide line of slip, higher than your head, with handprints in it.",
                    "dead" => "who went under", "town" => "The ground went under %s" },
        "flood" => { "did" => "flooded", "sealed" => "left to the water", "trace" => "Salt crust on everything, and the water still a finger higher each year.",
                     "dead" => "who drowned in it", "town" => "The river came up through %s" },
        "crazing" => { "did" => "crazed", "sealed" => "bricked up before it spread", "trace" => "Fine cracks over every surface, like frost, going nowhere good.",
                       "dead" => "who crazed with it", "town" => "The crazing came to %s" },
        "hush" => { "did" => "went quiet", "sealed" => "locked with the quiet inside", "trace" => "Everything in its place, and a layer of dust on it.",
                    "dead" => "who stopped talking" }
      },
      "quarrels" => [ "a maker's mark stamped on someone else's pot", "a kiln shelf cracked and blamed", "a glaze recipe copied",
                      "the loading order at the last firing", "a child promised to the wrong family", "water rights at the slip tank",
                      "a barge sunk with both their clay in it", "who read the cone wrong", "a seat in the Kiln Hall", "a dog that broke a shelf of greenware" ],
      "betrayals" => [ "put their name forward for the loading list", "sold their glaze recipe to the Guild", "shored their gallery with rotten timber",
                       "told the wardens where their unfired child was hiding", "swapped the cones so their firing failed" ],
      "fortunes" => [ "a good seam of white clay", "a firing that came out all whole", "a barge contract with the Guild", "a glaze nobody could copy" ],
      "waters" => [ "the slip tank", "the river", "the salt pans", "the estuary" ],
      "owners" => [ "Pawned by a %s who never came back for it", "Sold off by the %s family after a bad firing", "Won from a %s on Crackday",
                    "Made for a %s wedding that never happened", "A %s's, until the feud" ],
      "sightings" => [ "{who} was seen in {where}, not where they said they'd be." ],
      "raids" => [ "A clay barge between {from} and {to} was boarded, and its load tipped in the river." ]
    }.freeze

    LORE_NAMES = { "trades" => "Trades", "pasts" => "What the pits and vaults were", "falls" => "How places fall", "quarrels" => "Quarrels",
                   "betrayals" => "Betrayals", "fortunes" => "Good fortune", "waters" => "Waters", "owners" => "Changing hands",
                   "sightings" => "Sightings", "raids" => "Raided roads" }.freeze
    LORE_TABLES = Generators::Lore.to_tables(LORE).to_h do |kind, entries|
      [ :"lore_#{kind}", { name: LORE_NAMES.fetch(kind), kind: kind, entries: entries } ]
    end.freeze
  end
end
