# frozen_string_literal: true

# The Grimoire: each archetype's lessons and the creatures' moves
# (docs/ODA.md). Numbers follow the Base World's tuning for a level-5
# party. (Seeds::Oda)
module Seeds
  module Oda
    # The five Mancers, written from one form: four measures of the one
    # powder (a single, a spread, a double and the top measure, which a
    # resistance can't stop and which leaves the caster reloading), the
    # powder's own trick, a load for an ally's weapon, a field art, and the
    # last thing they learn.
    MANCER_POWDERS = {
      "fire" => { tiers: %w[Fire Fira Firaga Firaja], trick: [ "scorch", "Scorch", { primitive: "status", kind: "burn", chance: 80, duration: 3 }, "single_enemy",
                                                              "A pinch of red salt thrown in the face. It keeps burning after." ],
                  load: [ "flame_load", "Flame Load" ], last: [ "inferno", "Inferno" ],
                  field: [ "signal_fire", "Signal Fire", "reveal", "A red flare over the mesas, and every lookout for a day's ride answers with what they see." ] },
      "water" => { tiers: %w[Water Watera Waterga Waterja], trick: [ "undertow", "Undertow", { primitive: "status", kind: "slow", chance: 75, duration: 3 }, "single_enemy",
                                                                    "Cold blue salt that drags at the legs like a river." ],
                   load: [ "tide_load", "Tide Load" ], last: [ "maelstrom", "Maelstrom" ],
                   field: [ "find_water", "Find Water", "restore", "A pinch of blue salt in the palm, and it turns toward the nearest spring." ] },
      "thunder" => { tiers: %w[Thunder Thundara Thundaga Thundaja], trick: [ "jolt", "Jolt", { primitive: "status", kind: "paralyze", chance: 60, duration: 1 }, "single_enemy",
                                                                            "A spark through the joints. They stand very still for a moment." ],
                     load: [ "spark_load", "Spark Load" ], last: [ "thunderhead", "Thunderhead" ],
                     field: [ "spark_the_works", "Spark the Works", "find", "A dead machine, a jolt of yellow salt, and it remembers what it was for." ] },
      "earth" => { tiers: %w[Stone Stonera Stonega Stoneja], trick: [ "stoneskin", "Stoneskin", { primitive: "shield", power: 8, duration: 3 }, "single_ally",
                                                                      "Grey salt rubbed on the skin, and the skin remembers being rock." ],
                   load: [ "stone_load", "Stone Load" ], last: [ "landslide", "Landslide" ],
                   field: [ "read_the_seam", "Read the Seam", "find", "A taste of the dust, and they know where the good powder runs." ] },
      "wind" => { tiers: %w[Aero Aerora Aeroga Aeroja], trick: [ "gale", "Gale", { primitive: "away", who: "target", duration: 2, chance: 70 }, "single_enemy",
                                                                "A green gust that picks someone up and puts them somewhere else." ],
                  load: [ "gale_load", "Gale Load" ], last: [ "tempest", "Tempest" ],
                  field: [ "read_the_wind", "Read the Wind", "safe_road", "Green salt on the tongue, and the wind says which way the trouble lies." ] }
    }.freeze

    MANCER_SKILLS = { "fire" => "powdercraft", "water" => "trail", "thunder" => "clockwork", "earth" => "powdercraft", "wind" => "trail" }.freeze

    def self.mancer_abilities
      MANCER_POWDERS.flat_map do |type, powder|
        single, spread, double, top = powder[:tiers]
        trick_slug, trick_name, trick_effect, trick_target, trick_text = powder[:trick]
        load_slug, load_name = powder[:load]
        last_slug, last_name = powder[:last]
        field_slug, field_name, field_outcome, field_text = powder[:field]
        [
          [ single.downcase.to_sym, { name: single, kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
                                      effects: [ { primitive: "elemental", type: type, power: 12 } ],
                                      description: "A single measure of #{type} powder, fired from the palm." } ],
          [ spread.downcase.to_sym, { name: spread, kind: "magic", target: "all_enemies", mp_cost: 12, gesture: "flash",
                                      effects: [ { primitive: "elemental", type: type, power: 10 } ],
                                      description: "A measure spread thin across a whole line of them." } ],
          [ double.downcase.to_sym, { name: double, kind: "magic", target: "single_enemy", mp_cost: 14, gesture: "flash",
                                      effects: [ { primitive: "elemental", type: type, power: 26 } ],
                                      description: "A double measure, packed tight. Mind the recoil." } ],
          [ top.downcase.to_sym, { name: top, kind: "magic", target: "single_enemy", mp_cost: 24, reload_turns: 1, gesture: "flash",
                                   effects: [ { primitive: "elemental", type: type, power: 40, unresisted: 1 } ],
                                   description: "The top measure: no resistance stops it. It takes a turn to load the next." } ],
          [ trick_slug.to_sym, { name: trick_name, kind: "magic", target: trick_target, mp_cost: 4, gesture: "pop", effects: [ trick_effect ], description: trick_text } ],
          [ load_slug.to_sym, { name: load_name, kind: "magic", target: "single_ally", mp_cost: 4, gesture: "tint",
                                effects: [ { primitive: "imbue", type: type, duration: 3 } ],
                                description: "Loads an ally's weapon with #{type} powder: their Attack strikes as #{type} for a while. A specialist changes the matchup instead of the score." } ],
          [ last_slug.to_sym, { name: last_name, kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "spin",
                                effects: [ { primitive: "elemental", type: type, power: 45 } ],
                                description: "Everything left in the pouch at once. Only at the end of a Mancer's rope." } ],
          [ field_slug.to_sym, { name: field_name, kind: "field", field_skill: MANCER_SKILLS.fetch(type), field_outcome: field_outcome, field_difficulty: "normal",
                                 field_power: (field_outcome == "find" ? 150 : 0), effects: [], description: field_text } ]
        ]
      end.to_h
    end

    ABILITIES = mancer_abilities.merge(
      # --- the Courtsword: calm, and then not ---------------------------------------------
      sheathe: { name: "Sheathe", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
                 effects: [ { primitive: "gather", kind: "sheathed" }, { primitive: "buff", stat: "def", amount: 30, duration: 1 } ],
                 description: "The blade goes back in its sheath, and the Courtsword goes still. Every turn waited is another measure of the draw." },
      draw: { name: "Draw", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "lunge",
              effects: [ { primitive: "physical", power: 60, with: "sheathed", boost: 60, patience: 10 } ],
              description: "The draw: one cut across everyone. Stronger for every turn spent sheathed, and for everyone who moved first." },
      iai_stance: { name: "Iai Stance", kind: "skill", target: "self", mp_cost: 2, gesture: "fade",
                    effects: [ { primitive: "status", kind: "iai", duration: 2 } ],
                    description: "Hand on the hilt. The first one to come at them alone is cut down before they arrive." },
      zantetsuken: { name: "Zantetsuken", kind: "skill", target: "single_enemy", mp_cost: 6, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 90, against: "wounded", bonus: 300 } ],
                     description: "A cut for the end of a fight: three times as hard against anyone already at the end of theirs." },
      stillwater: { name: "Stillwater", kind: "skill", target: "self", mp_cost: 4, gesture: "float",
                    effects: [ { primitive: "gather", kind: "sheathed", amount: 2 }, { primitive: "buff", stat: "spr", amount: 50, duration: 3 } ],
                    description: "A breath held so long the world forgets them. Two measures of the draw at once." },
      moon_cut: { name: "Moon Cut", kind: "skill", target: "all_enemies", mp_cost: 8, gesture: "spin",
                  effects: [ { primitive: "physical", power: 70, patience: 25 } ],
                  description: "Drawn last, in a full circle. The longer everyone else took, the further it reaches." },
      last_light: { name: "Last Light", kind: "skill", target: "single_enemy", mp_cost: 6, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 100, with: "sheathed", boost: 100 } ],
                    description: "Everything the sheath held, into one cut, for one of them." },
      final_draw: { name: "Final Draw", kind: "skill", target: "all_enemies", mp_cost: 12, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 110, with: "sheathed", boost: 80, patience: 20 } ],
                    description: "The scene everyone remembers: a calm figure, and then everyone else falls." },
      thousand_cuts: { name: "Thousand Cuts", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                       effects: [ { primitive: "physical", power: 200 } ], description: "Nobody saw the blade move." },
      stare_down: { name: "Stare Down", kind: "field", field_skill: "nerve", field_outcome: "sneak", field_difficulty: "hard", effects: [],
                    description: "Whoever's waiting on the road looks into a Courtsword's eyes, and finds somewhere else to be." },

      # --- the Thief --------------------------------------------------------------------
      mug: { name: "Mug", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
             effects: [ { primitive: "physical", power: 80 }, { primitive: "steal", chance: 40 } ],
             description: "A punch and a pocket in one movement." },
      steal: { name: "Steal", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "slide",
               effects: [ { primitive: "steal", chance: 60 } ], description: "Something of theirs, now something of yours." },
      smoke_bomb: { name: "Smoke Bomb", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
                    effects: [ { primitive: "escape" } ], description: "A paper twist of grey powder and a quick exit, for everyone." },
      hide: { name: "Hide", kind: "skill", target: "self", mp_cost: 0, gesture: "fade",
              effects: [ { primitive: "away", who: "self", duration: 1 } ], description: "Gone, until they aren't." },
      lift: { name: "Lift", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "slide",
              effects: [ { primitive: "steal", chance: 60, boon: 1 } ],
              description: "Not their purse: their haste, their barrier, their luck. Worn better by a Thief." },
      twin_knives: { name: "Twin Knives", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 60, hits: 2 } ], description: "Two blades, one breath." },
      backstab: { name: "Backstab", kind: "skill", target: "single_enemy", mp_cost: 3, gesture: "lunge",
                  effects: [ { primitive: "physical", power: 100, against: "blind", bonus: 250 } ], description: "Best when they can't see it coming." },
      blinding_dust: { name: "Blinding Dust", kind: "skill", target: "single_enemy", mp_cost: 2, gesture: "pop",
                       effects: [ { primitive: "status", kind: "blind", chance: 80, duration: 3 } ], description: "Grit, pepper and a little white powder, in the eyes." },
      shadowstep: { name: "Shadowstep", kind: "skill", target: "single_enemy", mp_cost: 4, gesture: "fade",
                    effects: [ { primitive: "away", who: "self", duration: 1, power: 220 } ], description: "Gone for a turn, and back behind them." },
      grand_larceny: { name: "Grand Larceny", kind: "skill", target: "single_enemy", mp_cost: 6, gesture: "slide",
                       effects: [ { primitive: "steal", chance: 90 }, { primitive: "steal", chance: 80, boon: 1 } ], description: "Everything that isn't nailed down, and a few things that are." },
      vanishing_point: { name: "Vanishing Point", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "fade",
                         effects: [ { primitive: "physical", power: 300 } ], description: "There, then not, then there was a knife." },
      pick_lock: { name: "Pick Lock", kind: "field", field_skill: "hands", field_outcome: "unlock", field_difficulty: "normal", effects: [],
                   description: "A Company padlock, a clockwork door, a strongroom: the lock in the party's way opens, key or no key." },

      # --- the Monk: fists and breath, and no powder at all --------------------------------
      palm_strike: { name: "Palm Strike", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 90 }, { primitive: "gather", kind: "chi" } ],
                     description: "An open hand, and a breath gathered with it." },
      sweep_kick: { name: "Sweep Kick", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                    effects: [ { primitive: "physical", power: 60 } ], description: "Everyone in reach, off their feet." },
      gather_breath: { name: "Gather Breath", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
                       effects: [ { primitive: "gather", kind: "chi", amount: 2 } ], description: "In, and hold it. Two breaths of chi." },
      dragon_fist: { name: "Dragon Fist", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 100, pierce: 50, with: "chi", boost: 40 } ],
                     description: "Through the armour, not around it. Every breath of chi goes into it." },
      chakra: { name: "Chakra", kind: "skill", target: "self", mp_cost: 0, gesture: "float",
                effects: [ { primitive: "heal", power: 20 }, { primitive: "cleanse" } ], description: "Breath set right, and the body follows." },
      iron_body: { name: "Iron Body", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
                   effects: [ { primitive: "buff", stat: "def", amount: 60, duration: 3 }, { primitive: "gather", kind: "chi" } ], description: "Struck, they ring like a bell." },
      revenge: { name: "Revenge", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                 effects: [ { primitive: "physical", power: 100, grudge: 200 } ], description: "Every bruise, returned." },
      seven_forms: { name: "Seven Forms", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "spin",
                     effects: [ { primitive: "physical", power: 110, pierce: 30, with: "chi", boost: 50 } ],
                     description: "The whole of the temple's teaching, in one movement, spent on everyone." },
      hundred_fists: { name: "Hundred Fists", kind: "skill", target: "random_enemy", mp_cost: 0, gesture: "lunge",
                       effects: [ { primitive: "physical", power: 60, hits: 6 } ], description: "Counted, if you're fast enough to count." },
      meditate: { name: "Meditate", kind: "field", field_skill: "nerve", field_outcome: "restore", field_difficulty: "easy", field_power: 25, effects: [],
                  description: "An hour of stillness, and the party breathes with them." },

      # --- the Magician: time, mirrors, smoke and small machines ------------------------
      quick: { name: "Quick", kind: "magic", target: "single_ally", mp_cost: 8, gesture: "spin",
               effects: [ { primitive: "quick" } ], description: "A turn of the key in someone's back: they go again, now." },
      haste: { name: "Haste", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "spin",
               effects: [ { primitive: "status", kind: "haste", duration: 3 } ], description: "Their clock runs fast." },
      slow: { name: "Slow", kind: "magic", target: "single_enemy", mp_cost: 4, gesture: "tint",
              effects: [ { primitive: "status", kind: "slow", chance: 80, duration: 3 } ], description: "Their clock runs slow." },
      dispel: { name: "Dispel", kind: "magic", target: "single_enemy", mp_cost: 5, gesture: "flash",
                effects: [ { primitive: "dispel" } ], description: "Whatever's helping them stops." },
      reflect: { name: "Reflect", kind: "magic", target: "single_ally", mp_cost: 6, gesture: "flash",
                 effects: [ { primitive: "status", kind: "reflect", duration: 3 } ], description: "A mirror only magic can see. A Mancer's answer." },
      mimic: { name: "Mimic", kind: "skill", target: "self", mp_cost: 0, gesture: "pop",
               effects: [ { primitive: "mimic" } ], description: "Whatever an ally just did, again, and free." },
      gravity: { name: "Gravity", kind: "magic", target: "single_enemy", mp_cost: 8, gesture: "shake",
                 effects: [ { primitive: "percent", power: 25, chance: 85 } ], description: "A quarter of whatever they have left, gone heavy." },
      stop: { name: "Stop", kind: "magic", target: "single_enemy", mp_cost: 10, gesture: "fade",
              effects: [ { primitive: "status", kind: "stop", chance: 60, duration: 2 } ], description: "The clock in their chest stops, for a little while." },
      banish: { name: "Banish", kind: "magic", target: "single_enemy", mp_cost: 8, gesture: "fade",
                effects: [ { primitive: "away", who: "target", duration: 2, chance: 70 } ], description: "Smoke, a mirror, and they're somewhere else." },
      vanishing_act: { name: "Vanishing Act", kind: "magic", target: "self", mp_cost: 6, gesture: "fade",
                       effects: [ { primitive: "escape" } ], description: "Ta-da. The whole party, gone." },
      time_lapse: { name: "Time Lapse", kind: "magic", target: "all_allies", mp_cost: 18, gesture: "spin",
                    effects: [ { primitive: "status", kind: "haste", duration: 3 } ], description: "Everyone's clock, wound up." },
      clockstop: { name: "Clockstop", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "fade",
                   effects: [ { primitive: "status", kind: "stop", chance: 70, duration: 2 } ], description: "Every clock on their side, stopped at once." },
      smoke_and_mirrors: { name: "Smoke and Mirrors", kind: "field", field_skill: "clockwork", field_outcome: "sneak", field_difficulty: "normal", effects: [],
                           description: "A puff of smoke, a mirror at the right angle, and the party walks past whatever was waiting." },

      # --- the Healer --------------------------------------------------------------------
      triage: { name: "Triage", kind: "magic", target: "single_ally", mp_cost: 4, gesture: "float",
                effects: [ { primitive: "heal", power: 18, triage: 200 } ], description: "The worst first: the more hurt they are, the more it mends." },
      cure: { name: "Cure", kind: "magic", target: "single_ally", mp_cost: 4, gesture: "float",
              effects: [ { primitive: "heal", power: 25 } ], description: "A clean bandage and a steady hand." },
      draw_out: { name: "Draw Out", kind: "magic", target: "single_ally", mp_cost: 3, gesture: "float",
                  effects: [ { primitive: "cleanse", kind: "poison" }, { primitive: "cleanse", kind: "burn" } ],
                  description: "Powder-sickness and burns, drawn out with a poultice." },
      regen: { name: "Regen", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
               effects: [ { primitive: "status", kind: "regen", duration: 4 } ], description: "A tonic that keeps working after it's swallowed." },
      purify: { name: "Purify", kind: "magic", target: "single_ally", mp_cost: 5, gesture: "float",
                effects: [ { primitive: "cleanse" } ], description: "Whatever ails them, all of it." },
      bulwark: { name: "Bulwark", kind: "magic", target: "all_allies", mp_cost: 9, gesture: "float",
                 effects: [ { primitive: "buff", stat: "def", amount: 40, duration: 3 } ], description: "Bandages, braces and a talking-to: everyone takes hits better." },
      raise: { name: "Raise", kind: "magic", target: "single_ally", mp_cost: 10, gesture: "pop",
               effects: [ { primitive: "revive", fraction: 25 } ], description: "Smelling salts, a thump on the chest, and they're back." },
      reraise: { name: "Reraise", kind: "magic", target: "single_ally", mp_cost: 14, gesture: "float",
                 effects: [ { primitive: "status", kind: "reraise", duration: 5 } ], description: "A charm sewn into the collar: if they go down, they get up." },
      mass_cure: { name: "Mass Cure", kind: "magic", target: "all_allies", mp_cost: 12, gesture: "float",
                   effects: [ { primitive: "heal", power: 16, triage: 100 } ], description: "Everyone patched, the worst most." },
      full_recovery: { name: "Full Recovery", kind: "magic", target: "single_ally", mp_cost: 18, gesture: "float",
                       effects: [ { primitive: "heal", power: 60 }, { primitive: "cleanse" } ], description: "A week in a healer's house, in a minute." },
      purge: { name: "Purge", kind: "magic", target: "all_enemies", mp_cost: 0, gesture: "flash",
               effects: [ { primitive: "elemental", type: "water", power: 30, against: "undead", bonus: 300 } ], description: "Clean water, and everything rotten in reach flinches." },
      field_dressing: { name: "Field Dressing", kind: "field", field_skill: "trail", field_outcome: "restore", field_difficulty: "easy", field_power: 30, effects: [],
                        description: "Boiled water, clean cloth and an hour. Everyone's better for it." },

      # --- the Ranger --------------------------------------------------------------------
      aimed_shot: { name: "Aimed Shot", kind: "skill", target: "single_enemy", mp_cost: 0, reach: true, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 130, type: "shot" } ], description: "A breath, a squeeze. It finds them wherever they've gone." },
      call_hawk: { name: "Call Hawk", kind: "skill", target: "self", mp_cost: 3, gesture: "float",
                   effects: [ { primitive: "summon", creature: "hawk", stays: 1 } ], description: "A whistle, and the hawk comes down: it stays for the fight." },
      long_shot: { name: "Long Shot", kind: "skill", target: "single_enemy", mp_cost: 2, reach: true, reload_turns: 1, gesture: "lunge",
                   effects: [ { primitive: "physical", power: 200, type: "shot" } ], description: "The long gun: a big shot, a long reload." },
      volley: { name: "Volley", kind: "skill", target: "random_enemy", mp_cost: 4, reach: true, gesture: "shake",
                effects: [ { primitive: "physical", power: 50, hits: 3, type: "shot" } ], description: "Three quick shots at whoever's there." },
      call_hound: { name: "Call Hound", kind: "skill", target: "self", mp_cost: 4, gesture: "bounce",
                    effects: [ { primitive: "summon", creature: "hound", duration: 3 } ], description: "A ranger's dog, in for three of its turns, and in hard." },
      pinning_shot: { name: "Pinning Shot", kind: "skill", target: "single_enemy", mp_cost: 3, reach: true, gesture: "lunge",
                      effects: [ { primitive: "physical", power: 80, type: "shot" }, { primitive: "status", kind: "slow", chance: 70, duration: 3 } ],
                      description: "Through the boot. They aren't running anywhere." },
      hunters_mark: { name: "Hunter's Mark", kind: "skill", target: "single_enemy", mp_cost: 3, gesture: "pop",
                      effects: [ { primitive: "debuff", stat: "def", amount: 40, duration: 3 } ], description: "Chalk on their coat, where the shot goes." },
      deadeye: { name: "Deadeye", kind: "skill", target: "single_enemy", mp_cost: 6, reach: true, gesture: "lunge",
                 effects: [ { primitive: "physical", power: 150, type: "shot", against: "wounded", bonus: 250 } ], description: "For the one who's nearly done." },
      rain_of_lead: { name: "Rain of Lead", kind: "skill", target: "random_enemy", mp_cost: 0, reach: true, gesture: "shake",
                      effects: [ { primitive: "physical", power: 60, hits: 6, type: "shot" } ], description: "Every chamber, every barrel, every pocket." },
      scout: { name: "Scout", kind: "field", field_skill: "trail", field_outcome: "reveal", field_difficulty: "easy", effects: [],
               description: "Up the nearest mesa with a glass, and back with the lie of the land." },

      # --- the Soldier: pike, shot and the line held -------------------------------------
      pike_thrust: { name: "Pike Thrust", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 130, pierce: 30 } ], description: "Eighteen feet of ash and a steel point, through whatever's in the way." },
      war_cry: { name: "War Cry", kind: "skill", target: "self", mp_cost: 0, gesture: "bounce",
                 effects: [ { primitive: "buff", stat: "str", amount: 50, duration: 3 } ], description: "A shout that does nothing to the enemy and everything to the Soldier." },
      halberd_sweep: { name: "Halberd Sweep", kind: "skill", target: "all_enemies", mp_cost: 4, gesture: "spin",
                       effects: [ { primitive: "physical", power: 75 } ], description: "A wide, low cut across the whole line." },
      rally: { name: "Rally", kind: "skill", target: "all_allies", mp_cost: 6, gesture: "bounce",
               effects: [ { primitive: "buff", stat: "str", amount: 25, duration: 3 } ], description: "\"On me! Hold!\" And they do." },
      shield_bash: { name: "Shield Bash", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 80 }, { primitive: "status", kind: "paralyze", chance: 35, duration: 1 } ],
                     description: "The rim of a shield, in the face. They lose a moment." },
      butt_stroke: { name: "Butt Stroke", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                     effects: [ { primitive: "physical", power: 80 }, { primitive: "status", kind: "paralyze", chance: 35, duration: 1 } ],
                     description: "The wrong end of the pike, in the face. They lose a moment." },
      fire_at_will: { name: "Fire at Will", kind: "skill", target: "random_enemy", mp_cost: 8, gesture: "shake",
                      effects: [ { primitive: "physical", power: 70, hits: 3, type: "shot" } ], description: "The matchlocks come up behind the pikes, and the line goes white with smoke." },
      forlorn_hope: { name: "Forlorn Hope", kind: "skill", target: "all_enemies", mp_cost: 0, gesture: "lunge",
                      effects: [ { primitive: "physical", power: 180, grudge: 100 } ], description: "The charge nobody comes back from, except, this once, the Soldier." },
      kick_it_in: { name: "Kick It In", kind: "field", field_skill: "brawn", field_outcome: "unlock", field_difficulty: "normal", effects: [],
                    description: "The Thief has a pick. The Soldier has a boot." },

      # --- the Bodyguard: in front, always ----------------------------------------------
      guard: { name: "Guard", kind: "skill", target: "self", mp_cost: 0, gesture: "shake",
               effects: [ { primitive: "status", kind: "cover", duration: 3 } ], description: "Steps in front of everyone: every single blow meant for the party comes here instead." },
      brace: { name: "Brace", kind: "skill", target: "self", mp_cost: 2, gesture: "tint",
               effects: [ { primitive: "buff", stat: "def", amount: 60, duration: 3 }, { primitive: "buff", stat: "mdef", amount: 40, duration: 3 } ],
               description: "Feet set, shield up, chin down." },
      interpose: { name: "Interpose", kind: "skill", target: "single_ally", mp_cost: 4, gesture: "slide",
                   effects: [ { primitive: "shield", power: 30, duration: 3 } ], description: "A shoulder and a shield between an ally and the worst of it." },
      shield_wall: { name: "Shield Wall", kind: "skill", target: "all_allies", mp_cost: 8, gesture: "tint",
                     effects: [ { primitive: "buff", stat: "def", amount: 30, duration: 3 } ], description: "Everyone behind the Bodyguard's shield, and the shield is big enough." },
      unbreakable: { name: "Unbreakable", kind: "skill", target: "self", mp_cost: 10, gesture: "flash",
                     effects: [ { primitive: "status", kind: "regen", duration: 4 }, { primitive: "buff", stat: "def", amount: 80, duration: 4 } ],
                     description: "Whatever comes, they're still standing when it's gone." },
      last_stand: { name: "Last Stand", kind: "skill", target: "single_enemy", mp_cost: 0, gesture: "lunge",
                    effects: [ { primitive: "physical", power: 160, grudge: 200 } ], description: "Everything the Bodyguard has taken for the others, given back at once." },
      escort: { name: "Escort", kind: "field", field_skill: "nerve", field_outcome: "safe_road", field_difficulty: "normal", effects: [],
                description: "Out in front, eyes on every ridge. Whatever waits on the road decides to wait for someone else." },

      # --- what the creatures do ---------------------------------------------------------
      talon: { name: "Talon", kind: "skill", target: "single_enemy", mp_cost: 0, effects: [ { primitive: "physical", power: 120, type: "wind" } ],
               description: "Down out of the sun." },
      bite: { name: "Bite", kind: "skill", target: "single_enemy", mp_cost: 0, effects: [ { primitive: "physical", power: 130 } ], description: "Teeth." },
      buckshot: { name: "Buckshot", kind: "skill", target: "all_enemies", mp_cost: 0, effects: [ { primitive: "physical", power: 55, type: "shot" } ],
                  description: "A scattergun at everyone in front of it." },
      quickdraw: { name: "Quickdraw", kind: "skill", target: "single_enemy", mp_cost: 0, effects: [ { primitive: "physical", power: 140, type: "shot" } ],
                   description: "From the hip." },
      powder_spit: { name: "Powder Spit", kind: "skill", target: "single_enemy", mp_cost: 0, effects: [ { primitive: "elemental", type: "fire", power: 14 },
                                                                                                    { primitive: "status", kind: "burn", chance: 40, duration: 2 } ],
                     description: "A mouthful of raw red salt, lit." },
      seam_quake: { name: "Seam Quake", kind: "skill", target: "all_enemies", mp_cost: 0, effects: [ { primitive: "elemental", type: "deep", power: 16 } ],
                    description: "The ground remembers what's under it." },
      deep_roar: { name: "Deep Roar", kind: "skill", target: "all_enemies", mp_cost: 0, effects: [ { primitive: "status", kind: "confuse", chance: 40, duration: 2 } ],
                   description: "A sound from under the world." },
      grow: { name: "Grow", kind: "skill", target: "self", mp_cost: 0, effects: [ { primitive: "buff", stat: "str", amount: 50, duration: 3 }, { primitive: "heal", power: 20 } ],
              description: "Hurt, it gets bigger." },
      rust_breath: { name: "Rust Breath", kind: "skill", target: "single_enemy", mp_cost: 0, effects: [ { primitive: "debuff", stat: "def", amount: 40, duration: 3 } ],
                     description: "Everything metal it breathes on goes soft." },
    ).freeze
  end
end
