# frozen_string_literal: true

# The Bestiary: what's met on the mesa roads and in the seams, the
# duellists (who fight one against one, with a technique and their tells),
# the giants woken from the deep, and a Ranger's animals. (Seeds::Oda)
module Seeds
  module Oda
    MONSTERS = {
      # A Ranger's animals (the summon primitive): called, not met.
      hawk: { name: "Hawk", level: 3, stats: stats(max_hp: 45, str: 13, atk: 10, agi: 32, def: 3, mdef: 3), base_type: "wind",
              exp: 0, gil: 0, abp: 0, ai_script: [ { use: "talon" } ], description: "A ranger's hawk. Stays up there all fight, coming down when it likes." },
      hound: { name: "Hound", level: 5, stats: stats(max_hp: 70, str: 18, atk: 14, agi: 20, def: 5, mdef: 3), base_type: "steel",
               exp: 0, gil: 0, abp: 0, ai_script: [ { use: "bite" } ], description: "Brindled, scarred, and very happy to see you." },

      # --- the mesa roads ---------------------------------------------------------------
      dust_coyote: { name: "Dust Coyote", level: 1, stats: stats(max_hp: 80, str: 12, atk: 11, agi: 14, def: 3, mdef: 2),
                     base_type: "wind", exp: 30, gil: 20, abp: 2,
                     ai_script: [ { if: { chance: 30 }, use: "bite" }, { use: "attack" } ], drops: [ { item: "tonic", chance: 25 } ],
                     description: "Ribs, teeth and a pack's patience." },
      powder_rat: { name: "Powder Rat", level: 2, stats: stats(max_hp: 70, max_mp: 20, str: 9, mag: 15, atk: 8, agi: 18, def: 2, mdef: 6),
                    base_type: "fire", exp: 36, gil: 25, abp: 2,
                    ai_script: [ { if: { chance: 50 }, use: "powder_spit" }, { use: "attack" } ], drops: [ { item: "fire_shot", chance: 15 } ],
                    description: "Grew up in a powder store and ate what it found. Glows faintly at night." },
      road_bandit: { name: "Road Bandit", level: 2, stats: stats(max_hp: 110, str: 14, atk: 14, agi: 12, def: 6, mdef: 3),
                     base_type: "steel", exp: 45, gil: 60, abp: 2,
                     ai_script: [ { if: { chance: 30 }, use: "buckshot" }, { use: "attack" } ],
                     drops: [ { item: "tonic", chance: 30 }, { item: "charcoal_draught", chance: 15 } ],
                     description: "A scattergun, a bandana and debts. Refused a duel once, and has been running since." },
      rust_lizard: { name: "Rust Lizard", level: 3, stats: stats(max_hp: 150, str: 15, atk: 14, agi: 8, def: 14, mdef: 4),
                     base_type: "earth", exp: 55, gil: 30, abp: 3,
                     ai_script: [ { if: { chance: 35 }, use: "rust_breath" }, { use: "attack" } ], drops: [ { item: "iron_bracer", chance: 5 } ],
                     description: "Lives under the mesas and eats iron. Your iron, by preference." },
      storm_crow: { name: "Storm Crow", level: 3, stats: stats(max_hp: 90, max_mp: 20, mag: 18, str: 10, atk: 9, agi: 26, def: 3, mdef: 8),
                    base_type: "thunder", exp: 50, gil: 25, abp: 3,
                    ai_script: [ { if: { chance: 50 }, use: "thunder" }, { use: "attack" } ], drops: [ { item: "thunder_shot", chance: 15 } ],
                    description: "Flies ahead of the dry storms and pecks at anything metal." },
      seam_crawler: { name: "Seam Crawler", level: 4, stats: stats(max_hp: 160, mag: 16, str: 15, atk: 14, agi: 10, def: 10, mdef: 10),
                      base_type: "deep", exp: 70, gil: 40, abp: 3,
                      ai_script: [ { if: { chance: 30 }, use: "seam_quake" }, { use: "attack" } ], drops: [ { item: "charcoal_draught", chance: 25 } ],
                      description: "Something small that came up a seam. Steel goes into it like into wet sand." },
      company_rifleman: { name: "Company Rifleman", level: 4, stats: stats(max_hp: 130, str: 16, atk: 18, agi: 14, def: 10, mdef: 5),
                          base_type: "shot", exp: 70, gil: 80, abp: 3,
                          ai_script: [ { if: { chance: 40 }, use: "quickdraw" }, { use: "attack" } ], drops: [ { item: "fire_shot", chance: 20 } ],
                          description: "In the Powder Company's grey, on the Company's pay, doing the Company's business." },
      salt_wraith: { name: "Salt Wraith", level: 5, undead: true, stats: stats(max_hp: 170, max_mp: 30, mag: 22, str: 10, atk: 10, agi: 16, def: 4, mdef: 18),
                     base_type: "water", exp: 90, gil: 50, abp: 4,
                     ai_script: [ { if: { chance: 40 }, use: "watera" }, { if: { chance: 20 }, use: "undertow" }, { use: "attack" } ],
                     description: "What the drowned belfry keeps. Healing hurts it." },

      # --- the duellists: one against one, by their technique, giving away their stance --
      smiling_draw: { name: "The Smiling Draw", level: 8, boss: true, technique: "wait",
                      stats: stats(max_hp: 420, max_mp: 30, str: 24, atk: 24, agi: 20, def: 14, mdef: 10, spr: 14),
                      base_type: "steel", exp: 300, gil: 400, abp: 10,
                      ai_script: [ { if: { round_multiple: 3 }, use: "iai_stance" }, { if: { chance: 30 }, use: "quickdraw" }, { use: "attack" } ],
                      tells: { "strike" => [ "Let's not keep the bell waiting.", "He stops smiling.", "Now, I think." ],
                               "guard" => [ "Your move, friend.", "He smiles wider.", "I've got all day." ],
                               "feint" => [ "Did you hear something?", "His hand drifts, then doesn't.", "Look at you, so serious." ] },
                      boss_line: "Noon's a fine time for it. Shall we?",
                      description: "Silas Crane: forty-one duels and he has smiled through every one. He collects them like other men collect coins." },
      bell_tower_brawler: { name: "Bell-Tower Brawler", level: 3, technique: "tie_win",
                            stats: stats(max_hp: 160, str: 17, atk: 15, agi: 10, def: 8, mdef: 4),
                            base_type: "earth", exp: 60, gil: 50, abp: 3, ai_script: [ { use: "attack" } ],
                            tells: { "strike" => [ "Hah!", "Cracks his knuckles." ], "guard" => [ "Come on, then.", "Plants his feet." ],
                                     "feint" => [ "Look over there!", "Grins at someone behind you." ] },
                            description: "Fights anybody under the bell for a round of drinks. Loses gracefully, mostly." },
      gunhand: { name: "Gunhand", level: 5, technique: "steady",
                 stats: stats(max_hp: 200, str: 18, atk: 20, agi: 22, def: 8, mdef: 6),
                 base_type: "shot", exp: 120, gil: 150, abp: 5,
                 ai_script: [ { if: { chance: 50 }, use: "quickdraw" }, { use: "attack" } ],
                 tells: { "strike" => [ "Fingers twitch over the grip.", "Draw." ], "guard" => [ "Steps back, slow.", "Waits." ],
                          "feint" => [ "Tips the hat.", "Whistles a few notes." ] },
                 description: "A hired pistol with a reputation and the nerve to keep it." },

      # --- the giants, woken from the deep (masks are made for them) -------------------------
      seam_giant: { name: "Seam Giant", level: 8, boss: true, giant: true,
                    stats: stats(max_hp: 900, max_mp: 50, str: 26, mag: 22, atk: 24, agi: 6, def: 18, mdef: 14),
                    base_type: "deep", exp: 400, gil: 300, abp: 12, status_immune: %w[stop doom],
                    ai_script: [ { if: { self_hp_below: 50 }, use: "grow", target: "self" }, { if: { round_multiple: 3 }, use: "seam_quake" },
                                 { if: { chance: 25 }, use: "deep_roar" }, { use: "attack" } ],
                    boss_line: "The seam opens like an eye.",
                    description: "Raw powder that stood up when the Company dug too deep. Every wound makes it bigger. Steel and shot glance off; a mask meets it as an equal." },
      ash_colossus: { name: "Ash Colossus", level: 10, boss: true, giant: true,
                      stats: stats(max_hp: 1200, max_mp: 60, str: 30, mag: 26, atk: 28, agi: 5, def: 22, mdef: 16),
                      base_type: "deep", exp: 600, gil: 500, abp: 15, status_immune: %w[stop doom sleep],
                      affinities: { "water" => "weak" },
                      ai_script: [ { if: { self_hp_below: 40 }, use: "grow", target: "self" }, { if: { round_multiple: 2 }, use: "inferno" },
                                   { if: { chance: 30 }, use: "seam_quake" }, { use: "attack" } ],
                      boss_line: "The ash on the mesa rises, and keeps rising, into a shape.",
                      description: "A burnt-out seam that woke angry. Fire inside, ash outside, and something very old looking out." },
      overseer: { name: "Overseer", level: 7, boss: true,
                  stats: stats(max_hp: 520, max_mp: 60, str: 20, mag: 22, atk: 20, agi: 14, def: 14, mdef: 12),
                  base_type: "shot", exp: 300, gil: 600, abp: 10,
                  ai_script: [ { if: { self_hp_below: 30 }, use: "smoke_bomb" }, { if: { round_multiple: 3 }, use: "reflect", target: "self" },
                               { if: { chance: 40 }, use: "buckshot" }, { use: "attack" } ],
                  boss_line: "The Company thanks you for your interest in its property.",
                  description: "Marrow Vey's own guns: a long coat, a scattergun and a ledger. Doesn't duel. Has people for that." },
      drowned_bellringer: { name: "Drowned Bellringer", level: 6, boss: true, undead: true,
                            stats: stats(max_hp: 600, max_mp: 60, mag: 24, str: 16, atk: 16, agi: 10, def: 10, mdef: 18),
                            base_type: "water", exp: 350, gil: 300, abp: 10,
                            ai_script: [ { if: { round_multiple: 3 }, use: "waterga" }, { if: { chance: 30 }, use: "undertow" }, { use: "attack" } ],
                            boss_line: "Under the water, the bell rings once.",
                            description: "Rang the noon bell for a duel that never came. The other one refused. Still waiting." }
    }.freeze
  end
end
